class cfgPatches
{
	class ax_grounded_csat_iran_2035_rf
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"RF_Data_Loadorder",
			"A3_Atlas_Data_F_Atlas_Loadorder",
			"ax_grounded_soldiers_editorpreviews"
		};
		author = "Axle";
		skipwhenmissingdependencies = 1;
	};
};

class cfgWeapons
{
	class H_HelmetAggressor_F;
	class H_HelmetHeavy_Black_RF: H_HelmetAggressor_F
	{
		hiddenSelectionsMaterials[]=
		{
			"lxRF\characters_rf\headgear\data\heavy_helmet.rvmat"
		};
	};
	class SMG_02_F;
	class srifle_DMR_01_black_RF;
	class arifle_ash12_blk_RF;
	class arifle_ash12_LR_blk_RF;
	class arifle_ash12_GL_blk_RF;
	class arifle_ash12_blk_Pointer_RF: arifle_ash12_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class arifle_ash12_blk_aco_snd_Pointer_RF: arifle_ash12_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_ACO_grn";
			};
			class LinkedItemsMuzzle
			{
				slot="MuzzleSlot";
				item="suppressor_127x55_small_RF";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class arifle_ash12_LR_blk_vrco_snd_Pointer_RF: arifle_ash12_LR_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_VRCO_RF";
			};
			class LinkedItemsMuzzle
			{
				slot="MuzzleSlot";
				item="suppressor_127x55_small_RF";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class arifle_ash12_GL_blk_aco_snd_Pointer_RF: arifle_ash12_GL_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_ACO_grn";
			};
			class LinkedItemsMuzzle
			{
				slot="MuzzleSlot";
				item="suppressor_127x55_small_RF";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class arifle_ash12_GL_blk_snd_Pointer_RF: arifle_ash12_GL_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsMuzzle
			{
				slot="MuzzleSlot";
				item="suppressor_127x55_small_RF";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class srifle_DMR_01_black_DMS_BI_Pointer_RF: srifle_DMR_01_black_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_DMS";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_02_F_blk";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class SMG_02_ACO_Pointer_F: SMG_02_F
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_ACO_grn_smg";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
};

class cfgVehicles
{
	class SoldierEB;
	class O_Soldier_base_F: SoldierEB
	{
	};
	class O_support_AMort_F;
	class O_support_CMort_RF: O_support_AMort_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_support_CMort_RF.jpg";
	};
	class O_Soldier_iran_base_F;
	class O_Soldier_iran_urban_base_F;
	class O_Soldier_SL_F;
	class O_Soldier_F;
	class O_Soldier_GL_F;
	class O_medic_F;
	class O_Soldier_AR_F;
	class O_soldier_UAV_F;
	class O_Soldier_HAT_F;
	class O_soldier_M_F: O_Soldier_iran_base_F
	{
		weapons[]=
		{
			"srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_soldierU_M_F: O_Soldier_iran_urban_base_F
	{
		weapons[]=
		{
			"srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_QRF_Soldier_SL_RF: O_Soldier_SL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_Soldier_SL_RF.jpg";
		weapons[]=
		{
			"arifle_ash12_LR_blk_vrco_snd_Pointer_RF",
			"hgun_DEagle_RF",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_ash12_LR_blk_vrco_snd_Pointer_RF",
			"hgun_DEagle_RF",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"7Rnd_50AE_Mag_RF",
			"7Rnd_50AE_Mag_RF",
			"7Rnd_50AE_Mag_RF",
			"HandGrenade",
			"HandGrenade",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"7Rnd_50AE_Mag_RF",
			"7Rnd_50AE_Mag_RF",
			"7Rnd_50AE_Mag_RF",
			"HandGrenade",
			"HandGrenade",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"V_TacVest_khk",
			"H_HelmetHeavy_Simple_Hex_RF",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_khk",
			"H_HelmetHeavy_Simple_Hex_RF",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class O_QRF_Soldier_RF: O_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_Soldier_RF.jpg";
		weapons[]=
		{
			"arifle_ash12_blk_aco_snd_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_ash12_blk_aco_snd_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class O_QRF_Soldier_GL_RF: O_Soldier_GL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_Soldier_GL_RF.jpg";
		weapons[]=
		{
			"arifle_ash12_GL_blk_aco_snd_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_ash12_GL_blk_aco_snd_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class O_QRF_medic_RF: O_medic_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_medic_RF.jpg";
		weapons[]=
		{
			"arifle_ash12_blk_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_ash12_blk_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"V_TacVest_khk",
			"H_HelmetHeavy_Simple_Hex_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_khk",
			"H_HelmetHeavy_Simple_Hex_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class O_QRF_Soldier_AR_RF: O_Soldier_AR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_Soldier_AR_RF.jpg";
		weapons[]=
		{
			"LMG_Zafir_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_Zafir_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class O_QRF_soldier_M_RF: O_soldier_M_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_soldier_M_RF.jpg";
		weapons[]=
		{
			"srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"10Rnd_762x54_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"V_TacVest_khk",
			"H_MilCap_ocamo",
			"G_Bandanna_beast",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_khk",
			"H_MilCap_ocamo",
			"G_Bandanna_beast",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class O_QRF_Soldier_UAV_RF: O_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_Soldier_UAV_RF.jpg";
		weapons[]=
		{
			"arifle_ash12_GL_blk_snd_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_ash12_GL_blk_snd_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_SmokeRed_shell_RF",
			"1Rnd_RC40_SmokeGreen_shell_RF",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"10Rnd_127x55_Mag_RF",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_SmokeRed_shell_RF",
			"1Rnd_RC40_SmokeGreen_shell_RF",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"H_HelmetHeavy_Simple_Hex_RF",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class O_QRF_Soldier_HAT_RF: O_Soldier_HAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_QRF_Soldier_HAT_RF.jpg";
		weapons[]=
		{
			"SMG_02_ACO_Pointer_F",
			"launch_O_Vorona_brown_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_02_ACO_Pointer_F",
			"launch_O_Vorona_brown_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Vorona_HEAT",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"30Rnd_9x21_Mag_SMG_02",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Vorona_HEAT",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"V_TacVest_khk",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_khk",
			"H_HelmetHeavy_Simple_Hex_RF",
			"G_Balaclava_blk_lxWS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class Atlas_O_Soldier_R_base_F: O_Soldier_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_Medic_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
	};
	class Atlas_O_Soldier_R_Exp_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_GL_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
	};
	class Atlas_O_Soldier_R_AA_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AA",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AA",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_AT_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AT",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AT",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_LAT_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"RPG32_F",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"RPG32_F",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_SL_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
	};
	class Atlas_O_Soldier_R_TL_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
	};
};