class CfgPatches
{
	class ax_faction_russia_grfu_reconhood
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"ReconCloaks_Characters_Headgear",
			"ax_faction_russia_grfu"
		};
		author="Axle";
		skipwhenmissingdependencies=1;
	};
};

class CfgVehicles
{
	class O_R_soldier_M_F;
	class O_R_Patrol_Soldier_M2_F: O_R_soldier_M_F
    {
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "ReconCloaks_H_Hood_Cap_rutaiga",
            "G_Bandanna_oli",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_ep_F"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "ReconCloaks_H_Hood_Cap_rutaiga",
            "G_Bandanna_oli",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_ep_F"
        };
    };
	class O_R_ghillie_base_F;
	class O_R_spotter_F: O_R_ghillie_base_F
	{
		uniformClass="U_O_R_Gorka_01_camo_F";
		backpack="AX_B_EAssaultPack_taiga_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_taiga",
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_taiga",
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
	class O_R_sniper_F: O_R_ghillie_base_F
	{
		uniformClass="U_O_R_Gorka_01_camo_F";
		backpack="B_AssaultPack_taiga_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_taiga",
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_taiga",
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
	class O_R_spotter_ard_F: O_R_spotter_F
	{
		uniformClass="U_O_R_Gorka_01_brown_F";
		backpack="AX_B_EAssaultPack_arid_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_khk",
			"Aegis_V_ChestrigEast_RUarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_khk",
			"Aegis_V_ChestrigEast_RUarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
	class O_R_sniper_ard_F: O_R_sniper_F
	{
		uniformClass="U_O_R_Gorka_01_brown_F";
		backpack="B_AssaultPack_rgr";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_khk",
			"Aegis_V_ChestrigEast_RUarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHoodSpec_khk",
			"Aegis_V_ChestrigEast_RUarid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
};