    class AX_O_Plane_Fighter_j10_F: PLAAF_Fighter_J10
    {
        scope=1;
		scopeCurator=1;
		side=0;
		displayName="$STR_A3_GRFU_Plane_Fighter_j10_F0";
		faction="OPF_F";
		crew="O_Fighter_Pilot_F";
		typicalCargo[]=
		{
			"O_Fighter_Pilot_F"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\vehicles_f_plaav\data\j10\J10_ext_co.paa"
		};
    };
	class AX_O_T_Plane_Fighter_j10_F: AX_O_Plane_Fighter_j10_F
    {
        scope=2;
		scopeCurator=2;
		side=0;
		editorPreview="\ax_grounded_futura\vehicles_f_plaav\previews\AX_O_T_Plane_Fighter_j10_F.jpg";
		faction="OPF_T_F";
		crew="O_T_Pilot_F";
		typicalCargo[]=
		{
			"O_T_Pilot_F"
		};
    };
    class AX_O_Plane_Fighter_j11_F: PLAAF_Fighter_J11
    {
        scope=1;
		scopeCurator=1;
		side=0;
		displayName="$STR_A3_GRFU_Plane_Fighter_j11_F0";
		faction="OPF_F";
		crew="O_Fighter_Pilot_F";
		typicalCargo[]=
		{
			"O_Fighter_Pilot_F"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\vehicles_f_plaav\data\j11\J11_ext_co.paa"
		};
    };
    class AX_O_T_Plane_Fighter_j11_F: AX_O_Plane_Fighter_j11_F
    {
        scope=2;
		scopeCurator=2;
		side=0;
		editorPreview="\ax_grounded_futura\vehicles_f_plaav\previews\AX_O_T_Plane_Fighter_j11_F.jpg";
		faction="OPF_T_F";
		crew="O_T_Pilot_F";
		typicalCargo[]=
		{
			"O_T_Pilot_F"
		};
    };
    class AX_O_Plane_Fighter_j15_F: PLAAF_Fighter_J15
    {
        scope=1;
		scopeCurator=1;
		side=0;
		displayName="$STR_A3_GRFU_Plane_Fighter_j15_F0";
		faction="OPF_F";
		crew="O_Fighter_Pilot_F";
		typicalCargo[]=
		{
			"O_Fighter_Pilot_F"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\vehicles_f_plaav\data\j15\J15_ext_co.paa"
		};
    };
    class AX_O_T_Plane_Fighter_j15_F: AX_O_Plane_Fighter_j15_F
    {
        scope=2;
		scopeCurator=2;
		side=0;
		editorPreview="\ax_grounded_futura\vehicles_f_plaav\previews\AX_O_T_Plane_Fighter_j15_F.jpg";
		faction="OPF_T_F";
		crew="O_T_Pilot_F";
		typicalCargo[]=
		{
			"O_T_Pilot_F"
		};
    };
	class AX_O_Plane_Fighter_j16_F: PLAAF_Fighter_J16
    {
        scope=1;
		scopeCurator=1;
		side=0;
		displayName="$STR_A3_GRFU_Plane_Fighter_j16_F0";
		faction="OPF_F";
		crew="O_Fighter_Pilot_F";
		typicalCargo[]=
		{
			"O_Fighter_Pilot_F"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\vehicles_f_plaav\data\j16\J16_ext_co.paa"
		};
    };
	class AX_O_T_Plane_Fighter_j16_F: AX_O_Plane_Fighter_j16_F
    {
        scope=2;
		scopeCurator=2;
		side=0;
		editorPreview="\ax_grounded_futura\vehicles_f_plaav\previews\AX_O_T_Plane_Fighter_j16_F.jpg";
		faction="OPF_T_F";
		crew="O_T_Pilot_F";
		typicalCargo[]=
		{
			"O_T_Pilot_F"
		};
    };
	class AX_O_Plane_Fighter_j20_F: PLAAF_Fighter_J20
    {
        scope=1;
		scopeCurator=1;
		side=0;
		displayName="$STR_A3_GRFU_Plane_Fighter_j20_F0";
		faction="OPF_F";
		crew="O_Fighter_Pilot_F";
		typicalCargo[]=
		{
			"O_Fighter_Pilot_F"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\vehicles_f_plaav\data\j20\J20_ext_co.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"ax_grounded_futura\vehicles_f_plaav\data\j20\J20A_Ext.rvmat"
		};
    };
	class AX_O_T_Plane_Fighter_j20_F: AX_O_Plane_Fighter_j20_F
    {
        scope=2;
		scopeCurator=2;
		side=0;
		editorPreview="\ax_grounded_futura\vehicles_f_plaav\previews\AX_O_T_Plane_Fighter_j20_F.jpg";
		faction="OPF_T_F";
		crew="O_T_Pilot_F";
		typicalCargo[]=
		{
			"O_T_Pilot_F"
		};
    };