    class AX_G_Bandanna_shemag_tan: G_Bandanna_blk
	{
		author="$STR_A3_MCFU_Axle";
		displayName="$STR_A3_MCFU_G_Bandana_shemag_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\ui\icon_G_Bandanna_shemag_tan_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\headgear_bandMask_shemag_CO.paa"
		};
		identityTypes[]={};
	};
	class AX_G_Bandanna_shemag_shades_tan: G_Bandanna_shades
	{
		author="$STR_A3_MCFU_Axle";
		displayName="$STR_A3_MCFU_G_Bandana_shemag_shades_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\ui\icon_G_Bandanna_shemag_shades_tan_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\headgear_bandMask_shemag_CO.paa",
			"\a3\characters_f\heads\glasses\data\joeyx_black_ca.paa"
		};
		identityTypes[]={};
	};
	class AX_G_Bandanna_shemag_sport_tan: G_Bandanna_sport
	{
		author="$STR_A3_MCFU_Axle";
		displayName="$STR_A3_MCFU_G_Bandana_shemag_sport_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\ui\icon_G_Bandanna_shemag_sport_tan_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\headgear_bandMask_shemag_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\sunglasses_sport_black_ca.paa"
		};
		identityTypes[]={};
	};
	class AX_G_Balaclava_mesh_blk_F: G_Balaclava_light_blk_F
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_MCFU_G_Balaclava_mesh_blk_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\ui\icon_G_Balaclava_mesh_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Balaclava_mesh_blk_F_CO.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Mesh_Balaclava.rvmat"
		};
		identityTypes[]={};
	};
	class AX_G_Balaclava_mesh_coy_F: AX_G_Balaclava_mesh_blk_F
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_MCFU_G_Balaclava_mesh_coy_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\ui\icon_G_Balaclava_mesh_coy_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Balaclava_mesh_coy_F_CO.paa"
		};
	};
	class AX_G_Balaclava_mesh_G_blk_F: G_Balaclava_light_G_blk_F
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_MCFU_G_Balaclava_mesh_G_blk_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\ui\icon_G_Balaclava_mesh_G_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Balaclava_mesh_blk_F_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Mesh_Balaclava.rvmat",
			"\A3\Characters_F\Heads\Glasses\Data\G_Combat.rvmat"
		};
	};
	class AX_G_Balaclava_mesh_G_coy_F: AX_G_Balaclava_mesh_G_blk_F
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_MCFU_G_Balaclava_mesh_G_coy_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\ui\icon_G_Balaclava_mesh_G_coy_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Balaclava_mesh_coy_F_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
	};