    class EF_B_Marine_Des_Base_1: SoldierWB
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Des_CO.paa"
		};
	};
	class EF_B_Marine_Des_Base_2: EF_B_Marine_Des_Base_1{};
	class EF_B_Marine_Des_Base_3: EF_B_Marine_Des_Base_1{};
	class EF_B_Marine_Des_Base_4: EF_B_Marine_Des_Base_1{};
	class EF_B_Marine_Des_Base_5: EF_B_Marine_Des_Base_1{};
	class EF_B_Marine_Des_Base_6: EF_B_Marine_Des_Base_1{};
	class EF_B_Marine_Wdl_Base_1: EF_B_Marine_Des_Base_1
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Wdl_CO.paa"
		};
	};
	class EF_B_Marine_Wdl_Base_2: EF_B_Marine_Des_Base_2
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Wdl_CO.paa"
		};
	};
	class EF_B_Marine_Wdl_Base_3: EF_B_Marine_Des_Base_3
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Wdl_CO.paa"
		};
	};
	class EF_B_Marine_Wdl_Base_4: EF_B_Marine_Des_Base_4
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Wdl_CO.paa"
		};
	};
	class EF_B_Marine_Wdl_Base_5: EF_B_Marine_Des_Base_5
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Wdl_CO.paa"
		};
	};
	class EF_B_Marine_Wdl_Base_6: EF_B_Marine_Des_Base_6
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Wdl_CO.paa"
		};
	};
    class EF_B_Marine_Diver_Des_Base: EF_B_Marine_Des_Base_1
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Des_CO.paa",
			"\ef\ef_marines\data\diving_gear_co.paa"
		};
	};
	class EF_B_Marine_Diver_Wdl_Base: EF_B_Marine_Diver_Des_Base
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\US_Marines_FROG_Wdl_CO.paa",
			"\ef\ef_marines\data\diving_gear_co.paa"
		};
	};
	class EF_B_Marine_Recon_Des_base: EF_B_Marine_Des_Base_1{};
	class EF_B_Marine_Recon_Wdl_base: EF_B_Marine_Wdl_Base_1{};
	class AX_uniform_B_MC_CombatUniform_wdl: B_soldier_F
    {
        scope=1;
        scopeCurator=0;
        uniformClass="AX_U_B_MC_CombatUniform_wdl";
        hiddenSelectionsTextures[]=
        {
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
        };
    };
    class AX_uniform_B_MC_CombatUniform_des: B_soldier_F
    {
        scope=1;
        scopeCurator=0;
        uniformClass="AX_U_B_MC_CombatUniform_des";
        hiddenSelectionsTextures[]=
        {
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
        };
    };
	class AX_uniform_B_MC_CombatUniform_wdl_cb: B_soldier_F
    {
        scope=1;
        scopeCurator=0;
        uniformClass="AX_U_B_MC_CombatUniform_wdl_cb";
        hiddenSelectionsTextures[]=
        {
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_CB_co.paa"
        };
    };
    class AX_uniform_B_MC_CombatUniform_des_cb: B_soldier_F
    {
        scope=1;
        scopeCurator=0;
        uniformClass="AX_U_B_MC_CombatUniform_des_cb";
        hiddenSelectionsTextures[]=
        {
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_CB_co.paa"
        };
    };
	class AX_uniform_B_MC_CombatUniform_vest_wdl: B_Soldier_SL_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_vest_des: B_Soldier_SL_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt_wdl: B_soldier_AR_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt_wdl";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa",
			"\A3\Characters_F_Enoch\Uniforms\Data\basicbody_wdl_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt_des: B_soldier_AR_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt_des";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa",
			"\lxws\characters_f_lxws\data\NATO\basicbody_sand_co.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt2_wdl: B_ION_soldier_AR_lxWS
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt2_wdl";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa",
			"", //"\lxWS\characters_1_f_lxws\uniform\data\pmc_watch_co.paa",
			"\A3\Characters_F_Enoch\Uniforms\Data\basicbody_wdl_CO.paa",
			"lxWS\characters_f_lxws\data\SFIA\c_cloth1_green_co.paa"
		};
	};
    class AX_uniform_B_MC_CombatUniform_tshirt2_des: B_ION_soldier_AR_lxWS
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt2_des";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa",
			"", //"\lxWS\characters_1_f_lxws\uniform\data\pmc_watch_co.paa",
			"\lxws\characters_f_lxws\data\NATO\basicbody_sand_co.paa",
			"lxWS\characters_f_lxws\data\SFIA\c_cloth1_sand_co.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt3_wdl: B_Soldier_F
	{
		scope=1;
		scopeCurator=0;
		model="\lxws\characters_1_f_lxws\uniform\b_soldier_01_shirt_lxws.p3d";
		uniformClass="AX_U_B_MC_CombatUniform_tshirt3_wdl";
		hiddenSelections[]=
		{
			"Camo",
			"Camo1",
			"Camo2",
			"Insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\c_cloth1_grn_CO.paa",
			""
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt3_des: AX_uniform_B_MC_CombatUniform_tshirt3_wdl
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt3_des";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\c_cloth1_tan_CO.paa",
			""
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt3_wdl_blk: AX_uniform_B_MC_CombatUniform_tshirt3_wdl
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt3_wdl_blk";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\c_cloth1_blk_CO.paa",
			""
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt3_des_blk: AX_uniform_B_MC_CombatUniform_tshirt3_wdl
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt3_des_blk";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\c_cloth1_blk_CO.paa",
			""
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt3_wdl_coy: AX_uniform_B_MC_CombatUniform_tshirt3_wdl
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt3_wdl_coy";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\c_cloth1_coy_CO.paa",
			""
		};
	};
	class AX_uniform_B_MC_CombatUniform_tshirt3_des_coy: AX_uniform_B_MC_CombatUniform_tshirt3_wdl
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_tshirt3_des_coy";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\c_cloth1_coy_CO.paa",
			""
		};
	};
	class AX_uniform_B_MC_CombatUniform_shirt_wdl: B_ION_soldier_UAV_01_lxWS
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_shirt_wdl";
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_epb\Guerrilla\Data\ig_guerrilla5_1_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_shirt_des: B_ION_soldier_UAV_01_lxWS
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_shirt_des";
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_epb\Guerrilla\Data\ig_guerrilla5_1_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
	};
	class AX_uniform_B_MC_SurvivalFatigues_wdl: b_soldier_survival_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_SurvivalFatigues_wdl";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa",
			"\A3\Characters_F\Common\Data\diver_suit_nato_CO.paa",
			"\A3\Characters_F\Common\Data\diver_equip_nato_CO.paa",
			"\A3\Characters_F_Enoch\Uniforms\Data\basicbody_wdl_CO.paa"
		};
	};
	class AX_uniform_B_MC_SurvivalFatigues_des: b_soldier_survival_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_SurvivalFatigues_des";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa",
			"\A3\Characters_F\Common\Data\diver_suit_nato_CO.paa",
			"\A3\Characters_F\Common\Data\diver_equip_nato_CO.paa",
			"\lxws\characters_f_lxws\data\NATO\basicbody_sand_co.paa"
		};
	};
	class AX_uniform_B_MC_StealthUniform_wdl_F: B_CTRG_Soldier_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_StealthUniform_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpw_co.paa"
		};
	};
	class AX_uniform_B_MC_StealthUniform_des_F: B_CTRG_Soldier_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_StealthUniform_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpd_co.paa"
		};
	};
	class AX_uniform_B_MC_StealthUniform_RolledUp_wdl_F: B_CTRG_Soldier_3_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_StealthUniform_RolledUp_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpw_co.paa"
		};
	};
	class AX_uniform_B_MC_StealthUniform_RolledUp_des_F: B_CTRG_Soldier_3_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_StealthUniform_RolledUp_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpd_co.paa"
		};
	};
	class AX_uniform_B_MC_HeliPilotCoveralls: B_Helipilot_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_HeliPilotCoveralls";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_helipilot_CO.paa"
		};
	};
	class AX_uniform_B_MC_HeliPilotCoveralls_tan: B_Helipilot_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_HeliPilotCoveralls_tan";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_helipilot_tan_CO.paa"
		};
	};
	class AX_uniform_B_MC_PilotCoveralls: B_Helipilot_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_PilotCoveralls";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_CO.paa"
		};
	};
	class AX_uniform_B_MC_PilotCoveralls_tan: B_Helipilot_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_PilotCoveralls_tan";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_tan_CO.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_worn: B_Helipilot_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_worn";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_CO.paa"
		};
	};
	class EF_B_Navy_FlightDeckCrew: B_Helipilot_F
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_CO.paa"
		};
	};
	class AX_uniform_B_MC_HeliPilotCoveralls_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_HeliPilotCoveralls_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_helipilot_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coy_boots.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\rg_gloves.paa"
		};
	};
	class AX_uniform_B_MC_HeliPilotCoveralls_Gloves_tan: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_HeliPilotCoveralls_Gloves_tan";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_helipilot_tan_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coy_boots.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\rg_gloves.paa"
		};
	};
	class AX_uniform_B_USN_HeliPilotCoveralls_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_HeliPilotCoveralls_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_helipilot_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_HeliPilotCoveralls_Gloves_tan: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_HeliPilotCoveralls_Gloves_tan";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_helipilot_tan_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_MC_PilotCoveralls_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_PilotCoveralls_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coy_boots.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\rg_gloves.paa"
		};
	};
	class AX_uniform_B_MC_PilotCoveralls_Gloves_tan: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_PilotCoveralls_Gloves_tan";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_tan_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coy_boots.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\rg_gloves.paa"
		};
	};
	class AX_uniform_B_USN_PilotCoveralls_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_PilotCoveralls_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_pilot_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_PilotCoveralls_Gloves_tan: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_PilotCoveralls_Gloves_tan";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_pilot_tan_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_White_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_White_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_white_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_Yellow_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_Yellow_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_yellow_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_Red_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_Red_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_red_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_Green_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_Green_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_green_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_Brown_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_Brown_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_brown_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_Blue_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_Blue_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_blue_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
	class AX_uniform_B_USN_CrewCoveralls_Violet_Gloves: I_E_Uniform_01_coveralls_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_USN_CrewCoveralls_Violet_Gloves";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_violet_CO.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_pants_co.paa",
			"a3\characters_f_enoch\uniforms\data\i_e_soldier_01_gloves_black_co.paa"
		};
	};
/*
	class AX_uniform_B_MC_CombatUniformNCU_01_wdl_F: Atlas_I_E_SF_CombatUniformNCU_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniformNCU_01_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniformNCU_02_wdl_F: Atlas_I_E_SF_CombatUniformNCU_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniformNCU_02_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniformNCU_01_des_F: Atlas_I_E_SF_CombatUniformNCU_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniformNCU_01_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniformNCU_02_des_F: Atlas_I_E_SF_CombatUniformNCU_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniformNCU_02_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
*/
	class AX_uniform_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_IHWCU_NCU_01.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_blk_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_IHWCU_NCU_01_des_F: AX_uniform_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_IHWCU_NCU_01_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_blk_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_IHWCU_NCU_02.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_blk_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_IHWCU_NCU_02_des_F: AX_uniform_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_IHWCU_NCU_02_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\U_UniformIHWCU_blk_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_01.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camoboots",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpw_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_01_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_cb2_F: AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb2_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_flag_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_cb2_F: AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_01_des_cb2_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_flag_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_02.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camoboots",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_02_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_02_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_02_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_02_des_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_02_des_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_03.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camoboots",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_grn_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F: AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_brn_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_tan_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_des_brn_F: AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_des_brn_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_brn_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_01_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_Cloak_01.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camoboots",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_Cloak_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_oli_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\headgear\data\H_ReconCloak_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_01_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_Cloak_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu2_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\headgear\data\H_ReconCloak_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\Boots_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_unbl_01.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpw_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb2_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb2_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_flag_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb2_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb2_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_flag_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_unbl_02.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_des_cb_F: AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_cb_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_unbl_03.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_grn_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_brn_F: AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_brn_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_brn_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_tan_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_des_brn_F: AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_des_brn_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\basicbody_alt_brn_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa"
		};
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_wdl_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\U_Uniform_G3_NCU_Cloak_unbl_01.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"insignia"
		};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_Cloak_unbl_wdl_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_oli_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpw_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\headgear\data\H_ReconCloak_coy_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_des_F: AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_wdl_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_Cloak_unbl_des_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_g3_coy_co.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_ncu_mpd_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\CombatGloves_coy_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\headgear\data\H_ReconCloak_coy_CO.paa"
		};
	};
	class AX_uniform_B_USN_CombatUniform_01_aor2_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\lxws\characters_f_lxws\uniform\I_E_Soldier_01_lxWS.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"flag",
			"insignia"
		};
		uniformClass="AX_U_B_USN_CombatUniform_01_aor2_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_usncu_01_aor2.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_usncu_02_aor2.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_injury.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_injury.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_Pants.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_Pants_injury.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_Pants_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_USN_CombatUniform_02_aor2_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\a3\Characters_F_Enoch\Uniforms\I_E_Soldier_01_ShortSleeve_F.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"insignia"
		};
		uniformClass="AX_U_B_USN_CombatUniform_02_aor2_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_usncu_01_aor2.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_usncu_02_aor2.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_injury.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_injury.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_Pants.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_Pants_injury.rvmat",
				"a3\Characters_F_Enoch\Uniforms\Data\I_E_Soldier_01_Pants_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_B_USN_CombatUniform_03_aor2_F: B_soldier_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		model="\A3\Characters_F_Gamma\Guerrilla\IG_Guerrilla1_1.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3"
		};
		uniformClass="AX_U_B_USN_CombatUniform_03_aor2_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\c_cloth1_khk_scarf_CO.paa",
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing_usncu_02_aor2.paa",
			""
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"A3\Characters_f\Civil\Data\c_cloth1.rvmat",
				"A3\Characters_f\Civil\Data\c_cloth1_injury.rvmat",
				"A3\Characters_f\Civil\Data\c_cloth1_injury.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\ia_soldier_01_clothing.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\ia_soldier_01_clothing_injury.rvmat",
				"A3\Characters_F_Beta\INDEP\Data\ia_soldier_01_clothing_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};