	class AX_U_B_MC_CombatUniform_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_wdl_cb: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpw_cb_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_wdl_cb";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_des_cb: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpd_cb_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_des_cb";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_vest_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_vest_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_vest_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_vest_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_vest_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_vest_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt_wdl";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt_des";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt2_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt2_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt2_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt2_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_tshirt2_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt2_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt2_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt2_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_tshirt3_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_wdl_blk: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_wdl_blk_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpw_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_wdl_blk";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_des_blk: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_des_blk_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpd_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_des_blk";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_wdl_coy: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_wdl_coy_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpw_coy_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_wdl_coy";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_des_coy: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_des_coy_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpd_coy_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_des_coy";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_shirt_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_shirt_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_shirt_mpw_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_shirt_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_shirt_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_shirt_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_shirt_mpd_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_shirt_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_SurvivalFatigues_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_SurvivalFatigues_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_SurvivalFatigues_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\characters_f\common\data\diver_suit_nato_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_SurvivalFatigues_wdl";
			containerClass="Supply40";
			uniformType="Neopren";
			mass=60;
		};
	};
	class AX_U_B_MC_SurvivalFatigues_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_SurvivalFatigues_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_SurvivalFatigues_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\characters_f\common\data\diver_suit_nato_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_SurvivalFatigues_des";
			containerClass="Supply40";
			uniformType="Neopren";
			mass=60;
		};
	};
	class AX_U_B_MC_StealthUniform_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_StealthUniform_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_StealthUniform_RolledUp_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_RolledUp_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_RolledUp_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_StealthUniform_RolledUp_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_RolledUp_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_RolledUp_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_HeliPilotCoveralls: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_MCFU_U_B_MC_HeliPilotCoveralls_F0";
		picture="\A3\characters_f\data\ui\icon_U_B_coveralls_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_helipilot_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_HeliPilotCoveralls";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_HeliPilotCoveralls_tan: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_MCFU_U_B_MC_HeliPilotCoveralls_tan_F0";
		picture="\A3\characters_f\data\ui\icon_U_B_coveralls_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_helipilot_tan_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_HeliPilotCoveralls_tan";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_PilotCoveralls: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_MCFU_U_B_MC_PilotCoveralls_F0";
		picture="\A3\characters_f\data\ui\icon_U_B_coveralls_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_PilotCoveralls";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_PilotCoveralls_tan: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_MCFU_U_B_MC_PilotCoveralls_tan_F0";
		picture="\A3\characters_f\data\ui\icon_U_B_coveralls_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_tan_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_PilotCoveralls_tan";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_HeliPilotCoveralls_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_HeliPilotCoveralls_Gloves_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_HeliPilotCoveralls_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_helipilot_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_HeliPilotCoveralls_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_HeliPilotCoveralls_Gloves_tan: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_HeliPilotCoveralls_Gloves_tan_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_HeliPilotCoveralls_Gloves_tan_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_helipilot_tan_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_HeliPilotCoveralls_Gloves_tan";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_HeliPilotCoveralls_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_USN_HeliPilotCoveralls_Gloves_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_HeliPilotCoveralls_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_helipilot_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_HeliPilotCoveralls_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_HeliPilotCoveralls_Gloves_tan: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_USN_HeliPilotCoveralls_Gloves_tan_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_HeliPilotCoveralls_Gloves_tan_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_helipilot_tan_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_HeliPilotCoveralls_Gloves_tan";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_PilotCoveralls_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_PilotCoveralls_Gloves_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_PilotCoveralls_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_PilotCoveralls_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_PilotCoveralls_Gloves_tan: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_PilotCoveralls_Gloves_tan_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_PilotCoveralls_Gloves_tan_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usmc_pilot_tan_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_PilotCoveralls_Gloves_tan";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_PilotCoveralls_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_USN_PilotCoveralls_Gloves_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_PilotCoveralls_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_pilot_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_PilotCoveralls_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_PilotCoveralls_Gloves_tan: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_USN_PilotCoveralls_Gloves_tan_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_PilotCoveralls_Gloves_tan_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_usn_pilot_tan_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_PilotCoveralls_Gloves_tan";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_worn: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_worn";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_worn_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_worn";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_Gloves";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ef\ef_marines\Data\u_coveralls_navy_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_White_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_White";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_White_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_white_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_White_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_Yellow_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_Yellow";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_Yellow_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_yellow_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_Yellow_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_Red_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_Red";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_Red_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_red_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_Red_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_Green_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_Green";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_Green_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_green_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_Green_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_Brown_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_Brown";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_Brown_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_brown_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_Brown_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_Blue_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_Blue";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_Blue_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_blue_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_Blue_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_USN_CrewCoveralls_Violet_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_CrewCoveralls_Navy_Violet";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_USN_CrewCoveralls_Violet_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_navy_deck_violet_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_USN_CrewCoveralls_Violet_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_01_des_F_ca.paa"; //20% bright 20% contrast
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_02_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_02_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_02_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_02_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_02_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_02_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_02_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_01_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_02_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_02_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_02_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_02_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb2_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_cb2_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_des_cb2_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_cb2_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_des_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_des_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_wdl_brn_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_des_brn_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_des_brn_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_des_brn_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_des_brn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_Cloak_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_Cloak_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_Cloak_01_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_Cloak_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_Cloak_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_Cloak_01_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb2_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_cb2_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb2_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb2_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_wdl_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_unbl_02_des_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_brn_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_wdl_brn_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_wdl_brn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_des_brn_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_des_brn_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_des_brn_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_unbl_des_brn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_Cloak_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_Cloak_01_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_Cloak_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_Cloak_01_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	