	class AX_U_B_MC_CombatUniform_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_wdl_cb: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpw_cb_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_wdl_cb";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_des_cb: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpd_cb_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_des_cb";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_vest_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_vest_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_vest_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_vest_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_vest_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_vest_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt_wdl";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt_des";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt2_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt2_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt2_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt2_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_tshirt2_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt2_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt2_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt2_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
    class AX_U_B_MC_CombatUniform_tshirt3_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_wdl_blk: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_wdl_blk_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpw_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_wdl_blk";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_des_blk: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_des_blk_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpd_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_des_blk";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_wdl_coy: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_wdl_coy_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpw_coy_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_wdl_coy";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_tshirt3_des_coy: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_tshirt3_des_coy_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_tshirt3_mpd_coy_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_tshirt3_des_coy";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_shirt_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_shirt_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_shirt_mpw_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPW_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_shirt_wdl";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_shirt_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_MC_CombatUniform_shirt_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_shirt_mpd_blk_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_MPD_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_shirt_des";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_SurvivalFatigues_wdl: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_SurvivalFatigues_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_SurvivalFatigues_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\characters_f\common\data\diver_suit_nato_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_SurvivalFatigues_wdl";
			containerClass="Supply40";
			uniformType="Neopren";
			mass=60;
		};
	};
	class AX_U_B_MC_SurvivalFatigues_des: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_SurvivalFatigues_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_SurvivalFatigues_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"a3\characters_f\common\data\diver_suit_nato_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_SurvivalFatigues_des";
			containerClass="Supply40";
			uniformType="Neopren";
			mass=60;
		};
	};
	class AX_U_B_MC_StealthUniform_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_StealthUniform_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_StealthUniform_RolledUp_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_RolledUp_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpw_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_RolledUp_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_StealthUniform_RolledUp_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_StealthUniform_RolledUp_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_CombatUniform_vest_mpd_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_ctrg_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_StealthUniform_RolledUp_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_HeliPilotCoveralls: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_MCFU_U_B_MC_HeliPilotCoveralls_F0";
		picture="\A3\characters_f\data\ui\icon_U_B_coveralls_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Data\coveralls_sage_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_HeliPilotCoveralls";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_PilotCoveralls: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_MCFU_U_B_MC_PilotCoveralls_F0";
		picture="\A3\characters_f\data\ui\icon_U_B_coveralls_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_pilot_usmc_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_PilotCoveralls";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_HeliPilotCoveralls_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_HeliPilotCoveralls_Gloves_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_HeliPilotCoveralls_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_pilot_usmc_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_HeliPilotCoveralls_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_PilotCoveralls_Gloves: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_MC_PilotCoveralls_Gloves_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_PilotCoveralls_Gloves_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\coveralls_pilot_usmc_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_PilotCoveralls_Gloves";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_01_des_F_ca.paa"; //20% bright 20% contrast
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_02_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_02_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_02_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniformNCU_02_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_CombatUniformNCU_02_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniformNCU_02_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniformNCU_02_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_01_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_02_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_02_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_IHWCU_NCU_02_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_IHWCU_NCU_02_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_IHWCU_NCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_IHWCU_NCU_02_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb2_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_wdl_cb2_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_01_des_cb2_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_01_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_01_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_01_des_cb2_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_wdl_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_wdl_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_02_des_cb_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_02_des_cb_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_02_des_cb_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_02_des_cb_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_wdl_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_wdl_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_wdl_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_wdl_brn_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpw_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_wdl_brn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_des_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=2;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_des_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_des_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_des_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_B_MC_CombatUniform_G3_NCU_tee_des_brn_F: Uniform_Base
	{
		author="$STR_A3_MCFU_Axle";
		scope=1;
		displayName="$STR_A3_MCFU_U_B_G3_NCU_tee_des_brn_F0";
		picture="\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\ui\icon_U_B_MC_CombatUniform_G3_NCU_tee_des_brn_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
            "\ax_aegisefusmc\characters_f_usmc_futura\uniforms\data\clothing1_mpd_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_B_MC_CombatUniform_G3_NCU_tee_des_brn_F";
			containerClass="Supply40";
			mass=40;
		};
	};