    class None_ru: None
	{
		identityTypes[]=
		{
			"G_RUSSIA_default",
			300,
			"G_RUSSIA_officer",
			500,
			"G_RUSSIA_sf",
			300
		};
	};
	class G_Balaclava_blk: None
	{
	};
	class G_Balaclava_oli: G_Balaclava_blk
	{
	};
	class AX_G_Balaclava_3hole_blk_ru: G_Balaclava_blk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava_blk_CO.paa"
		};
		identityTypes[]=
		{
			"G_RUSSIA_default",
			50,
			"G_RUSSIA_sf",
			50
		};
	};
	class AX_G_Balaclava_3hole_grn_ru: G_Balaclava_oli
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava_grn_CO.paa"
		};
		identityTypes[]=
		{
			"G_RUSSIA_default",
			50,
			"G_RUSSIA_sf",
			50
		};
	};
	class AX_G_Balaclava_3hole_combat_blk_ru: AX_G_Balaclava_3hole_blk_ru
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_combat0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_combat.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_combat_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava.rvmat",
			"\a3\characters_f\heads\glasses\Data\G_Combat.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava_blk_CO.paa",
			"\a3\characters_f\heads\glasses\data\g_combat_ca.paa"
		};
		mass=10;
		identityTypes[]={};
	};
	class AX_G_Balaclava_3hole_combat_grn_ru: AX_G_Balaclava_3hole_combat_blk_ru
	{
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_combat0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava_grn_CO.paa",
			"\a3\characters_f\heads\glasses\data\g_combat_ca.paa"
		};
	};
	class G_Balaclava_3hole_lowprofile_blk_ru: G_Balaclava_blk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_lowprofile0";
		model="\A3\Characters_F_Bootcamp\Guerrilla\g_balaclava_lowprofile.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_lowprofile_ca.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava.rvmat",
			"\a3\characters_f\heads\glasses\data\lowprofile.rvmat"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava_blk_CO.paa",
			"\a3\characters_f\heads\glasses\data\lowprofile_black_ca.paa"
		};
		mass=8;
		identityTypes[]={};
	};
	class G_Balaclava_3hole_lowprofile_grn_ru: G_Balaclava_3hole_lowprofile_blk_ru
	{
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_CFGGLASSES_G_Balaclava_lowprofile0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_3hole_balaclava_grn_CO.paa",
			"\a3\characters_f\heads\glasses\data\lowprofile_black_ca.paa"
		};
	};
	class AX_G_Balaclava_ribbed_blk_F: G_Balaclava_TI_blk_F
	{
		author="$STR_A3_GRFU_Grave";
		displayName="$STR_A3_GRFU_G_Balaclava_ribbed_blk_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Balaclava_ribbed_blk_CO.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Ribbed_balaclava.rvmat"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_RUS_default",
			25,
			"G_RUS_SF",
			25,
			"G_RUSSIA_default",
			50,
			"G_RUSSIA_sf",
			50
		};
		mass=6;
	};
	class AX_G_Balaclava_ribbed_grn_F: AX_G_Balaclava_ribbed_blk_F
	{
		author="$STR_A3_GRFU_Grave";
		displayName="$STR_A3_GRFU_G_Balaclava_ribbed_grn_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Balaclava_ribbed_grn_CO.paa"
		};
	};
	class AX_G_Balaclava_ribbed_G_blk_F: G_Balaclava_TI_G_blk_F
	{
		author="$STR_A3_GRFU_Grave";
		displayName="$STR_A3_GRFU_G_Balaclava_ribbed_G_blk_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Balaclava_ribbed_blk_CO.paa",
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Ribbed_balaclava.rvmat"
		};
		identityTypes[]={};
		mass=6;
	};
	class AX_G_Balaclava_ribbed_G_grn_F: AX_G_Balaclava_ribbed_G_blk_F
	{
		author="$STR_A3_GRFU_Grave";
		displayName="$STR_A3_GRFU_G_Balaclava_ribbed_G_grn_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Balaclava_ribbed_grn_CO.paa",
			"\ax_grounded_futura\characters_f_russia\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
	};
	class G_Bandanna_blk_ru: G_Balaclava_blk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_RUSSIA_default",
			50,
			"G_RUSSIA_sf",
			50
		};
	};
	class G_Bandanna_oli_ru: G_Bandanna_oli
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_RUSSIA_default",
			50,
			"G_RUSSIA_sf",
			50
		};
	};
	class G_Bandanna_khk_ru: G_Bandanna_khk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_RUSSIA_default",
			50,
			"G_RUSSIA_sf",
			50
		};
	};
	class G_Bandanna_beast_ru: G_Bandanna_beast
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_RUSSIA_default",
			25,
			"G_RUSSIA_sf",
			25
		};
	};