    class AX_U_I_CombatUniform_jacket_tan_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_tan_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_tan_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_I_CombatUniform_jacket_grn_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_grn_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_grn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_I_CombatUniform_jacket_gloves_tan_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_gloves_tan_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_gloves_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_gloves_tan_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_I_CombatUniform_jacket_gloves_grn_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_gloves_grn_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_gloves_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_gloves_grn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_I_CombatUniform_jacket_02_tan_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_02_tan_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_02_tan_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_I_CombatUniform_jacket_02_grn_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_02_grn_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_02_grn_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_I_CombatUniform_jacket_02_gloves_tan_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_02_gloves_tan_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_02_gloves_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_02_gloves_tan_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_I_CombatUniform_jacket_02_gloves_grn_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_I_CombatUniform_jacket_02_gloves_grn_F0";
		picture="\ax_grounded_futura\characters_f_altis\uniforms\data\UI\icon_U_I_CombatUniform_jacket_02_gloves_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\uniforms\data\Officer_Insignia_Tan_aaf_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_soldier_U_I_CombatUniform_jacket_02_gloves_grn_F";
			containerClass="Supply40";
			mass=40;
		};
	};