    class B_Soldier_lite_F: B_Soldier_03_f
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_lite_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
	};
    class B_Soldier_GL_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_GL_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_mcam_F";
        linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"V_PlateCarrierGL_mtp",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"V_PlateCarrierGL_mtp",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_AR_F: B_Soldier_02_f
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_AR_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_Soldier_SL_F: B_Soldier_03_f
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_SL_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"AddGis_V_AssaultCarrier_TL_mcam_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"AddGis_V_AssaultCarrier_TL_mcam_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_Soldier_TL_F: B_Soldier_03_f
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_TL_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"AddGis_V_AssaultCarrier_TL_mcam_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"AddGis_V_AssaultCarrier_TL_mcam_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_M_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_M_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_LAT_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_LAT_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		backpack="AX_B_AssaultPack_khk_LAT";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_medic_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_medic_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_mcam_F";
		backpack="AX_B_AssaultPack_khk_Medic";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"V_PlateCarrierSpec_mtp",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"V_PlateCarrierSpec_mtp",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_repair_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_repair_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		backpack="AX_B_AssaultPack_khk_Repair";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_exp_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_exp_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_mcam_F";
		backpack="AX_B_Kitbag_khk_Exp";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"V_PlateCarrierGL_mtp",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_mcam",
			"V_PlateCarrierGL_mtp",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_Soldier_A_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_A_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_AT_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_AT_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_AA_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_AA_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_engineer_F: B_Soldier_03_f
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_engineer_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_mcam_F";
		//backpack="";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class B_Helipilot_F: B_Soldier_04_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Helipilot_F.jpg";
		uniformClass="U_B_HeliPilotCoveralls_MTP_RF";
		linkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_helicrew_F: B_Helipilot_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_helicrew_F.jpg";
		uniformClass="U_B_HeliPilotCoveralls_MTP_RF";
		linkedItems[]=
		{
			"H_CrewHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_CrewHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_crew_F: B_Soldier_03_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_crew_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"H_HelmetCrew_B",
			"AddGis_V_AssaultCarrier_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_B",
			"AddGis_V_AssaultCarrier_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_Deck_Crew_F: B_Helipilot_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Deck_Crew_F.jpg";
		uniformClass="U_B_HeliPilotCoveralls";
	};
    class B_officer_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_officer_F.jpg";
		uniformClass="JAM_U_B_IHWCU_bloused_mcam_F";
	};
    class B_soldier_PG_F: B_Soldier_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_PG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_UAV_F: B_Soldier_03_f
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_UAV_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
    };
    class B_Survivor_F: B_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Survivor_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
	};
    class B_Soldier_unarmed_F: B_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_unarmed_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class B_soldier_AAR_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_AAR_F.jpg";
		backpack="AX_B_Kitbag_khk_AAR";
        linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_AAT_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_AAT_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";   
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_AAA_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_AAA_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";   
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"AddGis_H_HelmetB_Cover_mcam",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"AddGis_H_HelmetB_Cover_mcam",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_support_MG_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_support_MG_F.jpg";
    };
    class B_support_GMG_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_support_GMG_F.jpg";
    };
    class B_support_Mort_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_support_Mort_F.jpg";
    };
    class B_support_AMG_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_support_AMG_F.jpg";
    };
    class B_support_AMort_F: B_Soldier_support_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_support_AMort_F.jpg";
    };
    class B_Sharpshooter_F: B_Soldier_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Sharpshooter_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		weapons[]=
		{
			"AX_srifle_DMR_03_tan_v2_AMS_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_03_tan_v2_AMS_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_HeavyGunner_F: B_Soldier_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_HeavyGunner_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_soldier_mine_F: B_soldier_exp_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_mine_F.jpg";
    };
    class B_soldier_LAT2_F: B_Soldier_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_LAT2_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		backpack="AX_B_AssaultPack_khk_LAT2";
		weapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"launch_MRAWS_green_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"launch_MRAWS_green_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_Soldier_CQ_F: B_Soldier_base_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_CQ_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_Soldier_MG_F: B_Soldier_03_f
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_MG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_mcam_F";
		weapons[]=
		{
			"AX_LMG_Mk200_plain_v2_nogrip_RCO_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_plain_v2_nogrip_RCO_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_Soldier_CBRN_F: B_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Soldier_CBRN_F.jpg";
        linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"NVGoggles"
		};
	};
    class B_RadioOperator_F: B_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_RadioOperator_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_mcam_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_mcam",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
//
	class B_soldier_UAV_06_F: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_UAV_F.jpg";
	};
	class B_soldier_UAV_06_medical_F: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_UAV_F.jpg";
	};
	class B_soldier_UGV_02_Science_F: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_UAV_F.jpg";
	};
	class B_soldier_UGV_02_Demining_F: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_UAV_F.jpg";
	};
	class B_soldier_UAV_lxWS: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_soldier_UAV_F.jpg";
		weapons[] = 
		{
			"arifle_MXC_ACO_pointer_F", 
			"hgun_P07_F", 
			"Throw", 
			"Put"
		};
		respawnWeapons[] = 
		{
			"arifle_MXC_ACO_pointer_F", 
			"hgun_P07_F", 
			"Throw", 
			"Put"
		};
		magazines[] = 
		{
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"16Rnd_9x21_Mag", 
			"16Rnd_9x21_Mag", 
			"16Rnd_9x21_Mag", 
			"SmokeShellGreen", 
			"SmokeShellBlue", 
			"SmokeShellOrange", 
			"Chemlight_green", 
			"Chemlight_green"
		};
		respawnMagazines[] = 
		{
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"30Rnd_65x39_caseless_mag", 
			"16Rnd_9x21_Mag", 
			"16Rnd_9x21_Mag", 
			"16Rnd_9x21_Mag", 
			"SmokeShellGreen", 
			"SmokeShellBlue", 
			"SmokeShellOrange", 
			"Chemlight_green", 
			"Chemlight_green"
		};
	};
	class B_support_CMort_RF: B_support_AMort_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_support_AMort_F.jpg";
	};
