    class B_D_Soldier_A_lxWS: B_Soldier_A_F
    {
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Soldier_A_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_AAR_lxWS: B_soldier_AAR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_AAR_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_support_AMG_lxWS: B_support_AMG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_support_AMG_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_support_AMort_lxWS: B_support_AMort_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_support_AMort_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_AAA_lxWS: B_soldier_AAA_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_AAA_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class B_D_soldier_AAT_lxWS: B_soldier_AAT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_AAT_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_AR_lxWS: B_soldier_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_AR_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_MG_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_MG_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_medic_lxWS: B_medic_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_medic_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_lxWS_PlateCarrierSpec_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_lxWS_PlateCarrierSpec_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_crew_lxWS: B_crew_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_crew_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"H_HelmetCrew_B",
			"AddGis_V_AssaultCarrier_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_B",
			"AddGis_V_AssaultCarrier_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class Aegis_B_D_HeliCrew_F: B_helicrew_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_HeliCrew_F.jpg";
        uniformClass="AddGis_U_B_HeliPilotCoveralls_desert";
		linkedItems[]=
		{
			"AX_V_TacVest_blk",
			"H_CrewHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_TacVest_blk",
			"H_CrewHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_HeliPilot_lxWS: B_Helipilot_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_HeliPilot_lxWS.jpg";
        uniformClass="AddGis_U_B_HeliPilotCoveralls_desert";
		linkedItems[]=
		{
			"AX_V_TacVest_blk",
			"H_PilotHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_TacVest_blk",
			"H_PilotHelmetHeli_B",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
    class B_D_engineer_lxWS: B_engineer_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_engineer_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_exp_lxWS: B_soldier_exp_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_exp_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"V_lxWS_PlateCarrierGL_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"V_lxWS_PlateCarrierGL_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_Soldier_GL_lxWS: B_Soldier_GL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Soldier_GL_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"V_lxWS_PlateCarrierGL_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"V_lxWS_PlateCarrierGL_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_support_GMG_lxWS: B_support_GMG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_support_GMG_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_support_MG_lxWS: B_support_MG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_support_MG_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_support_Mort_lxWS: B_support_Mort_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_support_Mort_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_M_lxWS: B_soldier_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_M_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_mine_lxWS: B_soldier_mine_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_mine_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"V_lxWS_PlateCarrierGL_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"V_lxWS_PlateCarrierGL_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_AA_lxWS: B_soldier_AA_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_AA_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_AT_lxWS: B_soldier_AT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_AT_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_officer_lxWS: B_officer_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_officer_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_bloused_desert_F";
		linkedItems[]=
		{
			"lxWS_H_MilCap_desert",
			"V_Rangemaster_belt_cbr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_MilCap_desert",
			"V_Rangemaster_belt_cbr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class B_D_soldier_PG_lxWS: B_soldier_PG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_PG_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_repair_lxWS: B_soldier_repair_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_repair_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_Soldier_lxWS: B_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Soldier_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_LAT_lxWS: B_soldier_LAT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_LAT_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_LAT2_lxWS: B_soldier_LAT2_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_LAT2_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_Soldier_lite_lxWS: B_Soldier_lite_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Soldier_lite_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"lxWS_H_MilCap_desert",
			"V_BandollierB_cbr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_MilCap_desert",
			"V_BandollierB_cbr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class B_D_Survivor_lxWS: B_Survivor_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Survivor_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
	};
	class B_D_Soldier_unarmed_lxWS: B_Soldier_unarmed_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Soldier_unarmed_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_Soldier_SL_lxWS: B_Soldier_SL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Soldier_SL_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_TL_desert_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_TL_desert_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_Soldier_TL_lxWS: B_Soldier_TL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_Soldier_TL_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"AddGis_V_AssaultCarrier_TL_desert_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_desert",
			"AddGis_V_AssaultCarrier_TL_desert_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class B_D_soldier_UAV01_lxWS: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_UAV01_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
    };
    class B_D_soldier_UAV02_lxWS: B_soldier_UAV_lxWS
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_soldier_UAV02_lxWS.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
    };
    class Aegis_B_D_HeavyGunner_F: B_HeavyGunner_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_HeavyGunner_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_MG_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_MG_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class Aegis_B_D_RadioOperator_F: B_RadioOperator_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_RadioOperator_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class Aegis_B_D_Sharpshooter_F: B_Sharpshooter_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_Sharpshooter_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		weapons[]=
		{
			"srifle_DMR_03_tan_AMS_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_03_tan_AMS_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class Aegis_B_D_Soldier_CQ_F: B_Soldier_CQ_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_Soldier_CQ_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class Aegis_B_D_Soldier_MG_F: B_Soldier_MG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_Soldier_MG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_desert_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_MG_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_desert",
			"AddGis_V_AssaultCarrier_MG_desert_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };

	class Aegis_B_D_support_CMort_RF: B_D_support_AMort_lxWS
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_support_AMort_lxWS.jpg";
	};