	class B_W_Soldier_A_F: B_Soldier_A_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_A_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_AAR_F: B_soldier_AAR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_AAR_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Support_AMG_F: B_support_AMG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Support_AMG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Support_AMort_F: B_support_AMort_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Support_AMort_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_AAA_F: B_soldier_AAA_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_AAA_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_AAT_F: B_soldier_AAT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_AAT_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_AR_F: B_soldier_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_AR_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_MG_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_MG_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Medic_F: B_medic_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Medic_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_wdl",
			"V_PlateCarrierSpec_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_wdl",
			"V_PlateCarrierSpec_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Crew_F: B_crew_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Crew_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"H_HelmetCrew_B_oli_F",
			"AddGis_V_AssaultCarrier_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_B_oli_F",
			"AddGis_V_AssaultCarrier_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Engineer_F: B_engineer_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Engineer_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_Exp_F: B_soldier_exp_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_Exp_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_PlateCarrierGL_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_PlateCarrierGL_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_soldier_mine_F: B_W_Soldier_Exp_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_soldier_mine_F.jpg";
	};
	class B_W_Soldier_GL_F: B_Soldier_GL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_GL_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_PlateCarrierGL_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_PlateCarrierGL_wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Support_GMG_F: B_support_GMG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Support_GMG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Support_MG_F: B_support_MG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Support_MG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Support_Mort_F: B_support_Mort_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Support_Mort_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_ChestrigF_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Helicrew_F: B_helicrew_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Helicrew_F.jpg";
		uniformClass="AddGis_U_B_HeliPilotCoveralls_wdl";
		linkedItems[]=
		{
			"H_CrewHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_CrewHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Helipilot_F: B_Helipilot_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Helipilot_F.jpg";
		uniformClass="AddGis_U_B_HeliPilotCoveralls_wdl";
		linkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_B",
			"AX_V_TacVest_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_soldier_M_F: B_soldier_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_soldier_M_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class B_W_Soldier_AA_F: B_soldier_AA_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_AA_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class B_W_Soldier_AT_F: B_soldier_AT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_AT_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class B_W_Officer_F: B_officer_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Officer_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
	};
	class B_W_Soldier_Repair_F: B_soldier_repair_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_Repair_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_F: B_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class B_W_Soldier_LAT_F: B_soldier_LAT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_LAT_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_LAT2_F: B_soldier_LAT2_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_LAT2_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_SL_F: B_Soldier_SL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_SL_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_wdl",
			"AddGis_V_AssaultCarrier_TL_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_wdl",
			"AddGis_V_AssaultCarrier_TL_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_TL_F: B_Soldier_TL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_TL_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_wdl",
			"AddGis_V_AssaultCarrier_TL_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetSpecB_Cover_wdl",
			"AddGis_V_AssaultCarrier_TL_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_CBRN_F: B_W_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_CBRN_F.jpg";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_AirPurifyingRespirator_01_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_RadioOperator_F: B_W_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_RadioOperator_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_UAV_F: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_UAV_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"B_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"B_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_soldier_UGV_02_Science_F: B_W_Soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_UAV_F.jpg";
	};
	class B_W_soldier_UGV_02_Demining_F: B_W_Soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_UAV_F.jpg";
	};
	class B_W_soldier_UAV_02_lxWS_F: B_W_Soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_UAV_F.jpg";
	};
	class B_W_soldier_UAV_06_F: B_W_Soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_UAV_F.jpg";
	};
	class B_W_soldier_UAV_06_medical_F: B_W_Soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_UAV_F.jpg";
	};
	class B_W_Survivor_F: B_W_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Survivor_F.jpg";
	};
	class B_W_Soldier_unarmed_F: B_W_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_unarmed_F.jpg";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class B_W_Soldier_PG_F: B_soldier_PG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_PG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_Lite_F: B_Soldier_lite_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_Lite_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_BandollierB_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"V_BandollierB_rgr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class B_W_Soldier_CQ_F: B_Soldier_CQ_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_CQ_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Soldier_MG_F: B_Soldier_MG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Soldier_MG_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_shortsleeve_wdl_F";
		weapons[]=
		{
			"AX_LMG_Mk200_black_nogrip_RCO_LP_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_black_nogrip_RCO_LP_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_MG_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_MG_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Sharpshooter_F: B_Sharpshooter_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Sharpshooter_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_Lite_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_HeavyGunner_F: B_HeavyGunner_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_HeavyGunner_F.jpg";
		uniformClass="JAM_U_B_IHWCU_combat_tshirt_wdl_F";
		linkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_MG_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"AddGis_H_HelmetB_Cover_wdl",
			"AddGis_V_AssaultCarrier_MG_wdl_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};

	class Aegis_B_W_support_CMort_RF: B_W_Support_AMort_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Support_AMort_F.jpg";
	};
