    class Atlas_B_T_Soldier_JSOC_base: Atlas_B_Soldier_JSOC_base
	{
    };
    class Atlas_B_T_JSOC_AR_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_AR_F.jpg";
		uniformClass="U_I_C_Soldier_Bandit_4_F";
		linkedItems[]=
		{
			"H_Headset_Tactical_grn",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Headset_Tactical_grn",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_Exp_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_Exp_F.jpg";
		uniformClass="U_I_C_Soldier_Bandit_3_F";
		backpack="Atlas_B_T_AssaultPack_JSOC_Exp_F";
		linkedItems[]=
		{
			"H_Cap_oli",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Bandanna_beast",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_oli",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Bandanna_beast",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_GL_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_GL_F.jpg";
		uniformClass="U_I_C_Soldier_Para_5_F";
		linkedItems[]=
		{
			"H_Helmet_Skate",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Bandanna_Skull1",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Helmet_Skate",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Bandanna_Skull1",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_JTAC_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_JTAC_F.jpg";
		uniformClass="Atlas_U_C_Uniform_01_tshirt_white_F";
		backpack="B_RadioBag_01_tropic_F";
        weapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		linkedItems[]=
		{
			"H_WirelessEarpiece_F",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Squares",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_WirelessEarpiece_F",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Squares",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_M_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_M_F.jpg";
		uniformClass="U_I_C_Soldier_Para_4_F";
		linkedItems[]=
		{
			"Aegis_H_Milcap_nohs_grn_F",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"Aegis_H_Milcap_nohs_grn_F",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_Medic_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_Medic_F.jpg";
		uniformClass="AX_U_C_Man_casual_4_F";
		backpack="Atlas_B_T_AssaultPack_JSOC_Medic_F";
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_WirelessEarpiece_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_WirelessEarpiece_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_F.jpg";
		uniformClass="U_C_Poloshirt_blue";
        weapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"H_Booniehat_mgrn",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_mgrn",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_LAT_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_LAT_F.jpg";
		uniformClass="U_C_Uniform_Scientist_02_F";
		backpack="Atlas_B_T_AssaultPack_JSOC_LAT_F";
		linkedItems[]=
		{
			"H_Beret_blk",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Sport_Blackred",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Beret_blk",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Sport_Blackred",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_TL_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_TL_F.jpg";
		uniformClass="U_I_C_Soldier_Bandit_5_F";
        weapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"H_Cap_headphones",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Aviator",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_headphones",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Aviator",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_SL_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_SL_F.jpg";
		uniformClass="U_I_C_Soldier_Bandit_1_F";
		linkedItems[]=
		{
            "H_Bandanna_khk_hs",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
            "H_Bandanna_khk_hs",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_Sharpshooter_F: Atlas_B_T_JSOC_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_Sharpshooter_F.jpg";
		uniformClass="U_C_Poloshirt_tricolour";
		linkedItems[]=
		{
			"H_Hat_Safari_olive_F",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Hat_Safari_olive_F",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_UAV_F: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_UAV_F.jpg";
		uniformClass="U_C_Poloshirt_burgundy";
		backpack="B_UAV_01_backpack_F";
        weapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_khk_HAMR_IR_Snds_F",
			"hgun_P07_khk_snds_F",
			"Throw",
			"Put"
        };
		linkedItems[]=
		{
			"H_Headset_light",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Combat_Goggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Headset_light",
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Combat_Goggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_T_JSOC_UAV_lxWS: Atlas_B_T_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_T_JSOC_UAV_lxWS.jpg";
		uniformClass="Aegis_U_lxWS_ION_Casual_Hawaiian_2_F";
		backpack="B_UAV_02_backpack_lXWS";
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Lowprofile",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_tna_F",
			"G_Lowprofile",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
	};