	class Atlas_B_D_Soldier_JSOC_base: Atlas_B_Soldier_JSOC_base
    {
    };
    class Atlas_B_D_JSOC_AR_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_AR_F.jpg";
        uniformClass="AX_U_lxWS_C_Djella_03";
		linkedItems[]=
		{
			"H_Headset_tactical_khk",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Headset_tactical_khk",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_Exp_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_Exp_F.jpg";
		uniformClass="AX_U_lxWS_C_Djella_01";
		backpack="Atlas_B_D_AssaultPack_JSOC_Exp_F";
		linkedItems[]=
		{
			"lxWS_H_turban_04_sand",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Bandanna_tan",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_turban_04_sand",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Bandanna_tan",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_GL_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_GL_F.jpg";
		uniformClass="AX_U_lxWS_C_Djella_03";
		linkedItems[]=
		{
			"lxWS_H_turban_02_black",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_snd_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_turban_02_black",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_snd_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_JTAC_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_JTAC_F.jpg";
		uniformClass="U_lxWS_Djella_03_Green";
		backpack="Aegis_B_RadioBag_01_des_lxWS";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		linkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_snd_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_snd_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_M_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_M_F.jpg";
        uniformClass="AX_U_lxWS_Tak_02_A";
		linkedItems[]=
		{
			"lxWS_H_turban_03_green",
			"V_BandollierB_cbr",
			"G_Combat_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_turban_03_green",
			"V_BandollierB_cbr",
			"G_Combat_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_Medic_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_Medic_F.jpg";
        uniformClass="U_lxWS_Djella_02_Brown";
		backpack="Atlas_B_D_AssaultPack_JSOC_Medic_F";
		linkedItems[]=
		{
			"lxWS_H_turban_01_sand",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_snd_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_turban_01_sand",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Balaclava_snd_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_F.jpg";
		uniformClass="U_lxWS_Djella_02_Grey";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"H_HelmetB_light_sand",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Aviator",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetB_light_sand",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Aviator",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_LAT_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_LAT_F.jpg";
        uniformClass="AX_U_lxWS_C_Djella_03";
		backpack="Atlas_B_D_AssaultPack_JSOC_LAT_F";
		linkedItems[]=
		{
			"H_ShemagOpen_tan",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Lowprofile",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_ShemagOpen_tan",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Lowprofile",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_TL_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_TL_F.jpg";
        uniformClass="AX_U_lxWS_C_Djella_03";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"H_Shemag_olive_hs",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Shemag_olive_hs",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_SL_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_SL_F.jpg";
        uniformClass="U_lxWS_Djella_02_Sand";
		linkedItems[]=
		{
			"H_Hat_Pakol_brn_F",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Shemag_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Hat_Pakol_brn_F",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Shemag_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_Sharpshooter_F: Atlas_B_D_JSOC_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_Sharpshooter_F.jpg";
		uniformClass="U_I_C_Soldier_Bandit_3_F";
		linkedItems[]=
		{
			"H_Watchcap_khk_hs",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Bandanna_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_khk_hs",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Bandanna_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_UAV_F: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_UAV_F.jpg";
        uniformClass="AX_U_lxWS_Tak_03_A";
		backpack="B_UAV_01_backpack_F";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"H_Booniehat_khk_hs",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Squares",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_khk_hs",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Squares",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_D_JSOC_UAV_lxWS: Atlas_B_D_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_D_JSOC_UAV_lxWS.jpg";
		uniformClass="AX_U_lxWS_Djella_02_Brown";
		backpack="B_UAV_02_backpack_lXWS";
		linkedItems[]=
		{
			"H_Cap_headphones_tan",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_headphones_tan",
			"AddGis_V_AssaultCarrier_Lite_desert_F",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
	};