    class Atlas_B_W_Soldier_JSOC_base: Atlas_B_Soldier_JSOC_base
	{
	};
    class Atlas_B_W_JSOC_AR_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_AR_F.jpg";
		uniformClass="U_I_L_Uniform_01_tshirt_sport_F";
		linkedItems[]=
		{
			"H_Headset_tactical",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Headset_tactical",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_Exp_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_Exp_F.jpg";
		uniformClass="U_I_L_Uniform_01_tshirt_black_F";
		backpack="Atlas_B_W_AssaultPack_JSOC_Exp_F";
		linkedItems[]=
		{
			"Aegis_H_MilCap_nohs_gry_F",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Lowprofile",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"Aegis_H_MilCap_nohs_gry_F",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Lowprofile",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_GL_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_GL_F.jpg";
		uniformClass="U_I_L_Uniform_01_tshirt_skull_F";
		linkedItems[]=
		{
			"H_Watchcap_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Spectacles_Tinted",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Spectacles_Tinted",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_JTAC_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_JTAC_F.jpg";
		uniformClass="U_C_Uniform_Scientist_02_formal_F";
		backpack="B_RadioBag_01_wdl_F";
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		linkedItems[]=
		{
			"H_Cap_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shemag_shades",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shemag_shades",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_M_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_M_F.jpg";
		uniformClass="U_C_E_LooterJacket_01_F";
		linkedItems[]=
		{
			"H_Booniehat_oli",
			"V_BandollierB_oli",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_oli",
			"V_BandollierB_oli",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_Medic_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_Medic_F.jpg";
		uniformClass="U_C_ArtTShirt_01_v4_F";
		backpack="Atlas_B_W_AssaultPack_JSOC_Medic_F";
		linkedItems[]=
		{
			"H_Watchcap_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_F.jpg";
		uniformClass="U_Jayholder";
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"H_HelmetB_light_green",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Combat_Goggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetB_light_green",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Combat_Goggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_LAT_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_LAT_F.jpg";
		uniformClass="U_C_ArtTShirt_01_v5_F";
		backpack="Atlas_B_W_AssaultPack_JSOC_LAT_F";
		linkedItems[]=
		{
			"H_HeadSet_black_F",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_HeadSet_black_F",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_TL_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_TL_F.jpg";
		uniformClass="U_B_ION_Uniform_01_poloshirt_blue_F";
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"H_Beret_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Aviator",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Beret_blk",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Aviator",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_SL_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_SL_F.jpg";
		uniformClass="U_C_Uniform_Farmer_01_F";
		linkedItems[]=
		{
			"H_WirelessEarpiece_F",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_WirelessEarpiece_F",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Shemag_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_Sharpshooter_F: Atlas_B_W_JSOC_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_Sharpshooter_F.jpg";
		uniformClass="U_I_L_Uniform_01_tshirt_olive_F";
		linkedItems[]=
		{
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Balaclava_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Balaclava_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_UAV_F: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_UAV_F.jpg";
		uniformClass="U_C_Journalist";
		backpack="B_UAV_01_backpack_F";
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"h_pasgt_basic_olive_f",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Bandanna_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"h_pasgt_basic_olive_f",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Bandanna_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
	};
	class Atlas_B_W_JSOC_UAV_lxWS: Atlas_B_W_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_W_JSOC_UAV_lxWS.jpg";
		uniformClass="U_lxWS_ION_Casual5";
		backpack="B_UAV_02_backpack_lXWS";
		linkedItems[]=
		{
			"lxWS_H_Bandanna_blk_hs",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Squares_Tinted",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_Bandanna_blk_hs",
            "AddGis_V_AssaultCarrier_Lite_wdl_F",
			"G_Squares_Tinted",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_grn_Hidden"
		};
	};