    class Atlas_B_JSOC_AR_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_AR_F.jpg";
		uniformClass="U_BG_Guerilla2_3";
		linkedItems[]=
		{
			"H_Headset_tactical_khk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Shemag_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Headset_tactical_khk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Shemag_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_Exp_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_Exp_F.jpg";
		uniformClass="U_BG_Guerilla2_2";
		backpack="Atlas_B_AssaultPack_JSOC_Exp_F";
		linkedItems[]=
		{
			"H_Watchcap_blk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_blk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_GL_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_GL_F.jpg";
		uniformClass="U_C_ArtTshirt_01_v5_F";
		linkedItems[]=
		{
			"H_ShemagOpen_tan_hs",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_lowprofile",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_ShemagOpen_tan_hs",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_lowprofile",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_JTAC_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_JTAC_F.jpg";
		uniformClass="U_I_L_Uniform_01_tshirt_sport_F";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		linkedItems[]=
		{
			"H_Shemag_olive_hs",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Shemag_olive_hs",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_M_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_M_F.jpg";
		uniformClass="U_BG_Guerilla3_1";
		linkedItems[]=
		{
			"H_Hat_Safari_sand_F",
			"V_BandollierB_rgr",
			"G_Headset_light",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Hat_Safari_sand_F",
			"V_BandollierB_rgr",
			"G_Headset_light",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_Medic_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_Medic_F.jpg";
		uniformClass="U_BG_Guerrilla_6_1";
		backpack="Atlas_B_AssaultPack_JSOC_Medic_F";
		linkedItems[]=
		{
			"H_Headset_light",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_shades",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Headset_light",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_shades",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_F.jpg";
		uniformClass="AX_U_C_Man_casual_9_F";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"H_HelmetB_light",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Spectacles_Tinted",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetB_light",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Spectacles_Tinted",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_LAT_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_LAT_F.jpg";
		uniformClass="U_BG_Guerilla2_2";
		linkedItems[]=
		{
			"H_Cap_headphones",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_headphones",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_TL_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_TL_F.jpg";
		uniformClass="U_C_ArtTshirt_01_v1_F";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"H_Booniehat_oli",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_oli",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_SL_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_SL_F.jpg";
		uniformClass="U_C_ArtTShirt_01_v6_F";
		linkedItems[]=
		{
			"H_Cap_red",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Shemag_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_red",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Shemag_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_Sharpshooter_F: Atlas_B_JSOC_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_Sharpshooter_F.jpg";
		uniformClass="U_lxWS_ION_Casual5";
		linkedItems[]=
		{
			"H_Beret_blk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_hs_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Beret_blk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Bandanna_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_hs_Hidden"
		};
	};
	class Atlas_B_JSOC_UAV_F: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_UAV_F.jpg";
		uniformClass="U_C_Journalist";
		weapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_HAMR_IR_Snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"H_Bandanna_khk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Sport_Blackred",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Bandanna_khk",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Sport_Blackred",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
	};
	class Atlas_B_JSOC_UAV_lxWS: Atlas_B_Soldier_JSOC_base
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Atlas_B_JSOC_UAV_lxWS.jpg";
		uniformClass="U_C_Mechanic_01_F";
		linkedItems[]=
		{
			"H_Hat_tan",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
		respawnLinkedItems[]=
		{
			"H_Hat_tan",
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"G_Aviator",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"AX_NVGoggles_brn_Hidden"
		};
	};