	class B_Patrol_Soldier_TL_F: B_Soldier_TL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Soldier_TL_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		backpack="B_AssaultPack_rgr";
		weapons[]=
		{
			"arifle_SPAR_01_GL_snd_RCO_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_SPAR_01_GL_snd_RCO_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellBlue"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellBlue"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetB_light_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetB_light_desert",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
	};
	class B_Patrol_Soldier_UAV_F: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Soldier_UAV_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_03_mcam_F";
		backpack="B_UAV_01_backpack_F";
		weapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_Cap_tan_specops_us_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_Cap_tan_specops_us_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
	};
	class B_Patrol_Soldier_M_F: B_soldier_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Soldier_M_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		backpack="B_TacticalPack_rgr";
		weapons[]=
		{
			"AX_arifle_SPAR_03_snd_v2_MOS_Pointer_Snds_Bipod_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SPAR_03_snd_v2_MOS_Pointer_Snds_Bipod_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_Cap_tan_specops_us_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_Cap_tan_specops_us_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_Patrol_Medic_F: B_medic_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Medic_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		backpack="AX_B_AssaultPackSpec_mcamo_patrol_Medic_F";
		weapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_MilCap_mcamo",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_MilCap_mcamo",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_Patrol_Soldier_AR_F: B_soldier_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Soldier_AR_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_03_mcam_F";
		backpack="B_AssaultPackSpec_mcamo";
		weapons[]=
		{
			"arifle_SPAR_02_snd_RCO_Pointer_Snds_Bipod_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_SPAR_02_snd_RCO_Pointer_Snds_Bipod_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"150Rnd_556x45_Drum_Mag_F",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier2_rgr",
			"H_HelmetSpecB_light_snakeskin",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier2_rgr",
			"H_HelmetSpecB_light_snakeskin",
			"G_Bandanna_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_Patrol_Soldier_MG_F: B_soldier_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Soldier_MG_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		backpack="B_Kitbag_mcamo";
		weapons[]=
		{
			"AX_LMG_Mk200_plain_v3_Holo_LP_S_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_plain_v3_Holo_LP_S_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box_Tracer",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box_Tracer",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetSpecB_light_grass",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_goggles_Hidden"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetSpecB_light_grass",
			"G_Bandanna_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_goggles_Hidden"
		};
	};
	class B_Patrol_HeavyGunner_F: B_HeavyGunner_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_HeavyGunner_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		backpack="B_Carryall_mcamo";
		weapons[]=
		{
			"AX_MMG_02_sand_RCO_LP_snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"AX_MMG_02_sand_RCO_LP_snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"130Rnd_338_Mag",
			"130Rnd_338_Mag",
			"130Rnd_338_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"130Rnd_338_Mag",
			"130Rnd_338_Mag",
			"130Rnd_338_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetSpecB_light_snakeskin",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetSpecB_light_snakeskin",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_Patrol_Soldier_A_F: B_Soldier_A_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Soldier_A_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		backpack="AX_B_Carryall_mcamo_patrol_Ammo_F";
		weapons[]=
		{
			"arifle_SPAR_01_snd_RCO_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_SPAR_01_snd_RCO_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_Booniehat_mgrn_hs",
			"G_Bandanna_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_Booniehat_mgrn_hs",
			"G_Bandanna_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_Patrol_Soldier_AT_F: B_soldier_AT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Soldier_AT_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		backpack="AX_B_Kitbag_rgr_AT_F";
		weapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"launch_B_Titan_short_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"launch_B_Titan_short_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"Titan_AP",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"Titan_AP",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetB_light_snakeskin",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetB_light_snakeskin",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_Patrol_Engineer_F: B_engineer_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_Patrol_Engineer_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Infiltrators";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		backpack="AX_B_Kitbag_mcamo_Exp_F";
		weapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_SPAR_01_snd_Holo_Pointer_Snds_F",
			"hgun_Pistol_heavy_01_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"30Rnd_556x45_Stanag_red",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetSpecB_paint2",
			"G_Bandanna_tan",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_gogglescvr_Hidden"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrier1_rgr",
			"H_HelmetSpecB_paint2",
			"G_Bandanna_tan",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_NVGoggles_brn_gogglescvr_Hidden"
		};
	};