    class B_QRF_Soldier_AR_RF: B_soldier_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_Soldier_AR_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		weapons[]=
		{
			"arifle_MX_SW_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_SW_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_MG_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_QRF_medic_RF: B_medic_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_medic_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		backpack="B_AssaultPack_rgr_Medic";
		weapons[]=
		{
			"arifle_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_QRF_Soldier_GL_RF: B_Soldier_GL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_Soldier_GL_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		weapons[]=
		{
			"arifle_MX_GL_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_QRF_Soldier_RF: B_Soldier_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_Soldier_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		weapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_QRF_soldier_LAT2_RF: B_soldier_LAT2_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_soldier_LAT2_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		weapons[]=
		{
			"arifle_MXC_Holo_pointer_F",
			"launch_MRAWS_olive_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Holo_pointer_F",
			"launch_MRAWS_olive_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MRAWS_HEAT_F",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MRAWS_HEAT_F",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"NVGoggles",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class B_QRF_soldier_LAT_RF: B_QRF_soldier_LAT2_RF
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_soldier_LAT_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		displayName="$STR_B_soldier_LAT_F0";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		weapons[]=
		{
			"arifle_MXC_Holo_pointer_F",
			"launch_NLAW_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Holo_pointer_F",
			"launch_NLAW_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_QRF_Sharpshooter_RF: B_Sharpshooter_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_Sharpshooter_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		weapons[]=
		{
			"AX_srifle_DMR_03_blksnd_AMS_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_03_blksnd_AMS_LP_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"HandGrenade",
			"HandGrenade"
		};
        linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class B_QRF_Soldier_SL_RF: B_Soldier_SL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_Soldier_SL_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		weapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_TL_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_TL_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_QRF_soldier_UAV_RF: B_soldier_UAV_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_QRF_soldier_UAV_RF.jpg";
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		weapons[]=
		{
			"arifle_MX_GL_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_shell_RF",
			"1Rnd_RC40_SmokeRed_shell_RF",
			"1Rnd_RC40_SmokeGreen_shell_RF",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_shell_RF",
			"1Rnd_RC40_SmokeRed_shell_RF",
			"1Rnd_RC40_SmokeGreen_shell_RF",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
	};

    class AX_B_QRF_Soldier_M_RF: B_soldier_M_F
	{
		scope=1;
		scopeArsenal=1;
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		weapons[]=
		{
			"arifle_MXM_Hamr_LP_BI_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXM_Hamr_LP_BI_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
        linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class AX_B_QRF_Soldier_A_RF: B_Soldier_A_F
	{
		scope=1;
		scopeArsenal=1;
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		weapons[]=
		{
			"arifle_MX_ACO_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_ACO_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class AX_B_QRF_Soldier_repair_RF: B_soldier_repair_F
	{
		scope=1;
		scopeArsenal=1;
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_mcam_F";
		weapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Holo_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_AssaultCarrier_Lite_mcam_F",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class AX_B_QRF_Soldier_TL_RF: B_Soldier_TL_F
	{
		scope=1;
		scopeArsenal=1;
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_02_mcam_F";
		weapons[]=
		{
			"arifle_MX_GL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_Hamr_pointer_F",
			"hgun_P07_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag_Tracer",
			"30Rnd_65x39_caseless_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		linkedItems[]=
		{
			"V_PlateCarrierGL_mtp",
			"H_HelmetB_camo_mcamo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_PlateCarrierGL_mtp",
			"H_HelmetB_camo_mcamo",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class AX_B_QRF_Support_CMort_RF: B_support_CMort_RF
	{
		scope=1;
		scopeArsenal=1;
		editorSubcategory="EdSubcat_Personnel_AirAssault";
		uniformClass="AddGis_U_UniformUS_03_mcam_F";
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"H_HelmetB_camo_mcamo",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
