    class B_D_recon_lxWS: B_recon_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_lxWS.jpg";
		uniformClass="AddGis_U_UniformUS_02_desert_F";
		weapons[]=
		{
			"arifle_MX_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Watchcap_khk",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_khk",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_D_recon_AR_lxWS: B_recon_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_AR_lxWS.jpg";
        uniformClass="AddGis_U_UniformUS_02_desert_F";
		weapons[]=
		{
			"arifle_MX_SW_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_SW_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"100Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_D_recon_LAT_lxWS: B_recon_LAT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_LAT_lxWS.jpg";
		uniformClass="AddGis_U_UniformUS_03_desert_F";
		weapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"launch_NLAW_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"launch_NLAW_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_D_recon_medic_lxWS: B_recon_medic_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_medic_lxWS.jpg";
		uniformClass="AddGis_U_UniformUS_03_desert_F";
        weapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_D_recon_TL_lxWS: B_recon_TL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_TL_lxWS.jpg";
		uniformClass="AddGis_U_UniformUS_02_desert_F";
        weapons[]=
		{
			"arifle_MX_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_RCO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_556x45_Stanag_Sand_Tracer_Red",
			"30Rnd_556x45_Stanag_Sand_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_556x45_Stanag_Sand_Tracer_Red",
			"30Rnd_556x45_Stanag_Sand_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"lxWS_H_MilCap_desert",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"lxWS_H_MilCap_desert",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_D_recon_M_lxWS: B_recon_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_M_lxWS.jpg";
		uniformClass="AddGis_U_UniformUS_desert_F";
        weapons[]=
		{
			"arifle_MXM_DMS_LP_BI_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MXM_DMS_LP_BI_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AX_H_Booniehat_desert_hs",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_H_Booniehat_desert_hs",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws_sniper"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws_sniper"
		};
	};
	class B_D_recon_JTAC_lxWS: B_recon_JTAC_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_JTAC_lxWS.jpg";
		uniformClass="AddGis_U_UniformUS_desert_F";
		backpack="Aegis_B_RadioBag_01_des_lxWS";
		weapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Watchcap_khk_hs",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_khk_hs",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_D_recon_exp_lxWS: B_recon_exp_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_D_recon_exp_lxWS.jpg";
		uniformClass="AddGis_U_UniformUS_03_desert_F";
        weapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AX_H_Booniehat_desert_hs",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_H_Booniehat_desert_hs",
			"V_ChestrigF_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class Aegis_B_D_Recon_GL_F: B_recon_GL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_Recon_GL_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_desert_F";
		weapons[]=
		{
			"arifle_MX_GL_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_ACO_pointer_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
        magazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"30Rnd_65x39_caseless_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
        linkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class Aegis_B_D_Recon_MG_F: B_recon_MG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_Recon_MG_F.jpg";
		uniformClass="AddGis_U_UniformUS_desert_F";
		weapons[]=
		{
			"AX_LMG_Mk200_plain_v2_nogrip_RCO_LP_S_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_plain_v2_nogrip_RCO_LP_S_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
        linkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"Aegis_V_PlateCarrier_RF_cbr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"Aegis_V_PlateCarrier_RF_cbr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class Aegis_B_D_Recon_CQ_F: B_recon_CQ_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_Recon_CQ_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_desert_F";
		linkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_sand",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class Aegis_B_D_Recon_Sharpshooter: B_Recon_Sharpshooter_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\Aegis_B_D_Recon_Sharpshooter.jpg";
		uniformClass="AddGis_U_UniformUS_03_desert_F";
		weapons[]=
		{
			"AX_srifle_DMR_03_tan_DMS_LP_BI_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_03_tan_DMS_LP_BI_snds_F",
			"hgun_P07_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
        linkedItems[]=
		{
			"AX_H_Booniehat_desert_hs",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_H_Booniehat_desert_hs",
			"V_Chestrig_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};