    class B_T_Recon_AR_F: B_recon_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_AR_F.jpg";
		uniformClass="AddGis_U_UniformUS_03_tna_F";
		weapons[]=
		{
			"arifle_MX_SW_khk_RCO_pointer_snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_SW_khk_RCO_pointer_snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"100Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_GL_F: B_recon_GL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_GL_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_tna_F";
		weapons[]=
		{
			"arifle_MX_GL_khk_RCO_pointer_snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_khk_RCO_pointer_snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_Exp_F: B_recon_exp_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_Exp_F.jpg";
        uniformClass="AddGis_U_UniformUS_03_tna_F";
        weapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Booniehat_tna_hs_F",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_tna_hs_F",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
    class B_T_Recon_JTAC_F: B_recon_JTAC_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_JTAC_F.jpg";
		uniformClass="AddGis_U_UniformUS_tna_F";
		backpack="B_RadioBag_01_tropic_F";
		weapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_M_F: B_recon_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_M_F.jpg";
		uniformClass="AddGis_U_UniformUS_tna_F";
		weapons[]=
		{
			"arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Booniehat_tna_hs_F",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_tna_hs_F",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_Medic_F: B_recon_medic_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_Medic_F.jpg";
		uniformClass="AddGis_U_UniformUS_03_tna_F";
		backpack="B_AssaultPack_rgr_BTReconMedic";
		weapons[]=
		{
			"arifle_MXC_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_F: B_recon_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_tna_F";
		weapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_LAT_F: B_recon_LAT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_LAT_F.jpg";
		uniformClass="AddGis_U_UniformUS_03_tna_F";
		backpack="B_AssaultPack_rgr_BTLAT_F";
		weapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"launch_NLAW_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"launch_NLAW_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_TL_F: B_recon_TL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_TL_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_tna_F";
		weapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_MilCap_tna_F",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_MilCap_tna_F",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_Sharpshooter_F: B_Recon_Sharpshooter_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_Sharpshooter_F.jpg";
		uniformclass="AddGis_U_UniformUS_tna_F";
		weapons[]=
		{
			"AX_srifle_DMR_03_khaki_DMS_LP_BI_snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_03_khaki_DMS_LP_BI_snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"H_Cap_tna_hs_F",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_tna_hs_F",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Recon_MG_F: B_recon_MG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_MG_F.jpg";
		uniformClass="AddGis_U_UniformUS_tna_F";
		weapons[]=
		{
			"AX_LMG_Mk200_khk_nogrip_Hamr_Pointer_Bipod_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_khk_nogrip_Hamr_Pointer_Bipod_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"Aegis_V_PlateCarrier_RF_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"Aegis_V_PlateCarrier_RF_oli",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
    class B_T_Recon_CQ_F: B_recon_CQ_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Recon_CQ_F.jpg";
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Sniper_F: B_sniper_F
	{
        editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Sniper_F.jpg";
	};
	class B_T_Spotter_F: B_spotter_F
	{
        editorPreview="\ax_alternateus\editor_previews_us\data\B_T_Spotter_F.jpg";
		uniformClass="U_B_T_Sniper_F";
		weapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws"
		};
    };
    class B_T_ghillie_tna_F: B_ghillie_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_ghillie_tna_F.jpg";
		uniformClass="U_B_T_FullGhillie_tna_F";
		weapons[]=
		{
			"srifle_LRR_tna_LRPS_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_LRR_tna_LRPS_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_green"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_green"
		};
	};
	class B_T_ghillie_spotter_tna_F: B_T_ghillie_tna_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_T_ghillie_spotter_tna_F.jpg";
		weapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_khk_ACO_Pointer_Snds_F",
			"hgun_P07_khk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"30Rnd_65x39_caseless_khaki_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
