    class B_W_Recon_AR_F: B_recon_AR_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_AR_F.jpg";
		uniformClass="AddGis_U_UniformUS_03_wdl_F";
		weapons[]=
		{
			"arifle_MX_SW_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_SW_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_Exp_F: B_recon_exp_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_Exp_F.jpg";
		uniformClass="AddGis_U_UniformUS_03_wdl_F";
		backpack="B_AssaultPack_rgr_ReconExp";
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Booniehat_wdl_hs",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_wdl_hs",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_GL_F: B_recon_GL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_GL_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_wdl_F";
		weapons[]=
		{
			"arifle_MX_GL_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_JTAC_F: B_recon_JTAC_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_JTAC_F.jpg";
		uniformClass="AddGis_U_UniformUS_wdl_F";
		backpack="B_RadioBag_01_wdl_F";
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_MG_F: B_recon_MG_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_MG_F.jpg";
		uniformClass="AddGis_U_UniformUS_wdl_F";
		weapons[]=
		{
			"AX_LMG_Mk200_nogrip_black_RCO_LP_S_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_nogrip_black_RCO_LP_S_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"Aegis_V_PlateCarrier_RF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"Aegis_V_PlateCarrier_RF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_M_F: B_recon_M_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_M_F.jpg";
		uniformClass="AddGis_U_UniformUS_wdl_F";
		weapons[]=
		{
			"arifle_MXM_Black_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MXM_Black_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Booniehat_wdl_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Booniehat_wdl_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_Medic_F: B_recon_medic_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_Medic_F.jpg";
		uniformClass="AddGis_U_UniformUS_03_wdl_F";
		backpack="B_AssaultPack_rgr_ReconMedic";
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_F: B_recon_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_wdl_F";
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Watchcap_camo_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_LAT_F: B_recon_LAT_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_LAT_F.jpg";
		uniformClass="AddGis_U_UniformUS_03_wdl_F";
		backpack="B_AssaultPack_rgr_ReconLAT";
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"launch_NLAW_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"launch_NLAW_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_ChestrigF_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_CQ_F: B_recon_CQ_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_CQ_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_wdl_F";
		weapons[]=
		{
			"sgun_KSG_ACO_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"sgun_KSG_ACO_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_TL_F: B_recon_TL_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_TL_F.jpg";
		uniformClass="AddGis_U_UniformUS_02_wdl_F";
		weapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetSpecB_light_green",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Recon_Sharpshooter_F: B_Recon_Sharpshooter_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Recon_Sharpshooter_F.jpg";
		uniformclass="AddGis_U_UniformUS_wdl_F";
		weapons[]=
		{
			"AX_srifle_DMR_03_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_03_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"H_Cap_usblack_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_usblack_hs",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Sniper_F: B_sniper_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Sniper_F.jpg";
		uniformClass="U_B_GhillieSuit_wdl_f";
		weapons[]=
		{
			"srifle_LRR_LRPS_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_LRR_LRPS_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_black"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_black"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Spotter_F: B_spotter_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_Spotter_F.jpg";
		uniformClass="U_B_GhillieSuit_wdl_f";
		weapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_ghillie_wdl_F: B_ghillie_base_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_ghillie_wdl_F.jpg";
		uniformClass="U_B_W_FullGhillie_wdl_F";
		weapons[]=
		{
			"srifle_LRR_LRPS_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_LRR_LRPS_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_black"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_black"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_ghillie_spotter_wdl_F: B_W_ghillie_wdl_F
	{
		editorPreview="\ax_alternateus\editor_previews_us\data\B_W_ghillie_spotter_wdl_F.jpg";
		weapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws"
		};
		linkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};