class CfgPatches
{
	class ax_grounded_csat_takistan_2035_jca_compat
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"ax_grounded_csat_takistan_2035",
			"Weapons_F_JCA_IA"
		};
		author="Axle";
		skipwhenmissingdependencies=1;
	};
};

class CfgVehicles
{
	class LSV_02_unarmed_base_F;
	class LSV_02_AT_base_F;
	class LSV_02_armed_base_F;
	class Atlas_O_T_LSV_02_unarmed_F: LSV_02_unarmed_base_F
	{
		class TransportMagazines
		{
			class _xx_17Rnd_9x21_Mag
			{
				magazine="JCA_15Rnd_9x21_M9A1_Mag";
				count=12;
			};
		};
	};
	class Atlas_O_T_LSV_02_AT_F: LSV_02_AT_base_F
	{
		class TransportMagazines
		{
			class _xx_17Rnd_9x21_Mag
			{
				magazine="JCA_15Rnd_9x21_M9A1_Mag";
				count=12;
			};
		};
	};
	class Atlas_O_T_LSV_02_armed_F: LSV_02_armed_base_F
	{
		class TransportMagazines
		{
			class _xx_17Rnd_9x21_Mag
			{
				magazine="JCA_15Rnd_9x21_M9A1_Mag";
				count=12;
			};
		};
	};
	class Atlas_O_T_soldier_base_F;
	class Atlas_O_T_officer_F: Atlas_O_T_soldier_base_F
	{
		weapons[]=
		{
			"hgun_PDW2000_F",
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"hgun_PDW2000_F",
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
	};
	class Atlas_O_T_soldier_SL_F: Atlas_O_T_soldier_base_F
	{
		weapons[]=
		{
			"atlas_arifle_SCAR_L_ARCO_FL_F",
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"atlas_arifle_SCAR_L_ARCO_FL_F",
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
	};
	class Atlas_O_T_soldier_TL_F: Atlas_O_T_soldier_base_F
	{
		weapons[]=
		{
			"atlas_arifle_SCAR_L_GL_ARCO_FL_F",
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"atlas_arifle_SCAR_L_GL_ARCO_FL_F",
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"30Rnd_556x45_stanag_sand_tracer_green",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
	};
	class Atlas_O_T_Fighter_Pilot_F: Atlas_O_T_soldier_base_F
	{
		weapons[]=
		{
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_hgun_M9A1_black_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
	};
	class AX_Atlas_O_T_Soldier_recon_base;
	class AX_Atlas_O_T_Recon_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_Recon_TL_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_Recon_exp_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_Recon_AR_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_LMG_03_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_LMG_03_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_Recon_M_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_grip_black_DMS_LP_snds_BP_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_grip_black_DMS_LP_snds_BP_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_Recon_medic_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_Recon_GL_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_L_GL_black_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_GL_black_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
	};
	class AX_Atlas_O_T_Recon_LAT_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"launch_RPG32_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"launch_RPG32_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"RPG32_F",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"RPG32_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_recon_JTAC_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ICO_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_03"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ICO_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_03"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class AX_Atlas_O_T_Recon_CQ_F: AX_Atlas_O_T_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_sgun_aa40_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_sgun_aa40_Holo_LP_snds_F",
			"AX_hgun_M9A1_black_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"JCA_15Rnd_9x21_M9A1_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
};
