class cfgPatches
{
	class ax_grounded_resfor_fia_2035_rf
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"RF_Data_Loadorder",
			"A3_Atlas_Data_F_Atlas_Loadorder"
		};
		author = "Axle";
		skipwhenmissingdependencies = 1;
	};
};

class cfgWeapons
{
	class srifle_h6_oli_rf;
	class srifle_h6_oli_dms_RF: srifle_h6_oli_rf
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_DMS_weathered_F";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_03_F_blk";
			};
		};
	};
};

class cfgVehicles
{
	class B_G_Soldier_SL_F;
	class I_G_Soldier_SL_F;
	class O_G_Soldier_SL_F;
	class B_G_Scout_RF: B_G_Soldier_SL_F
	{
		weapons[]=
		{
			"srifle_h6_oli_dms_RF",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"srifle_h6_oli_dms_RF",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_TacVest_rig_blk_RF",
			"H_ShemagOpen_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_blk_RF",
			"H_ShemagOpen_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		headgearList[]=
		{
			"H_Bandanna_gry",
			1,
			"H_Bandanna_blu",
			1,
			"H_Bandanna_cbr",
			1,
			"H_Bandanna_khk",
			1,
			"H_Bandanna_khk_hs",
			1,
			"H_Bandanna_sgg",
			1,
			"H_Bandanna_sand",
			1,
			"H_Bandanna_surfer",
			1,
			"H_Bandanna_surfer_blk",
			1,
			"H_Bandanna_surfer_grn",
			1,
			"H_Bandanna_camo",
			1,
			"H_Bandanna_camo_hs",
			1,
			"H_Watchcap_blk",
			1,
			"H_Watchcap_cbr",
			1,
			"H_Watchcap_camo",
			1,
			"H_Watchcap_khk",
			1,
			"H_Watchcap_sgg",
			1,
			"H_Watchcap_red",
			1,
			"H_Watchcap_blk_hs",
			1,
			"H_Watchcap_cbr_hs",
			1,
			"H_Watchcap_camo_hs",
			1,
			"H_Watchcap_khk_hs",
			1,
			"H_Booniehat_khk",
			1,
			"H_Booniehat_khk_hs",
			1,
			"H_Booniehat_oli",
			1,
			"H_Booniehat_tan",
			1,
			"H_Booniehat_dgtl",
			1,
			"H_Booniehat_mgrn",
			1,
			"H_Booniehat_oli_hs",
			1,
			"H_Booniehat_dgtl_hs",
			1,
			"H_Booniehat_mgrn_hs",
			1,
			"H_Cap_blk",
			1,
			"H_Cap_grn",
			1,
			"H_Cap_khk",
			1,
			"H_Cap_oli",
			1,
			"H_Cap_oli_hs",
			1,
			"H_Cap_tan",
			1,
			"H_Cap_blk_Raven",
			1,
			"H_Cap_blk_Raven_hs",
			1,
			"H_Shemag_olive",
			1,
			"H_Shemag_olive_hs",
			1,
			"H_ShemagOpen_tan",
			1,
			"H_ShemagOpen_khk",
			1,
			"H_ShemagOpen_khk_hs",
			1,
			"H_ShemagOpen_tan_hs",
			1,
			"H_HeadSet_light_F",
			1,
			"H_Hat_Safari_sand_F",
			1,
			"H_Hat_Safari_olive_F",
			1,
			"H_PASGT_basic_black_F",
			1,
			"H_PASGT_basic_green_F",
			1,
			"H_PASGT_basic_olive_F",
			1,
			"H_FakeHeadgear_F",
			1
		};
	};
	class I_G_Scout_RF: I_G_Soldier_SL_F
	{
		weapons[]=
		{
			"srifle_h6_oli_dms_RF",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"srifle_h6_oli_dms_RF",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_TacVest_rig_blk_RF",
			"H_ShemagOpen_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_blk_RF",
			"H_ShemagOpen_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		headgearList[]=
		{
			"H_Bandanna_gry",
			1,
			"H_Bandanna_blu",
			1,
			"H_Bandanna_cbr",
			1,
			"H_Bandanna_khk",
			1,
			"H_Bandanna_khk_hs",
			1,
			"H_Bandanna_sgg",
			1,
			"H_Bandanna_sand",
			1,
			"H_Bandanna_surfer",
			1,
			"H_Bandanna_surfer_blk",
			1,
			"H_Bandanna_surfer_grn",
			1,
			"H_Bandanna_camo",
			1,
			"H_Bandanna_camo_hs",
			1,
			"H_Watchcap_blk",
			1,
			"H_Watchcap_cbr",
			1,
			"H_Watchcap_camo",
			1,
			"H_Watchcap_khk",
			1,
			"H_Watchcap_sgg",
			1,
			"H_Watchcap_red",
			1,
			"H_Watchcap_blk_hs",
			1,
			"H_Watchcap_cbr_hs",
			1,
			"H_Watchcap_camo_hs",
			1,
			"H_Watchcap_khk_hs",
			1,
			"H_Booniehat_khk",
			1,
			"H_Booniehat_khk_hs",
			1,
			"H_Booniehat_oli",
			1,
			"H_Booniehat_tan",
			1,
			"H_Booniehat_dgtl",
			1,
			"H_Booniehat_mgrn",
			1,
			"H_Booniehat_oli_hs",
			1,
			"H_Booniehat_dgtl_hs",
			1,
			"H_Booniehat_mgrn_hs",
			1,
			"H_Cap_blk",
			1,
			"H_Cap_grn",
			1,
			"H_Cap_khk",
			1,
			"H_Cap_oli",
			1,
			"H_Cap_oli_hs",
			1,
			"H_Cap_tan",
			1,
			"H_Cap_blk_Raven",
			1,
			"H_Cap_blk_Raven_hs",
			1,
			"H_Shemag_olive",
			1,
			"H_Shemag_olive_hs",
			1,
			"H_ShemagOpen_tan",
			1,
			"H_ShemagOpen_khk",
			1,
			"H_ShemagOpen_khk_hs",
			1,
			"H_ShemagOpen_tan_hs",
			1,
			"H_HeadSet_light_F",
			1,
			"H_Hat_Safari_sand_F",
			1,
			"H_Hat_Safari_olive_F",
			1,
			"H_PASGT_basic_black_F",
			1,
			"H_PASGT_basic_green_F",
			1,
			"H_PASGT_basic_olive_F",
			1,
			"H_FakeHeadgear_F",
			1
		};
	};
	class O_G_Scout_RF: O_G_Soldier_SL_F
	{
		weapons[]=
		{
			"srifle_h6_oli_dms_RF",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"srifle_h6_oli_dms_RF",
			"hgun_ACPC2_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"10Rnd_556x45_AP_Stanag_RF",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellBlue",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"V_TacVest_rig_blk_RF",
			"H_ShemagOpen_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_blk_RF",
			"H_ShemagOpen_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		headgearList[]=
		{
			"H_Bandanna_gry",
			1,
			"H_Bandanna_blu",
			1,
			"H_Bandanna_cbr",
			1,
			"H_Bandanna_khk",
			1,
			"H_Bandanna_khk_hs",
			1,
			"H_Bandanna_sgg",
			1,
			"H_Bandanna_sand",
			1,
			"H_Bandanna_surfer",
			1,
			"H_Bandanna_surfer_blk",
			1,
			"H_Bandanna_surfer_grn",
			1,
			"H_Bandanna_camo",
			1,
			"H_Bandanna_camo_hs",
			1,
			"H_Watchcap_blk",
			1,
			"H_Watchcap_cbr",
			1,
			"H_Watchcap_camo",
			1,
			"H_Watchcap_khk",
			1,
			"H_Watchcap_sgg",
			1,
			"H_Watchcap_red",
			1,
			"H_Watchcap_blk_hs",
			1,
			"H_Watchcap_cbr_hs",
			1,
			"H_Watchcap_camo_hs",
			1,
			"H_Watchcap_khk_hs",
			1,
			"H_Booniehat_khk",
			1,
			"H_Booniehat_khk_hs",
			1,
			"H_Booniehat_oli",
			1,
			"H_Booniehat_tan",
			1,
			"H_Booniehat_dgtl",
			1,
			"H_Booniehat_mgrn",
			1,
			"H_Booniehat_oli_hs",
			1,
			"H_Booniehat_dgtl_hs",
			1,
			"H_Booniehat_mgrn_hs",
			1,
			"H_Cap_blk",
			1,
			"H_Cap_grn",
			1,
			"H_Cap_khk",
			1,
			"H_Cap_oli",
			1,
			"H_Cap_oli_hs",
			1,
			"H_Cap_tan",
			1,
			"H_Cap_blk_Raven",
			1,
			"H_Cap_blk_Raven_hs",
			1,
			"H_Shemag_olive",
			1,
			"H_Shemag_olive_hs",
			1,
			"H_ShemagOpen_tan",
			1,
			"H_ShemagOpen_khk",
			1,
			"H_ShemagOpen_khk_hs",
			1,
			"H_ShemagOpen_tan_hs",
			1,
			"H_HeadSet_light_F",
			1,
			"H_Hat_Safari_sand_F",
			1,
			"H_Hat_Safari_olive_F",
			1,
			"H_PASGT_basic_black_F",
			1,
			"H_PASGT_basic_green_F",
			1,
			"H_PASGT_basic_olive_F",
			1,
			"H_FakeHeadgear_F",
			1
		};
	};
};