	class O_Soldier_F;
	class Atlas_O_Soldier_R_base_F: O_Soldier_F
	{
		linkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_A_F: Atlas_O_Soldier_R_base_F
  	{
	};
  	class Atlas_O_Soldier_R_AR_F: Atlas_O_Soldier_R_base_F
  	{
  	};
  	class Atlas_O_Soldier_R_Medic_F: Atlas_O_Soldier_R_base_F
  	{
		linkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
	class O_crew_F;
  	class Atlas_O_Crew_R_F: O_crew_F
  	{
  	  	linkedItems[]=
		{
			"Atlas_V_OCarrierRig_khk_F",
			"lxWS_H_tank_tan_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_khk_F",
			"lxWS_H_tank_tan_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_Engineer_F: Atlas_O_Soldier_R_base_F
  	{
	};
  	class Atlas_O_Soldier_R_Exp_F: Atlas_O_Soldier_R_base_F
  	{
		linkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_GL_F: Atlas_O_Soldier_R_base_F
  	{
  	 	linkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_HG_F: Atlas_O_Soldier_R_base_F
  	{
	};
  	class Atlas_O_Soldier_R_M_F: Atlas_O_Soldier_R_base_F
  	{
	};
  	class Atlas_O_Soldier_R_AA_F: Atlas_O_Soldier_R_base_F
  	{
	};
  	class Atlas_O_Soldier_R_AT_F: Atlas_O_Soldier_R_base_F
  	{
  	};
  	class Atlas_O_Soldier_R_RadioOp_F: Atlas_O_Soldier_R_base_F
  	{
  	};
  	class Atlas_O_Soldier_R_F: Atlas_O_Soldier_R_base_F
  	{
  	};
  	class Atlas_O_Soldier_R_LAT_F: Atlas_O_Soldier_R_base_F
  	{
	};
  	class Atlas_O_Soldier_R_SL_F: Atlas_O_Soldier_R_base_F
  	{
  	  	linkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_TL_F: Atlas_O_Soldier_R_base_F
  	{
		linkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_UAV_F: Atlas_O_Soldier_R_base_F
  	{
  	  	linkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AddGis_V_LBV_khk_F",
			"AX_H_HelmetPCH_bare_blk_F",
			"NVGoggles_OPFOR",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};