	class G_Balaclava_blk: None
	{
		identityTypes[]=
		{
			"G_RUS_default",
			25,
			"G_RUS_SF",
			25,
			"NoGlasses",
			0,
			"G_IRAN_SF",
			0
		};
	};
	class AX_G_Balaclava_combat_blk_lxWS: G_Balaclava_combat
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_G_Balaclava_combat_blk_lxWS";
		hiddenSelectionsTextures[]=
		{
			"\lxws\characters_f_lxws\headgear\a3\data\headgear_balaclava_blk_co.paa",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\lxws\characters_f_lxws\headgear\a3\data\headgear_balaclava.rvmat"
		};
		identityTypes[]={};
	};
	class AX_G_Bandanna_blk: G_Bandanna_blk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		identityTypes[]=
		{
			"G_IRAN_default",
			25
		};
	};
	class AX_G_Shemag_tan: G_Shemag_tan
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		identityTypes[]=
		{
			"G_IRAN_default",
			50
		};
	};
	class AX_G_Lowprofile: G_Lowprofile
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		identityTypes[]=
		{
			"G_IRAN_default",
			25
		};
	};
	class AX_G_Balaclava_blk_lxWS: G_Balaclava_blk_lxWS
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		identityTypes[]=
		{
			"G_IRAN_SF",
			100,
			"G_IRAN_default",
			10
		};
	};
	class AX_G_Balaclava_mesh_blk_F: G_Balaclava_light_blk_F
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_G_Balaclava_mesh_blk_F0";
		picture="\ax_grounded_futura\characters_f_grounded\facewear\data\ui\icon_G_Balaclava_mesh_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Balaclava_mesh_blk_F_CO.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Mesh_Balaclava.rvmat"
		};
		identityTypes[]={};
	};
	class AX_G_Balaclava_mesh_G_blk_F: G_Balaclava_light_G_blk_F
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_G_Balaclava_mesh_G_blk_F0";
		picture="\ax_grounded_futura\characters_f_grounded\facewear\data\ui\icon_G_Balaclava_mesh_G_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Balaclava_mesh_blk_F_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Mesh_Balaclava.rvmat",
			"\A3\Characters_F\Heads\Glasses\Data\G_Combat.rvmat"
		};
	};
	class AX_G_Goggles_AR: G_Goggles_VR
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_G_Goggles_AR_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_AR_CO_cn.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_AR.rvmat"
		};
		identityTypes[]={};
	};
	class AX_G_Aviator_cn: G_Aviator
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		identityTypes[]=
		{
			"G_CHINA_officer",
			400
		};
	};
	class AX_G_Shades_Black_cn: G_Shades_Black
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		identityTypes[]=
		{
			"G_CHINA_default",
			50
		};
	};
	class AX_G_Sport_Black: G_Sport_Checkered
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		displayname="$STR_A3_GS_G_Sport_Black_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\sunglasses_sport_black_ca.paa"
		};
		identityTypes[]=
		{
			"G_CHINA_default",
			50
		};
	};
	class AX_G_Squares_cn: G_Squares
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GS_Axle";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Square_Spectacles_CO.paa"
		};
		identityTypes[]=
		{
			"G_CHINA_default",
			50
		};
	};
	class AX_G_Balaclava_nylon_blk: None
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_G_Balaclava_nylon_blk_F0";
		picture="\ax_grounded_futura\characters_f_grounded\facewear\data\ui\icon_G_Balaclava_nylon_blk_F_ca.paa";
		model="\ax_grounded_futura\characters_f_grounded\facewear\mask_balaclava.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\mask_balaclava_blk_CO.paa"
		};
		identityTypes[]={};
	};
	class AX_G_Balaclava_G_nylon_blk: None
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_G_Balaclava_nylon_G_blk_F0";
		picture="\ax_grounded_futura\characters_f_grounded\facewear\data\ui\icon_G_Balaclava_nylon_G_blk_F_ca.paa";
		model="\ax_grounded_futura\characters_f_grounded\facewear\mask_balaclava_goggles.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\mask_balaclava_blk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\goggles_pla_blk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\goggles_pla_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\mask_balaclava.rvmat",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\goggles_pla.rvmat",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\goggles_pla.rvmat"
		};
		identityTypes[]={};
	};
	class AX_G_Balaclava_ribbed_blk_F: G_Balaclava_TI_blk_F
	{
		author="$STR_A3_GS_Grave";
		displayName="$STR_A3_GS_G_Balaclava_ribbed_blk_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Balaclava_ribbed_blk_CO.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Ribbed_balaclava.rvmat"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_RUS_default",
			25,
			"G_RUS_SF",
			25
		};
		mass=6;
	};
	class AX_G_Balaclava_ribbed_grn_F: AX_G_Balaclava_ribbed_blk_F
	{
		author="$STR_A3_GS_Grave";
		displayName="$STR_A3_GS_G_Balaclava_ribbed_grn_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Balaclava_ribbed_grn_CO.paa"
		};
	};
	class AX_G_Balaclava_ribbed_G_blk_F: G_Balaclava_TI_G_blk_F
	{
		author="$STR_A3_GS_Grave";
		displayName="$STR_A3_GS_G_Balaclava_ribbed_G_blk_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Balaclava_ribbed_blk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Ribbed_balaclava.rvmat"
		};
		identityTypes[]={};
		mass=6;
	};
	class AX_G_Balaclava_ribbed_G_grn_F: AX_G_Balaclava_ribbed_G_blk_F
	{
		author="$STR_A3_GS_Grave";
		displayName="$STR_A3_GS_G_Balaclava_ribbed_G_grn_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Balaclava_ribbed_grn_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
	};