	class AX_H_PilotHelmetHeli_O_Hex: H_PilotHelmetHeli_O
	{
		scope=1;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_H_PilotHelmetHeli_O_hex_F0";
		picture="\A3\Characters_F\data\ui\icon_H_Pilot_Helmet_Heli_OI_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\helmet_heli_Hex_CO.paa"
		};
	};
	class AX_H_PilotHelmetHeli_O_GHex: H_PilotHelmetHeli_O
	{
		scope=1;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_H_PilotHelmetHeli_O_ghex_F0";
		picture="\A3\Characters_F\data\ui\icon_H_Pilot_Helmet_Heli_OI_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\helmet_heli_GHex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_hex_F: H_HelmetAggressor_base_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetAggressor_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetAggressor_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetAggressor_01_Hex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_ghex_F: H_HelmetAggressor_base_F
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_H_HelmetAggressor_ghex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetAggressor_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetAggressor_01_GHex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_dhex_F: H_HelmetAggressor_base_F
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_H_HelmetAggressor_dhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetAggressor_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetAggressor_01_DHex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_cover_hex_F: H_HelmetAggressor_cover_base_F
	{
		author="$STR_A3_GS_Axle";
		scope=1;
		displayName="$STR_A3_GS_H_HelmetAggressor_cover_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetAggressor_cover_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\h_helmetaggressor_01_Hex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_cover_ghex_F: H_HelmetAggressor_cover_base_F
	{
		scope=1;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_H_HelmetAggressor_cover_ghex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetAggressor_cover_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetAggressor_01_GHex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_cover_dhex_F: H_HelmetAggressor_cover_base_F
	{
		scope=1;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_H_HelmetAggressor_cover_dhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetAggressor_cover_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetAggressor_01_DHex_CO.paa"
		};
	};
	class AX_H_Beret_CSAT_red: HelmetBase
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_H_Beret_CSAT_red_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_Beret_red_CA.paa";
		model="\ax_grounded_futura\characters_f_grounded\headgear\beret_pla.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\beret_pla_red_CO.paa"
		};
		class ItemInfo: ItemInfo
		{
			mass=8;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"\ax_grounded_futura\characters_f_grounded\headgear\data\beret_pla_red_CO.paa"
			};
			uniformModel="\ax_grounded_futura\characters_f_grounded\headgear\beret_pla.p3d";
			modelSides[]={2,3};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=0;
					passThrough=0;
				};
			};
		};
	};
	class H_HelmetO_ocamo: H_HelmetB
	{
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\tech.rvmat"
		};
	};
	class AX_H_HelmetCCH_Headset_blktan_F: Atlas_H_HelmetCCH_Headset_khk_F
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetCCH_Headset_blktan_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_blktan_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa"
		};
	};
	class AX_H_HelmetCCH_blktan_F: Atlas_H_HelmetCCH_khk_F
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetCCH_blktan_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_blktan_CO.paa"
		};
	};
	class AX_H_HelmetCCH_Cover_blkhex_F: Atlas_H_HelmetCCH_cover_hex_F
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetCCH_Cover_blkhex_F0";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_Cover_hex_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa"
		};
	};
	class AX_H_HelmetCCH_Cover_blksemiarid_F: Atlas_H_HelmetCCH_cover_hex_F
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetCCH_Cover_blksemiarid_F0";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_Cover_semiarid_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa"
		};
	};
	class AX_H_HelmetPCH_bare_base_F: HelmetBase //Protective Combat Helmet
	{
		author="$STR_A3_GS_Lukin";
		scope=0;
		displayName="$STR_A3_GS_H_HelmetPCH_bare_base_F0";
		model="\ax_grounded_futura\characters_f_grounded\headgear\ach_bare.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6"
		};
		descriptionShort="$STR_A3_SP_AL_II";
		class ItemInfo: ItemInfo
		{
			mass=33;
			hiddenSelections[]=
			{
				"camo",
				"camo1",
				"camo2",
				"camo3",
				"camo4",
				"camo5",
				"camo6"
			};
			allowedSlots[]={901,701,605};
			uniformModel="\ax_grounded_futura\characters_f_grounded\headgear\ach_bare.p3d";
			modelSides[]={0,3};
			class HitpointsProtectionInfo
			{
				class Head
				{
					hitpointName="HitHead";
					armor=8;
					passThrough=0.5;
				};
			};
		};
	};
	class AX_H_HelmetPCH_bare_blk_F: AX_H_HelmetPCH_bare_base_F
	{
		author="$STR_A3_GS_Lukin";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetPCH_bare_blk_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetPCH_bare_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\ach_blk_co.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"",
			"",
			"",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_Cover_hex_CO.paa"
		};
	};
	class AX_H_HelmetPCH_bare_hs_blk_F: AX_H_HelmetPCH_bare_base_F
	{
		author="$STR_A3_GS_Lukin";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetPCH_bare_hs_blk_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetPCH_bare_hs_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\ach_blk_co.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetFASTMT_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_Cover_hex_CO.paa"
		};
	};
	class AX_H_HelmetPCH_cover_base_F: AX_H_HelmetPCH_bare_base_F
	{
		author="$STR_A3_GS_Lukin";
		scope=0;
		displayName="$STR_A3_GS_H_HelmetPCH_cover_base_F0";
		model="\ax_grounded_futura\characters_f_grounded\headgear\ach_iran.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"camo3",
			"camo4",
			"camo5",
			"camo6"
		};
		class ItemInfo: ItemInfo
		{
			mass=43;
			hiddenSelections[]=
			{
				"camo",
				"camo1",
				"camo2",
				"camo3",
				"camo4",
				"camo5",
				"camo6"
			};
			uniformModel="\ax_grounded_futura\characters_f_grounded\headgear\ach_iran.p3d";
			modelSides[]={2,3};
		};
	};
	class AX_H_HelmetPCH_cover_hex_F: AX_H_HelmetPCH_cover_base_F
	{
		author="$STR_A3_GS_Lukin";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetPCH_cover_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetPCH_cover_hs_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\ach_cover_hex_CO.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetFASTMT_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_Cover_hex_CO.paa"
		};
	};
	class AX_H_HelmetPCH_cover_uhex_F: AX_H_HelmetPCH_cover_base_F
	{
		author="$STR_A3_GS_Lukin";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetPCH_cover_uhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetPCH_cover_hs_uhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\ach_cover_uhex_co.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetFASTMT_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_cover_autumn_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_Cover_hex_CO.paa"
		};
	};
	class AX_H_HelmetPCH_cover_lite_hex_F: AX_H_HelmetPCH_cover_base_F
	{
		author="$STR_A3_GS_Lukin";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetPCH_cover_lite_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetPCH_cover_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\ach_cover_hex_CO.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"",
			"",
			"",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_Cover_hex_CO.paa"
		};
	};
	class AX_H_HelmetPCH_cover_lite_uhex_F: AX_H_HelmetPCH_cover_base_F
	{
		author="$STR_A3_GS_Lukin";
		scope=2;
		displayName="$STR_A3_GS_H_HelmetPCH_cover_lite_uhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\headgear\data\ui\icon_H_HelmetPCH_cover_uhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Headgear\Data\H_HelmetSpecter_01_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\ach_cover_uhex_co.paa",
			"\A3_Atlas\characters_f_atlas\Headgear\Data\H_HelmetCCH_blk_CO.paa",
			"",
			"",
			"",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\H_HelmetCCH_Cover_hex_CO.paa"
		};
	};