    class U_O_PilotCoveralls: Uniform_Base
    {
        displayName="$STR_A3_GS_Pilot_coveralls_semihex_F0";
    };
    class AX_U_O_A_PilotCoveralls: Uniform_Base
    {
        author="$STR_A3_GS_Axle";
        scope=2;
        displayName="$STR_A3_GS_Pilot_coveralls_hex_F0";
        picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_U_O_PilotCoveralls_Hex_F_ca.paa";
        model="\A3\Characters_F\Common\Suitpacks\suitpack_civilian_F.p3d";
        hiddenSelections[]=
        {
            "camo"
        };
        hiddenSelectionsTextures[]=
        {
            "\ax_grounded_futura\characters_f_grounded\uniforms\data\pilot_suit_Hex_CO.paa"
        };
        class ItemInfo: UniformItem
        {
            uniformModel="-";
            uniformClass="AX_O_PilotCoveralls_01_hex_F";
            containerClass="Supply60";
            mass=100;
        };
    };
    class AX_U_UniformBDU_01_hex_F: Uniform_Base
    {
        author="$STR_A3_GS_Axle";
        scope=2;
        displayName="$STR_A3_GS_U_UniformBDU_01_hex_F0";
        picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_Atlas_U_UniformBDU_01_Hex_F_ca.paa";
        model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
        hiddenSelections[]=
        {
            "camo"
        };
        hiddenSelectionsTextures[]=
        {
            "\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_opfor_co.paa"
        };
        class ItemInfo: UniformItem
        {
            uniformModel="-";
            uniformClass="AX_UniformBDU_01_hex_F";
            containerClass="Supply40";
            mass=60;
        };
    };
    class AX_U_UniformBDU_02_hex_F: Uniform_Base
    {
        author="$STR_A3_GS_Axle";
        scope=2;
        displayName="$STR_A3_GS_U_UniformBDU_02_hex_F0";
        picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_Atlas_U_UniformBDU_02_Hex_F_ca.paa";
        model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
        hiddenSelections[]=
        {
            "camo"
        };
        hiddenSelectionsTextures[]=
        {
            "\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_opfor_co.paa"
        };
        class ItemInfo: UniformItem
        {
            uniformModel="-";
            uniformClass="AX_UniformBDU_02_hex_F";
            containerClass="Supply40";
            mass=60;
        };
    };
    class AX_U_O_CBRN_Suit_01_Hex_F: Uniform_Base
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_U_O_CBRN_Suit_01_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_U_O_CBRN_Suit_01_Hex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\uniforms\data\CBRN_Suit_01_Hex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_Hex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_CBRN_Suit_01_UHex_F: Uniform_Base
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_U_O_CBRN_Suit_01_uhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_U_O_CBRN_Suit_01_UHex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\uniforms\data\CBRN_Suit_01_UHex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_UHex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
    class AX_U_O_CBRN_Suit_01_GHex_F: Uniform_Base
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_U_O_CBRN_Suit_01_ghex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_U_O_CBRN_Suit_01_GHex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\uniforms\data\CBRN_Suit_01_GHex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_GHex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_CBRN_Suit_01_DHex_F: Uniform_Base
	{
		scope=2;
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_U_O_CBRN_Suit_01_dhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_U_O_CBRN_Suit_01_DHex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\uniforms\data\CBRN_Suit_01_DHex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_DHex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class U_O_CombatUniform_oucamo: Uniform_Base
	{
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="ax_uniform_O_soldierU_F";
			containerClass="Supply40";
			mass=80;
		};
	};
	class AX_U_O_CombatFatigues_blk_F: Uniform_Base
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_U_O_CombatFatigues_blk_F0";
		picture="\A3_Atlas\Characters_F_Atlas\Uniforms\Data\UI\Atlas_U_O_CombatFatigues_whex_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CombatFatigues_blk_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatFatigues_02_blk_F: Uniform_Base
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_U_O_CombatFatigues_02_blk_F0";
		picture="\A3_Atlas\Characters_F_Atlas\Uniforms\Data\UI\Atlas_U_O_CombatFatigues_02_whex_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CombatFatigues_02_blk_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatFatigues_blksemiarid_F: Uniform_Base
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_U_O_CombatFatigues_blksemiarid_F0";
		picture="\A3_Atlas\Characters_F_Atlas\Uniforms\Data\UI\Atlas_U_O_CombatFatigues_whex_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CombatFatigues_blksemiarid_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatFatigues_02_blksemiarid_F: Uniform_Base
	{
		author="$STR_A3_GS_SCollins";
		scope=2;
		displayName="$STR_A3_GS_U_O_CombatFatigues_02_blksemiarid_F0";
		picture="\A3_Atlas\Characters_F_Atlas\Uniforms\Data\UI\Atlas_U_O_CombatFatigues_02_whex_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CombatFatigues_02_blksemiarid_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CBRN_Suit_01_Taiga_F: Uniform_Base
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_U_O_CBRN_Suit_01_Taiga_F0";
		picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_U_O_CBRN_Suit_01_Taiga_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\uniforms\data\CBRN_Suit_01_Taiga_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_Taiga_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_CBRN_Suit_01_Arid_F: Uniform_Base
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_U_O_CBRN_Suit_01_Arid_F0";
		picture="\ax_grounded_futura\characters_f_grounded\uniforms\data\ui\icon_U_O_CBRN_Suit_01_Taiga_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\uniforms\data\CBRN_Suit_01_Arid_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_Arid_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_R_FullGhillie_frst_F: Uniform_Base
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_U_O_R_FullGhillie_frst_F0";
		picture="\A3\characters_f_mark\data\ui\icon_U_B_FullGhillie_lsh_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_R_ghillie_frst_F";
			containerClass="Supply60";
			mass=80;
		};
	};
	class AX_U_O_R_FullGhillie_dsrt_F: Uniform_Base
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_U_O_R_FullGhillie_dsrt_F0";
		picture="\A3\characters_f_mark\data\ui\icon_U_B_FullGhillie_lsh_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_R_ghillie_dsrt_F";
			containerClass="Supply60";
			mass=80;
		};
	};