	class AX_V_OCarrierRig_CQB_alt_hex_F: Atlas_V_OCarrierRig_CQB_alt_oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierRig_CQB_alt_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_OCarrierRig_CQB_alt_hex_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_hex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_Hex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_hex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_CQB_alt_uhex_F: Atlas_V_OCarrierRig_CQB_alt_oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierRig_CQB_alt_uhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_OCarrierRig_CQB_alt_uhex_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_blk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_UHex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_blk_CO.paa"
		};
	};
	class AX_V_OCarrierRig_CQB_alt_khkhex_F: Atlas_V_OCarrierRig_CQB_alt_oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierRig_CQB_alt_khkhex_F0";
		picture="\A3_Atlas\Characters_F_Atlas\Vests\Data\UI\Atlas_V_OCarrierRig_CQB_khk_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_khk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_Hex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_khk_CO.paa"
		};
	};
	class AX_V_OCarrierRig_GL_alt_hex_F: Atlas_V_OCarrierRig_GL_alt_Oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierRig_GL_alt_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_OCarrierRig_GL_alt_hex_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_hex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_Hex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_hex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_GL_alt_uhex_F: Atlas_V_OCarrierRig_GL_alt_Oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierRig_GL_alt_uhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_OCarrierRig_GL_alt_uhex_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_blk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_UHex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_blk_CO.paa"
		};
	};
	class AX_V_OCarrierRig_GL_alt_khkhex_F: Atlas_V_OCarrierRig_GL_alt_Oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierRig_GL_alt_khkhex_F0";
		picture="\A3_Atlas\Characters_F_Atlas\Vests\Data\UI\Atlas_V_OCarrierRig_GL_khk_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_khk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_Hex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_khk_CO.paa"
		};
	};
	class AX_V_OCarrierRig_Lite_alt_hex_F: Atlas_V_OCarrierRig_Lite_Alt_Oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierRig_Lite_alt_hex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_OCarrierRig_alt_hex_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_hex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_Hex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_Lite_alt_uhex_F: Atlas_V_OCarrierRig_Lite_Alt_Oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierRig_Lite_alt_uhex_F0";
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_OCarrierRig_alt_hex_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_blk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_UHex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_Lite_alt_khkhex_F: Atlas_V_OCarrierRig_Lite_Alt_Oli_F
	{
		author="$STR_A3_GS_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierRig_Lite_alt_khkhex_F0";
		picture="\A3_Atlas\Characters_F_Atlas\Vests\Data\UI\Atlas_V_OCarrierRig_Lite_khk_F_ca.paa";
		hiddenSelections[]=
		{
			"camo",
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_khk_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\CarrierRigKBT_01_Hex_CO.paa"
		};
	};
	class AX_V_HarnessO_hex_F: V_HarnessO_gry
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_V_HarnessO_hex_F0";
		picture="\A3\characters_f\Data\UI\icon_V_HarnessO_brn_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\tech_Hex2_CO.paa"
		};
	};
	class AX_V_HarnessOGL_hex_F: V_HarnessOGL_brn
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_V_HarnessOGL_hex_F0";
		picture="\A3\characters_f\Data\UI\icon_V_HarnessOGL_brn_CA.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\tech_Hex2_CO.paa"
		};
		class ItemInfo: ItemInfo
		{
			hiddenSelections[]=
			{
				"camo1",
				"camo2"
			};
		};
	};
	class AX_V_HarnessOSpec_hex_F: V_HarnessOSpec_brn
	{
		author="$STR_A3_A_AveryTheKitty";
		displayName="$STR_A3_GS_V_HarnessOSpec_hex_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\Data\UI\icon_V_HarnessOSpec_brn_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\headgear\data\tech_Hex2_CO.paa"
		};
	};
	class Atlas_V_ORigLBV_GHex_F: Atlas_V_ORigLBV_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\vests\data\ORigLBV_ghex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_CQB_GHex_F: Atlas_V_OCarrierRig_CQB_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\ORigLBV_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\OCarrierRig_GL_ghex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_GL_GHex_F: Atlas_V_OCarrierRig_GL_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\ORigLBV_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\OCarrierRig_GL_ghex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_Lite_gHex_F: Atlas_V_OCarrierRig_Lite_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\ORigLBV_ghex_CO.paa"
		};
	};
	class AX_V_SmershVest_01_taiga_F: V_SmershVest_01_base_F
	{
		author="$STR_A3_GS_Axle";
		scope=2;
		displayName="$STR_A3_GS_V_SmershVest_01_taiga_F0";
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_SmershVest_01_taiga_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\vests\data\Smersh_Taiga_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\Smersh_miscellaneous_Taiga_CO.paa"
		};
	};
	class AX_V_SmershVest_01_radio_taiga_F: V_SmershVest_01_radio_base_F
	{
		author="$STR_A3_GS_Axle";
		displayName="$STR_A3_GS_V_SmershVest_01_radio_taiga_F0";
		scope=2;
		picture="\ax_grounded_futura\characters_f_grounded\vests\data\ui\icon_V_SmershVest_01_radio_taiga_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_grounded\vests\data\Smersh_Taiga_CO.paa",
			"\ax_grounded_futura\characters_f_grounded\vests\data\Smersh_miscellaneous_Taiga_CO.paa"
		};
	};
	class Aegis_V_OCarrierLuchnik_GL_F: Aegis_V_OCarrierLuchnik_F
	{
		class ItemInfo;
	};
	class Aegis_V_OCarrierLuchnik_CQB_F: Aegis_V_OCarrierLuchnik_F
	{
		class ItemInfo;
	};
	class Aegis_V_OCarrierLuchnik_Lite_F: Aegis_V_OCarrierLuchnik_F
	{
		class ItemInfo;
	};
	class AX_V_OCarrierLuchnik_SuperLite_F: Aegis_V_OCarrierLuchnik_Lite_F
	{
		author="$STR_A3_A_Jamie";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_SuperLite_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_Lite_F_CA.paa";
		Model="\ax_grounded_futura\characters_f_grounded\vests\Aegis_OCarrierLuchnik_SuperLite_F.p3d";
		class ItemInfo: ItemInfo
		{
			uniformModel="\ax_grounded_futura\characters_f_grounded\vests\Aegis_OCarrierLuchnik_SuperLite_F.p3d";
			containerClass="Supply140";
			mass=25;
		};
	};
	class AX_V_OCarrierLuchnik_SuperLite_arid_F: AX_V_OCarrierLuchnik_SuperLite_F
	{
		author="$STR_A3_A_Jamie";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_SuperLite_arid_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_Lite_arid_F_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_ruarid_CO.paa"
		};
	};
	class AX_V_OCarrierLuchnik_SuperLite_blk_F: AX_V_OCarrierLuchnik_SuperLite_F
	{
		author="$STR_A3_A_Jamie";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_SuperLite_blk_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_Lite_blk_F_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_blk_CO.paa"
		};
	};
	class AX_V_OCarrierLuchnik_SuperLite_blk_urban_F: AX_V_OCarrierLuchnik_SuperLite_blk_F
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_A_Jamie";
		displayName="$STR_A3_GS_V_OCarrierLuchnik_SuperLite_blk_F0";
		class ItemInfo: ItemInfo
		{
			containerClass="Supply160";
			mass=30;
		};
	};
	class AX_V_OCarrierLuchnik_GLLite_F: Aegis_V_OCarrierLuchnik_GL_F
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_A_Jamie";
		displayName="$STR_A3_GS_V_OCarrierLuchnik_GLLite_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_GL_F_CA.paa";
		model="\ax_grounded_futura\characters_f_grounded\vests\Aegis_OCarrierLuchnik_GLLite_F.p3d";
		class ItemInfo: ItemInfo
		{
			uniformModel="\ax_grounded_futura\characters_f_grounded\vests\Aegis_OCarrierLuchnik_GLLite_F.p3d";
			containerClass="Supply140";
			mass=25;
		};
	};
	class AX_V_OCarrierLuchnik_GLLite_arid_F: AX_V_OCarrierLuchnik_GLLite_F
	{
		author="$STR_A3_A_Jamie";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_GLLite_arid_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_GL_arid_F_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_ruarid_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_GL_ruarid_CO.paa"
		};
	};
	class AX_V_OCarrierLuchnik_GLLite_blk_F: AX_V_OCarrierLuchnik_GLLite_F
	{
		author="$STR_A3_A_Jamie";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_GLLite_blk_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_GL_blk_F_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_GL_blk_CO.paa"
		};
	};
	class AX_V_OCarrierLuchnik_CQBLite_F: Aegis_V_OCarrierLuchnik_CQB_F
	{
		author="$STR_A3_A_Jamie";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_CQBLite_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_CQB_F_CA.paa";
		model="\ax_grounded_futura\characters_f_grounded\vests\Aegis_OCarrierLuchnik_CQBLite_F.p3d";
		class ItemInfo: ItemInfo
		{
			uniformModel="\ax_grounded_futura\characters_f_grounded\vests\Aegis_OCarrierLuchnik_CQBLite_F.p3d";
			containerClass="Supply140";
			mass=25;
		};
	};
	class AX_V_OCarrierLuchnik_CQBLite_arid_F: AX_V_OCarrierLuchnik_CQBLite_F
	{
		author="$STR_A3_A_Jamie";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_CQBLite_arid_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_CQB_arid_F_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_ruarid_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_GL_ruarid_CO.paa"
		};
	};
	class AX_V_OCarrierLuchnik_CQBLite_blk_F: AX_V_OCarrierLuchnik_CQBLite_F
	{
		author="$STR_A3_A_Jamie";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GS_V_OCarrierLuchnik_CQBLite_blk_F0";
		picture="\A3_Aegis\Characters_F_Aegis\Vests\data\UI\Aegis_V_OCarrierLuchnik_CQB_blk_F_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_blk_CO.paa",
			"\A3_Aegis\Characters_F_Aegis\Vests\data\OCarrierLuchnik_GL_blk_CO.paa"
		};
	};