//Men
    class gm_ge_army_crew_90_win: gm_ge_army_crew_mp2a1_80_base
	{
		scope=2;
		scopeCurator=2;
		isgmContent=1;
		dlc="gm";
		author="$STR_DN_GM";
        faction="gm_fc_ge_90_winter";
		editorPreview="\gm\gm_characters\gm_ge_characters\data\ui\editor\gm_ge_army_crew_mp2a1_80_oli.jpg";
        vehicleClass="gm_vc_men_90_winter";
        editorSubcategory="gm_esc_men_90_winter";
		rankInsignias="army_blk";
        uniformClass="gm_ge_army_uniform_soldier_parka_80_win";
		linkedItems[]=
		{
			"gm_ge_army_conat2",
			"ItemRadio",
			"ItemMap",
			"ItemWatch",
			"gm_ge_headgear_crewhat_80_blk"
		};
		respawnLinkedItems[]=
		{
			"gm_ge_army_conat2",
			"ItemRadio",
			"ItemMap",
			"ItemWatch",
			"gm_ge_headgear_crewhat_80_blk"
		};
        magazines[]=
		{
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk",
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk",
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk",
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk"
		};
		respawnMagazines[]=
		{
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk",
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk",
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk",
			"gm_32Rnd_9x19mm_b_DM11_mp2_blk"
		};
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_characters\gm_ge_characters\data\uniform\gm_ge_army_uniform_crew_80_oli_co"
		};
	};
    class gm_ge_army_pilot_90_win: gm_ge_army_pilot_p1_80_base
	{
		scope=2;
		scopeCurator=2;
		isgmContent=1;
		dlc="gm";
		author="$STR_DN_GM";
        faction="gm_fc_ge_90_winter";
        editorSubcategory="gm_esc_men_90_winter";
		editorPreview="\gm\gm_characters\gm_ge_characters\data\ui\editor\gm_ge_army_pilot_p1_80_oli.jpg";
		serviceBranch="ge_armyaviation";
		uniformClass="gm_ge_army_uniform_soldier_parka_80_win";
		linkedItems[]=
		{
			"gm_ge_army_conat2",
			"ItemRadio",
			"ItemMap",
			"ItemWatch",
			"gm_ge_headgear_sph4_oli",
			"gm_ge_army_vest_pilot_oli"
		};
		respawnLinkedItems[]=
		{
			"gm_ge_army_conat2",
			"ItemRadio",
			"ItemMap",
			"ItemWatch",
			"gm_ge_headgear_sph4_oli",
			"gm_ge_army_vest_pilot_oli"
		};
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_characters\gm_ge_characters\data\uniform\gm_ge_army_uniform_pilot_oli_co"
		};
	};
	class gm_ge_army_militarypolice_90_win: gm_ge_army_rifleman_parka_80_win_base
	{
		scope=2;
		scopeCurator=2;
		isgmContent=1;
		dlc="gm";
		author="$STR_DN_GM";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		displayName="$STR_DN_GM_MAN_MILITARYPOLICE_BASE";
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		Icon="iconMan";
		role="Rifleman";
		cost=80000;
		faction="gm_fc_ge_90_winter";
		editorSubcategory="gm_esc_men_90_winter";
		editorPreview="\gm\gm_characters\gm_ge_characters\data\ui\editor\gm_ge_army_militarypolice_p1_parka_80_win.jpg";
		serviceBranch="ge_mp";
		weapons[]=
		{
			"Throw",
			"Put",
			"gm_p1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_p1_blk"
		};
		magazines[]=
		{
			"gm_8Rnd_9x19mm_b_DM11_p1_blk",
			"gm_8Rnd_9x19mm_b_DM11_p1_blk"
		};
		respawnMagazines[]=
		{
			"gm_8Rnd_9x19mm_b_DM11_p1_blk",
			"gm_8Rnd_9x19mm_b_DM11_p1_blk"
		};
		linkedItems[]=
		{
			"gm_ge_army_conat2",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_red_militarypolice",
			"gm_ge_army_vest_80_mp_wht"
		};
		respawnLinkedItems[]=
		{
			"gm_ge_army_conat2",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_red_militarypolice",
			"gm_ge_army_vest_80_mp_wht"
		};
	};

//Anti-Air
    class gm_ge_army_gepard1a1_90_win: gm_ge_army_gepard1a1_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_gepard\gm_ge_army_gepard\data\win\gm_ge_army_gepard1a1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_gepard\gm_ge_army_gepard\data\win\gm_ge_army_gepard1a1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_gepard\gm_ge_army_gepard\data\win\gm_ge_army_gepard1a1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_gepard\gm_ge_army_gepard\data\win\gm_ge_army_gepard1a1_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_gepard\gm_ge_army_gepard\data\win\gm_ge_army_gepard1a1_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_aa_win";
		editorSubcategory="gm_esc_aa_win";
	};

//APCs
    class gm_ge_army_m113a1g_apc_90_win: gm_ge_army_m113a1g_apc_base
	{
		scope=2;
		scopeCurator=2;
        faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_m113a1g_apc_milan_90_win: gm_ge_army_m113a1g_apc_milan_base
	{
		scope=2;
		scopeCurator=2;
        faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_m113a1g_command_90_win: gm_ge_army_m113a1g_command_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_m113a1g_medic_90_win_rc: gm_ge_army_m113a1g_medic_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_ge_army_m113\data\win\gm_ge_army_m113a1g_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_luchsa1_90_win: gm_ge_army_luchsa1_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchsa1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchsa1_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_luchsa2_90_win: gm_ge_army_luchsa2_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchsa2_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchsa2_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_luchs\gm_ge_army_luchs\data\win\gm_ge_army_luchs_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_marder1a1plus_90_win: gm_ge_army_marder1a1plus_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_marder1a1a_90_win: gm_ge_army_marder1a1a_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_marder1a2_90_win: gm_ge_army_marder1a2_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_marder1\gm_ge_army_marder1\data\win\gm_ge_army_marder1a0_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_fuchsa0_command_90_win: gm_ge_army_fuchsa0_command_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchs_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_command_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_command_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_fuchsa0_engineer_90_win: gm_ge_army_fuchsa0_engineer_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchs_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_engineer_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_engineer_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_ge_army_fuchsa0_reconnaissance_90_win: gm_ge_army_fuchsa0_reconnaissance_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchs_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_reconnaissance_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_fuchs\gm_ge_army_fuchs\data\win\gm_ge_army_fuchsa0_reconnaissance_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};

//Artillery
    class gm_ge_army_kat1_463_mlrs_90_win: gm_ge_army_kat1_463_mlrs_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_463_mlrs_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_463_mlrs_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_463_mlrs_ext_05_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_Artillery_win";
		editorSubcategory="gm_esc_Artillery_win";
	};
    class gm_ge_army_m109g_90_win: gm_ge_army_m109g_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_ge_army_m109\data\win\gm_ge_army_m109_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_ge_army_m109\data\win\gm_ge_army_m109g_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_ge_army_m109\data\win\gm_ge_army_m109g_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_ge_army_m109\data\win\gm_ge_army_m109g_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_ge_army_m109\data\win\gm_ge_army_m109g_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_ge_army_m109\data\win\gm_ge_army_m109g_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_Artillery_win";
		editorSubcategory="gm_esc_Artillery_win";
	};

//Cars
    class gm_ge_army_u1300l_firefighter_90_win: gm_ge_army_u1300l_firefighter_base
	{
		scope=2;
		scopeCurator=2;
        faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_firefighter_ext_03_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_typ247_firefighter_90_win: gm_ge_army_typ247_firefighter_base
	{
		scope=2;
		scopeCurator=2;
        faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ247_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ247_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ247_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_k125_90_win: gm_ge_army_k125_base
	{
		scope=2;
		scopeCurator=2;
		editorSubcategory="gm_esc_car_win";
        faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
	};
    class gm_ge_army_typ1200_cargo_90_win: gm_ge_army_typ1200_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_ge_army_typ1\data\win\gm_ge_army_typ1200_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_ge_army_typ1\data\win\gm_ge_army_typ1200_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_ge_army_typ1\data\win\gm_ge_army_typ1200_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_typ1200_cargo_90_win_rc: gm_ge_army_typ1200_cargo_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_ge_army_typ1\data\win\gm_ge_army_typ1200_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_ge_army_typ1\data\win\gm_ge_army_typ1200_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_ge_army_typ1\data\win\gm_ge_army_typ1200_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
	class gm_ge_army_typ247_cargo_90_win: gm_ge_army_typ247_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ247_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ247_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ247_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_typ253_cargo_90_win: gm_ge_army_typ253_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_typ253_cargo_90_win_rc: gm_ge_army_typ253_cargo_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
	class gm_ge_army_typ253_mp_90_win: gm_ge_army_typ253_mp_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_militarypolice_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_ge_army_typ2\data\win\gm_ge_army_typ253_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_w123_cargo_90_win: gm_ge_army_w123_cargo_base
	{
		scope=2;
		scopeCurator=2;
		editorSubcategory="gm_esc_car_win";
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
	};
    class gm_ge_army_iltis_cargo_90_win: gm_ge_army_iltis_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_iltis_cargo_90_win_rc: gm_ge_army_iltis_cargo_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_02_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
	class gm_ge_army_iltis_milan_90_win: gm_ge_army_iltis_milan_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_iltis_mg3_90_win: gm_ge_army_iltis_mg3_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_iltis\gm_ge_army_iltis\data\win\gm_ge_army_iltis_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_kat1_454_reammo_90_win: gm_ge_army_kat1_454_reammo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_05_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_kat1_454_cargo_90_win: gm_ge_army_kat1_454_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_454_ext_05_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_u1300l_container_90_win: gm_ge_army_u1300l_container_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_cargo_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_cargo_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_u1300l_medic_90_win_rc: gm_ge_army_u1300l_medic_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_medic_ext_03_win_rc_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_u1300l_repair_90_win: gm_ge_army_u1300l_repair_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_cargo_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_cargo_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_u1300l_cargo_90_win: gm_ge_army_u1300l_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_cargo_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_ge_army_u1300l\data\win\gm_ge_army_u1300l_cargo_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_kat1_451_reammo_90_win: gm_ge_army_kat1_451_reammo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_kat1_451_container_90_win: gm_ge_army_kat1_451_container_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_kat1_451_container_90_win_rc: gm_ge_army_kat1_451_container_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_03_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
	class gm_ge_army_kat1_451_refuel_90_win: gm_ge_army_kat1_451_refuel_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_refuel_ext_05_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_kat1_451_cargo_90_win: gm_ge_army_kat1_451_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_ge_army_kat1_451_cargo_90_win_rc: gm_ge_army_kat1_451_cargo_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_03_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_451_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
	class gm_ge_army_kat1_452_container_90_win: gm_ge_army_kat1_452_container_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
	class gm_ge_army_kat1_452_container_90_win_rc: gm_ge_army_kat1_452_container_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_03_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_kat1\gm_ge_army_kat1\data\win\gm_ge_army_kat1_452_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win_rc",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};

//Helicopters
    class gm_ge_army_ch53g_90_win: gm_ge_army_ch53g_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};
	class gm_ge_army_ch53gs_90_win: gm_ge_army_ch53gs_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};
    class gm_ge_army_bo105p_pah1_90_win: gm_ge_army_bo105p_pah1_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};
    class gm_ge_army_bo105p_pah1a1_90_win: gm_ge_army_bo105p_pah1a1_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};
    class gm_ge_army_bo105m_vbh_90_win: gm_ge_army_bo105m_vbh_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};
    class gm_ge_army_bo105p1m_vbh_90_win: gm_ge_army_bo105p1m_vbh_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};
    class gm_ge_army_bo105p1m_vbh_swooper_90_win: gm_ge_army_bo105p1m_vbh_swooper_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};

//Planes
    class gm_ge_airforce_do28d2_90_win: gm_ge_airforce_do28d2_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};
    class gm_ge_airforce_do28d2_medevac_90_win: gm_ge_airforce_do28d2_medevac_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_pilot_90_win";
	};

//Tanks
    class gm_ge_army_bpz2a0_90_win: gm_ge_army_bpz2a0_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_ge_army_bpz2\data\win\gm_ge_army_bpz2a0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_ge_army_bpz2\data\win\gm_ge_army_bpz2a0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_ge_army_bpz2\data\win\gm_ge_army_bpz2a0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_ge_army_bpz2\data\win\gm_ge_army_bpz2a0_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_ge_army_bpz2\data\win\gm_ge_army_bpz2a0_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_ge_army_bibera0_90_win: gm_ge_army_bibera0_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_ge_army_biber\data\win\gm_ge_army_biber_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_ge_army_biber\data\win\gm_ge_army_biber_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_ge_army_biber\data\win\gm_ge_army_biber_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_ge_army_biber\data\win\gm_ge_army_biber_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_ge_army_biber\data\win\gm_ge_army_biber_ext_05_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_ge_army_biber\data\win\gm_ge_army_biber_bridge_ext_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_ge_army_Leopard1a1_90_win: gm_ge_army_Leopard1a1_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_ge_army_Leopard1a1a1_90_win: gm_ge_army_Leopard1a1a1_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_ge_army_Leopard1a1a2_90_win: gm_ge_army_Leopard1a1a2_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_ge_army_leopard1a1a3_90_win: gm_ge_army_Leopard1a1a3_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
	class gm_ge_army_leopard1a1a4_90_win: gm_ge_army_Leopard1a1a4_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a1a1_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
	class gm_ge_army_Leopard1a3_90_win: gm_ge_army_Leopard1a3_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_ge_army_Leopard1a3a1_90_win: gm_ge_army_Leopard1a3a1_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_ge_army_leopard1a3a2_90_win: gm_ge_army_Leopard1a3a2_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
	class gm_ge_army_leopard1a3a3_90_win: gm_ge_army_Leopard1a3a3_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a3_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
	class gm_ge_army_Leopard1a5_90_win: gm_ge_army_Leopard1a5_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a5_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a5_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
	class gm_ge_army_leopard1a5a1_90_win: gm_ge_army_Leopard1a5a1_base
	{
		scope=1;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a5_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_ge_army_leopard1\data\win\gm_ge_army_leopard1a5_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_ge_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};

//Turrets
    class gm_ge_army_milan_launcher_tripod_90_win: gm_ge_army_milan_launcher_tripod_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
	};
    class gm_ge_army_mg3_aatripod_90_win: gm_ge_army_mg3_aatripod_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_ge_90_winter";
		crew="gm_ge_army_rifleman_g36a1_90_win";
	};