//Men
    class gm_dk_army_crew_90_win: gm_dk_army_rifleman_84_win_base
	{
		scope=2;
		scopeCurator=2;
		isgmContent=1;
		dlc="gm";
		author="$STR_DN_GM";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		displayName="$STR_DN_GM_MAN_CREW_BASE";
		textSingular="$STR_A3_nameSound_veh_infantry_s";
		textPlural="$STR_A3_nameSound_veh_infantry_p";
		nameSound="veh_infantry_s";
		Icon="iconMan";
		role="Crewman";
		engineer=1;
		cost=80000;
        faction="gm_fc_dk_90_winter";
        editorSubcategory="gm_esc_men_90_winter";
		editorPreview="\gm\gm_characters\gm_dk_characters\data\ui\editor\gm_dk_army_crew_84_oli.jpg";
		weapons[]=
		{
			"Throw",
			"Put",
			"gm_gvm75carb_oli",
			"gm_ferod16_grn"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_gvm75carb_oli",
			"gm_ferod16_grn"
		};
		magazines[]=
		{
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_handGrenade_frag_dm51",
			"gm_handGrenade_frag_dm51"
		};
		respawnMagazines[]=
		{
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_handGrenade_frag_dm51",
			"gm_handGrenade_frag_dm51"
		};
		linkedItems[]=
		{
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"itemMap",
			"gm_ge_headgear_headset_crew_oli",
			"gm_dk_army_vest_54_crew"
		};
		respawnLinkedItems[]=
		{
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"itemMap",
			"gm_ge_headgear_headset_crew_oli",
			"gm_dk_army_vest_54_crew"
		};
	};

//APCs
    class gm_dk_army_m113a1dk_apc_90_win: gm_dk_army_m113a1dk_apc_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_dk_army_m113a1dk_command_90_win: gm_dk_army_m113a1dk_command_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_dk_army_m113a1dk_engineer_90_win: gm_dk_army_m113a1dk_engineer_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_dk_army_m113a1dk_medic_90_win_rc: gm_dk_army_m113a1dk_medic_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_01_win_rc_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113a1dk_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win_rc",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};
    class gm_dk_army_m113a2dk_90_win: gm_dk_army_m113a2dk_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m113\gm_dk_army_m113\data\win\gm_dk_army_m113_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m92\gm_dk_army_m92\data\win\gm_dk_army_m113a2dk_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m92\gm_dk_army_m92\data\win\gm_dk_army_m113a2dk_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m92\gm_dk_army_m92\data\win\gm_dk_army_m113a2dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m92\gm_dk_army_m92\data\win\gm_dk_army_m113a2dk_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m92\gm_dk_army_m92\data\win\gm_dk_army_m113a2dk_ext_03_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_apc_win";
		editorSubcategory="gm_esc_apc_win";
	};

//Artillery
    class gm_dk_army_m109_90_win: gm_dk_army_m109_base
	{
		scope=2;
		scopeCurator=2;
	    faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_dk_army_m109\data\win\gm_dk_army_m109_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_dk_army_m109\data\win\gm_dk_army_m109_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_dk_army_m109\data\win\gm_dk_army_m109_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_dk_army_m109\data\win\gm_dk_army_m109_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_dk_army_m109\data\win\gm_dk_army_m109_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_m109\gm_dk_army_m109\data\win\gm_dk_army_m109_ext_04_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_Artillery_win";
		editorSubcategory="gm_esc_Artillery_win";
	};

//Cars
    class gm_dk_army_typ1200_cargo_90_win: gm_dk_army_typ1200_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_rifleman_gvm95_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_dk_army_typ1\data\win\gm_dk_army_typ1200_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_dk_army_typ1\data\win\gm_dk_army_typ1200_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ1\gm_dk_army_typ1\data\win\gm_dk_army_typ1200_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_dk_army_typ247_cargo_90_win: gm_dk_army_typ247_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_rifleman_gvm95_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ247_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ247_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ247_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_dk_army_typ253_cargo_90_win: gm_dk_army_typ253_cargo_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_rifleman_gvm95_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ253_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ253_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ253_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_dk_army_typ253_mp_90_win: gm_dk_army_typ253_mp_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_rifleman_gvm95_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ2_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ253_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ253_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_typ2\gm_dk_army_typ2\data\win\gm_dk_army_typ253_int_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};
    class gm_dk_army_u1300l_container_90_win: gm_dk_army_u1300l_container_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_rifleman_gvm95_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_dk_army_u1300l\data\win\gm_dk_army_u1300l_rim_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_dk_army_u1300l\data\win\gm_dk_army_u1300l_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_dk_army_u1300l\data\win\gm_dk_army_u1300l_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_dk_army_u1300l\data\win\gm_dk_army_u1300l_cargo_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_wheeled\gm_u1300l\gm_dk_army_u1300l\data\win\gm_dk_army_u1300l_cargo_ext_04_win_co.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_car_win";
		editorSubcategory="gm_esc_car_win";
	};

//Tanks
    class gm_dk_army_bpz2a0_90_win: gm_dk_army_bpz2a0_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_dk_army_bpz2\data\win\gm_dk_army_bpz2a0_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_dk_army_bpz2\data\win\gm_dk_army_bpz2a0_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_dk_army_bpz2\data\win\gm_dk_army_bpz2a0_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_dk_army_bpz2\data\win\gm_dk_army_bpz2a0_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_bpz2\gm_dk_army_bpz2\data\win\gm_dk_army_bpz2a0_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_dk_army_bibera0_90_win: gm_dk_army_bibera0_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_dk_army_biber\data\win\gm_dk_army_biber_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_dk_army_biber\data\win\gm_dk_army_biber_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_dk_army_biber\data\win\gm_dk_army_biber_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_dk_army_biber\data\win\gm_dk_army_biber_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_dk_army_biber\data\win\gm_dk_army_biber_ext_05_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_biber\gm_dk_army_biber\data\win\gm_dk_army_biber_bridge_ext_01_win_co.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};
    class gm_dk_army_Leopard1a3_90_win: gm_dk_army_Leopard1a3_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_crew_90_win";
		hiddenSelectionsTextures[]=
		{
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1_wheels_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1_ext_01_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1_ext_02_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1_ext_03_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1a3_ext_04_win_co.paa",
			"\gm\gm_vehicles\gm_land\gm_tracked\gm_leopard1\gm_dk_army_leopard1\data\win\gm_dk_army_leopard1a3_ext_05_win_co.paa",
			"\gm\gm_core\data\camo\gm_camonet_01_nato_wdl_ca.paa"
		};
		textureList[]=
		{
			"gm_dk_army_win",
			1
		};
		vehicleclass="gm_vc_armor_win";
		editorSubcategory="gm_esc_armor_win";
	};

//Turrets
    class gm_dk_army_mg3_aatripod_90_win: gm_dk_army_mg3_aatripod_base
	{
		scope=2;
		scopeCurator=2;
		faction="gm_fc_dk_90_winter";
		crew="gm_dk_army_rifleman_gvm95_90_win";
	};