class CfgPatches
{
	class ax_grounded_opfor_russia_2035_rf
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"RF_Data_Loadorder",
			"A3_Aegis_Characters_F_Aegis_RF",
			"ax_grounded_soldiers_editorpreviews"
		};
		author="Axle";
		skipwhenmissingdependencies=1;
	};
};

class CfgVehicles
{
	class O_R_Man_Base_F;
	class Aegis_O_R_Soldier_Urban_Base_F: O_R_Man_Base_F
	{
		uniformClass="Aegis_U_O_Luchnik_urban_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_A_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_Carryall_blk_RU_Ammo_F";
	};
	class Aegis_O_R_SoldierU_AAR_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_FieldPack_blk_RU_AAR_F";
	};
	class Aegis_O_R_SoldierU_AR_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_AHAT_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_Carryall_blk_RU_AHAT_F";
	};
	class Aegis_O_R_SoldierU_AAA_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_Carryall_blk_RU_AAA_F";
	};
	class Aegis_O_R_engineerU_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_Carryall_blk_RU_eng_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_soldierU_AA_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_FieldPack_blk_RU_AA_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"Aegis_H_HelmetAggressor_cover_ruurban_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"Aegis_H_HelmetAggressor_cover_ruurban_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_soldierU_exp_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_Carryall_blk_RU_exp_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_M_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"Aegis_H_HelmetAggressor_cover_ruurban_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"Aegis_H_HelmetAggressor_cover_ruurban_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_medicU_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_FieldPack_blk_RU_Medic_F";
		magazines[]=
		{
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"20rnd_127x55_mag_rf",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
	};
	class Aegis_O_R_SoldierU_LAT_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_FieldPack_blk_RU_RPG_AT_F";
		uniformClass="Aegis_U_O_Luchnik_RolledUp_urban_F";
	};
	class Aegis_O_R_SoldierU_GL_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_HAT_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="Aegis_B_FieldPack_blk_RU_HAT_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_blk_urban_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_CQ_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_SL_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"Aegis_H_HelmetAggressor_cover_ruurban_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"Aegis_H_HelmetAggressor_cover_ruurban_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_TL_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_blk_F",
			"H_HelmetHeavy_Black_RF",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_RadioOperatorU_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		backpack="B_RadioBag_01_black_F";
	};
	class Aegis_O_R_SoldierU_unarmed_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SharpshooterU_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Aegis_O_R_SoldierU_Lite_F: Aegis_O_R_Soldier_Urban_Base_F
	{
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_blk_F",
			"H_HelmetHeavy_Simple_Black_RF",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
};