    class Atlas_O_T_soldier_F;
	class AX_Atlas_O_T_Soldier_recon_base: Atlas_O_T_soldier_F
	{
		scope=0;
		scopeCurator=0;
		textSingular="$STR_A3_nameSound_veh_infantry_SF_s";
		textPlural="$STR_A3_nameSound_veh_infantry_SF_p";
		nameSound="veh_infantry_SF_s";
		uniformClass="Atlas_U_O_CombatFatigues_02_semiarid_F";
		editorsubcategory="EdSubcat_Personnel_SpecialForces";
		items[]=
		{
			"FirstAidKit",
			"optic_Nightstalker"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_Nightstalker"
		};
		linkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		icon="iconManRecon";
		role="Rifleman";
	};
    class AX_Atlas_O_T_Recon_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_recon_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_recon_F0";
		uniformClass="AX_U_O_CombatFatigues_blksemiarid_F";
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_H_HelmetCCH_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
	class AX_Atlas_O_T_Recon_TL_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_recon_TL_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Recon_TL_F0";
		uniformClass="AX_U_O_CombatFatigues_blk_F";
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ACOG_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		icon="iconManLeader";
		role="Rifleman";
		threat[]={1,0.1,0.30000001};
	};
    class AX_Atlas_O_T_Recon_exp_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_Recon_exp_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Recon_exp_F0";
		uniformClass="AX_U_O_CombatFatigues_02_blk_F";
		backpack="AX_B_Carryall_cbr_OTExp_F";
		weapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"Aegis_V_CarrierRigKBT_01_cqb_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"Aegis_V_CarrierRigKBT_01_cqb_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		role="Rifleman";
		threat[]={1,0.1,0.30000001};
		icon="iconManExplosive";
		picture="pictureExplosive";
	};
	class AX_Atlas_O_T_Recon_AR_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_Recon_AR_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_C_O_R_recon_AR_F0";
		weapons[]=
		{
			"AX_LMG_03_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_LMG_03_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Atlas_H_HelmetCCH_blk_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_blk_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		icon="iconManMG";
		role="MachineGunner";
		threat[]={1,0.1,0.30000001};
	};
    class AX_Atlas_O_T_Recon_M_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_Recon_M_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_recon_M_F0";
		uniformClass="Atlas_U_O_CombatFatigues_semiarid_F";
		weapons[]=
		{
			"AX_arifle_SCAR_grip_black_DMS_LP_snds_BP_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_grip_black_DMS_LP_snds_BP_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"20Rnd_762x51_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		role="Marksman";
		threat[]={1,0.1,0.30000001};
	};
	class AX_Atlas_O_T_Recon_medic_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_Recon_medic_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_recon_medic_F0";
		uniformClass="AX_U_O_CombatFatigues_02_blksemiarid_F";
		backpack="AX_B_FieldPack_cbr_OTMedic_F";
		weapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_short_black_ICO_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_H_HelmetCCH_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_blktan_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		icon="iconManMedic";
		picture="pictureHeal";
		role="CombatLifeSaver";
		threat[]={1,0.1,0.30000001};
	};
	class AX_Atlas_O_T_Recon_GL_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_recon_GL_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_C_O_R_recon_GL_F0";
		uniformClass="AX_U_O_CombatFatigues_blksemiarid_F";
		weapons[]=
		{
			"AX_arifle_SCAR_L_GL_black_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_GL_black_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Headset_blk_F",
			"Aegis_V_CarrierRigKBT_01_cqb_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Headset_blk_F",
			"Aegis_V_CarrierRigKBT_01_cqb_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		role="Grenadier";
		threat[]={1,0.1,0.30000001};
	};
	class AX_Atlas_O_T_Recon_LAT_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_Recon_LAT_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_recon_LAT_F0";
		uniformClass="AX_U_O_CombatFatigues_blksemiarid_F";
		backpack="AX_B_FieldPack_cbr_OTLAT_F";
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"launch_RPG32_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"launch_RPG32_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"RPG32_F",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"30Rnd_556x45_AUG_Mag_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"RPG32_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"AX_H_HelmetCCH_Cover_blksemiarid_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_Cover_blksemiarid_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		icon="iconManAT";
		role="MissileSpecialist";
		threat[]={1,0.1,0.30000001};
	};
	class AX_Atlas_O_T_recon_JTAC_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_recon_JTAC_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_recon_JTAC_F0";
		uniformClass="AX_U_O_CombatFatigues_02_blksemiarid_F";
		backpack="B_RadioBag_01_semiarid_F";
		weapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ICO_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_03"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SCAR_L_grip_black_ICO_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_03"
		};
		magazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"30Rnd_556x45_Stanag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Headset_blk_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Headset_blk_F",
			"V_CarrierRigKBT_01_light_Khaki_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		role="SpecialOperative";
		threat[]={1,0.1,0.30000001};
	};
	class AX_Atlas_O_T_Recon_CQ_F: AX_Atlas_O_T_Soldier_recon_base
	{
		//editorPreview="\A3_Atlas\EditorPreviews_F_Atlas\Data\CfgVehicles\Atlas_O_W_Recon_CQ_F.jpg";
		author="$STR_A3_GS_Axle";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_A_CfgVehicles_B_recon_CQ_F0";
		uniformClass="Atlas_U_O_CombatFatigues_semiarid_F";
		weapons[]=
		{
			"AX_sgun_aa40_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_sgun_aa40_Holo_LP_snds_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Pellets_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"8Rnd_12Gauge_AA40_Slug_lxWS",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_red",
			"Chemlight_red"
		};
        linkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"Aegis_V_CarrierRigKBT_01_tac_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetCCH_Headset_blktan_F",
			"Aegis_V_CarrierRigKBT_01_tac_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};