	class O_Soldier_base_F;
	class O_Soldier_02_F;
	class O_Soldier_support_base_F;
	class O_Soldier_iran_base_F: O_Soldier_base_F{};
	class O_Soldier_iran_support_base_F: O_Soldier_support_base_F{};
	class O_Soldier_recon_base;
	class O_Soldier_A_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_A_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_AAR_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_AAR_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_support_AMG_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_support_AMG_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_support_AMort_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_support_AMort_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_AHAT_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_AHAT_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_AAT_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_AAT_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_AAA_F: O_Soldier_AAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_AAA_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_AR_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_AR_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_CQB_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_CQB_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_medic_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_medic_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_CQB_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_CQB_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_crew_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_crew_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"H_HelmetCrew_O",
			"AX_V_OCarrierRig_Hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_O",
			"AX_V_OCarrierRig_Hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_engineer_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_engineer_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_soldier_exp_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_exp_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_GL_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_GL_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_soldier_mine_F: O_soldier_exp_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_soldier_mine_F.jpg";
	};
	class O_Soldier_GL_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_GL_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_GL_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_GL_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_support_GMG_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_support_GMG_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_support_MG_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_support_MG_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_support_Mort_F: O_Soldier_iran_support_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_support_Mort_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_HeavyGunner_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_HeavyGunner_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		weapons[]=
		{
			"AX_MMG_01_black_ARCO_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_MMG_01_black_ARCO_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_CQB_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_CQB_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_helipilot_F: O_Soldier_02_F
	{
        uniformClass="U_O_PilotCoveralls";
		linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_helicrew_F: O_helipilot_F
	{
        uniformClass="U_O_PilotCoveralls";
		linkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_soldier_M_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_soldier_M_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		weapons[]=
		{
			"srifle_DMR_01_black_DMS_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_01_black_DMS_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_AA_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_AA_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_AT_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_AT_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_officer_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_officer_F.jpg";
        uniformClass="U_O_OfficerUniform_ocamo";
		linkedItems[]=
		{
			"H_Beret_CSAT_01_F",
			"V_Rangemaster_belt_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Beret_CSAT_01_F",
			"V_Rangemaster_belt_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_soldier_PG_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_PG_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Pilot_F: O_helipilot_F
	{
        uniformClass="U_O_PilotCoveralls";
		linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Fighter_Pilot_F: O_Pilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Fighter_Pilot_F.jpg";
        uniformClass="U_O_PilotCoveralls";
		linkedItems[]=
		{
			"H_PilotHelmetFighter_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetFighter_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_soldier_repair_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_repair_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_CBRN_F: O_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_CBRN_F.jpg";
        uniformClass="AX_U_O_CBRN_Suit_01_Hex_F";
		backpack="B_CombinationUnitRespirator_01_F";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"G_AirPurifyingRespirator_02_sand_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"G_AirPurifyingRespirator_02_sand_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_RadioOperator_F: O_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_RadioOperator_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_LAT_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_LAT_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_HAT_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_HAT_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_lite_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_lite_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"H_MilCap_ocamo",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_MilCap_ocamo",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_Soldier_CQ_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_CQ_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_unarmed_F: O_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_unarmed_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_Sharpshooter_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Sharpshooter_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Soldier_SL_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_SL_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Survivor_F: O_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Survivor_F.jpg";
	};
	class O_Soldier_TL_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_TL_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_GL_alt_hex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_GL_alt_hex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_soldier_UAV_F: O_Soldier_iran_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_UAV_F.jpg";
        uniformClass="U_O_LCF_noInsignia_hex_lxWS";
		linkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetPCH_cover_hex_F",
			"AX_V_OCarrierRig_Lite_alt_hex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
	};
	class O_soldier_UAV_06_F: O_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_soldier_UAV_06_F.jpg";
	};
	class O_soldier_UAV_06_medical_F: O_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_soldier_UAV_06_medical_F.jpg";
	};
	class O_soldier_UAV_lxWS: O_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_Soldier_UAV_F.jpg";
		weapons[]=
		{
			"arifle_Katiba_C_ACO_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Katiba_C_ACO_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
	};
	class O_soldier_UGV_02_Demining_F: O_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\futura\O_soldier_UGV_02_Demining_F.jpg";
	};
	class O_Story_Colonel_F: O_officer_F{};
	class O_Story_CEO_F: O_Soldier_iran_base_F{};
	class O_recon_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessOSpec_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessOSpec_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_M_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_TacVest_khk",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_khk",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_LAT_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_TacVest_khk",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_khk",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_medic_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_exp_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_JTAC_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_TL_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessOSpec_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessOSpec_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};	
	};
	class O_recon_CQ_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_TacVest_khk",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_khk",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_AR_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessOSpec_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessOSpec_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_recon_GL_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessOGL_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class O_Pathfinder_F: O_Soldier_recon_base
	{
		linkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_HarnessO_hex_F",
			"AX_H_HelmetAggressor_hex_F",
			"AX_G_Balaclava_combat_blk_lxWS",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};