    class O_Soldier_iran_urban_base_F: O_Soldier_base_F
    {
        displayName="$STR_O_Soldier_Urban_base0";
		vehicleClass="MenUrban";
		editorSubcategory="EdSubcat_Personnel_Camo_Urban";
		role="Rifleman";
        uniformClass="Aegis_U_O_LightCombatFatigues_urb_F";
    };
    class O_soldierU_F: O_Soldier_iran_urban_base_F
	{
        weapons[]=
		{
			"arifle_Katiba_ARCO_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Katiba_ARCO_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"30Rnd_65x39_caseless_green",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_AR_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_CQB_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_CQB_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_AAR_F: O_Soldier_iran_urban_base_F
	{
		linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_LAT_F: O_Soldier_iran_urban_base_F
	{
        weapons[]=
		{
			"arifle_Katiba_ACO_pointer_F",
			"launch_RPG32_black_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Katiba_ACO_pointer_F",
			"launch_RPG32_black_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_AT_F: O_Soldier_iran_urban_base_F
	{
        weapons[]=
		{
			"arifle_Katiba_ACO_pointer_F",
			"launch_Titan_short_blk_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Katiba_ACO_pointer_F",
			"launch_Titan_short_blk_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_AAT_F: O_Soldier_iran_urban_base_F
	{
		linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_AA_F: O_Soldier_iran_urban_base_F
	{
        weapons[]=
		{
			"arifle_Katiba_C_ACO_pointer_F",
			"launch_Titan_blk_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_Katiba_C_ACO_pointer_F",
			"launch_Titan_blk_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_AAA_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_TL_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_GL_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_GL_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_SoldierU_SL_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_medic_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_repair_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_exp_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_engineer_U_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_M_F: O_Soldier_iran_urban_base_F
	{
        weapons[]=
		{
			"srifle_DMR_01_black_DMS_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_01_black_DMS_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_A_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_SoldierU_GL_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_GL_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_GL_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_SoldierU_unarmed_F: O_soldierU_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_Urban_HeavyGunner_F: O_Soldier_iran_urban_base_F
	{
        weapons[]=
		{
			"AX_MMG_01_black_ARCO_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_MMG_01_black_ARCO_LP_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_Urban_Sharpshooter_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_CQ_F: O_Soldier_iran_urban_base_F
	{
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_Urban_RadioOperator_F: O_soldierU_F
	{
        uniformClass="Aegis_U_O_LightCombatFatigues_urb_F";
        linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };
    class O_soldierU_CBRN_F: O_soldierU_F
	{
        uniformClass="AX_U_O_CBRN_Suit_01_UHex_F";
		backpack="B_CombinationUnitRespirator_01_F";
		linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"G_AirPurifyingRespirator_02_black_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_alt_uhex_F",
			"AX_H_HelmetPCH_cover_uhex_F",
			"G_AirPurifyingRespirator_02_black_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_urb_F"
		};
    };