	class Atlas_O_Soldier_R_base_F: O_Soldier_F
	{
		editorSubcategory="EdSubcat_Personnel_Reservists";
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_A_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_A_F.jpg";
  	};
  	class Atlas_O_Soldier_R_AR_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_AR_F.jpg";
  	};
  	class Atlas_O_Soldier_R_Medic_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_Medic_F.jpg";
  	  	linkedItems[]=
		{
			"Atlas_V_OCarrierRig_CQB_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_CQB_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Crew_R_F: O_crew_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Crew_R_F.jpg";
		editorSubcategory="EdSubcat_Personnel_Reservists";
  	  	linkedItems[]=
		{
			"V_BandollierB_khk",
			"lxWS_H_tank_tan_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_khk",
			"lxWS_H_tank_tan_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_Engineer_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_Engineer_F.jpg";
  	};
  	class Atlas_O_Soldier_R_Exp_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_Exp_F.jpg";
  	  	linkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_GL_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_GL_F.jpg";
  	 	linkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_HG_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_HG_F.jpg";
  	};
  	class Atlas_O_Soldier_R_M_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_M_F.jpg";
  	};
  	class Atlas_O_Soldier_R_AA_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_AA_F.jpg";
  	};
  	class Atlas_O_Soldier_R_AT_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_AT_F.jpg";
  	};
  	class Atlas_O_Soldier_R_RadioOp_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_RadioOp_F.jpg";
  	};
  	class Atlas_O_Soldier_R_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_F.jpg";
  	};
  	class Atlas_O_Soldier_R_LAT_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_LAT_F.jpg";
  	};
  	class Atlas_O_Soldier_R_SL_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_SL_F.jpg";
  	  	linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_TL_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_TL_F.jpg";
  	  	linkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};
  	class Atlas_O_Soldier_R_UAV_F: Atlas_O_Soldier_R_base_F
  	{
		//editorPreview="\ax_grounded_futura\editor_previews\futura\Atlas_O_Soldier_R_UAV_F.jpg";
  	  	linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_alt_khk_F",
			"AX_H_HelmetPCH_cover_lite_hex_F",
			"NVGoggles_OPFOR",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
  	};