    class O_Soldier_AR_F;
	class O_medic_F;
    class O_crew_F;
	class O_Soldier_GL_F;
	class O_officer_F;
	class O_Soldier_F;
    class O_Soldier_LAT_F;
    class O_helipilot_F;
    class O_Soldier_TL_F;
	class O_soldier_UAV_F;
    class O_A_soldier_base_F: O_officer_F
	{
		uniformClass="AX_U_UniformBDU_01_hex_F";
	};
    class O_A_soldier_A_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_A_F.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
		linkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_soldier_AR_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_AR_F.jpg";
		linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_medic_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_medic_F.jpg";
		linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_crew_F: O_A_soldier_base_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_crew_F.jpg";
		linkedItems[]=
		{
			"H_Tank_black_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Tank_black_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_engineer_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_engineer_F.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
		linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_A_soldier_GL_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_GL_F.jpg";
		linkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_helipilot_F: O_helipilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_helipilot_F.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
	};
    class O_A_helicrew_F: O_A_helipilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_helicrew_F.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
	};
	class O_A_Fighter_Pilot_F: O_A_helipilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_Fighter_Pilot_F.jpg";
		uniformClass="AX_U_O_A_PilotCoveralls";
	};
    class O_A_soldier_M_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_M_F.jpg";
		linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
            "NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
            "NVGoggles_OPFOR"
		};
    };
    class O_A_soldier_AA_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_AA_F.jpg";
		linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_A_soldier_AT_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_AT_F.jpg";
		linkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_A_officer_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_officer_F.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
		weapons[]=
		{
			"hgun_PDW2000_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"hgun_PDW2000_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
	};
    class O_A_soldier_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_F.jpg";
		linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class O_A_RadioOperator_F: O_A_soldier_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_RadioOperator_F.jpg";
        linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_soldier_LAT_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_LAT_F.jpg";
        linkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PASGT_basic_sand_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_soldier_SL_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_SL_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_arco_flash_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_arco_flash_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
        linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_soldier_TL_F: O_A_soldier_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_soldier_TL_F.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_arco_flash_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_arco_flash_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_PASGT_Cover_O_Hex_F",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    
