	class O_A_officer_lxWS: O_officer_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_officer_lxWS.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
        linkedItems[]=
		{
			"H_MilCap_ocamo",
			"V_BandollierB_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_MilCap_ocamo",
			"V_BandollierB_khk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_Soldier_TL_lxWS: O_Soldier_TL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_Soldier_TL_lxWS.jpg";
        uniformClass="AX_U_UniformBDU_01_hex_F";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"30Rnd_580x42_Mag_Tracer_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
        linkedItems[]=
		{
			"H_MilCap_ocamo",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_MilCap_ocamo",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_Soldier_lxWS: O_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_Soldier_lxWS.jpg";
        uniformClass="AX_U_UniformBDU_02_hex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShell"
		};
        linkedItems[]=
		{
			"Aegis_H_Milcap_nohs_ocamo_F",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_H_Milcap_nohs_ocamo_F",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_Soldier_GL_lxWS: O_Soldier_GL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_Soldier_GL_lxWS.jpg";
        uniformClass="AX_U_UniformBDU_01_hex_F";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
        linkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_medic_lxWS: O_medic_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_medic_lxWS.jpg";
        uniformClass="AX_U_UniformBDU_02_hex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
        linkedItems[]=
		{
			"Aegis_H_Milcap_nohs_ocamo_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_H_Milcap_nohs_ocamo_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_crew_lxWS: O_crew_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_crew_lxWS.jpg";
		uniformClass="AX_U_UniformBDU_01_hex_F";
        weapons[]=
		{
			"hgun_PDW2000_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"hgun_PDW2000_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"30Rnd_9x21_Mag",
			"HandGrenade_Guer",
			"HandGrenade_Guer",
			"SmokeShell"
		};
        linkedItems[]=
		{
			"H_HeadSet_black_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_HeadSet_black_F",
			"V_BandollierB_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_A_Soldier_AR_lxWS: O_Soldier_AR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_Soldier_AR_lxWS.jpg";
        uniformClass="AX_U_UniformBDU_01_hex_F";
		weapons[]=
		{
			"arifle_CTARS_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTARS_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
        linkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class O_A_HeavyGunner_lxWS: O_A_Soldier_AR_lxWS
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_HeavyGunner_lxWS.jpg";
        uniformClass="AX_U_UniformBDU_01_hex_F";
		weapons[]=
		{
			"AX_LMG_Zafir_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Zafir_flash_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
        linkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_ChestrigF_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
    class O_A_Soldier_LAT_lxWS: O_Soldier_LAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\tacops\O_A_Soldier_LAT_lxWS.jpg";
		uniformClass="AX_U_UniformBDU_02_hex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_F",
			"launch_RPG32_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_F",
			"launch_RPG32_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"RPG32_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"RPG32_F",
			"SmokeShellYellow",
			"SmokeShellYellow",
			"Chemlight_yellow",
			"Chemlight_yellow"
		};
        linkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_Cap_brn_SPECOPS",
			"V_Chestrig_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
