	class Aegis_arifle_M4A1_base_F: Rifle_Base_F
	{
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			class PointerSlot: JCA_RailSLot_AR
			{
				iconPosition[]={0.34999999,0.44999999};
				iconScale=0.2;
			};
		};
	};
	class Aegis_arifle_M4A1_GL_base_F: Aegis_arifle_M4A1_base_F
	{
		class EGLM;
	};
	class Aegis_arifle_M4A1_Grip_base_F: Aegis_arifle_M4A1_base_F
	{
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\weapons_f_JCA_IA\Rifles\M4A1\data\anim\M4A1_Grip.rtm"
		};
	};
	class Aegis_arifle_M4A1_short_base_F: Aegis_arifle_M4A1_base_F
	{
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\weapons_f_JCA_IA\Rifles\M4A1\data\anim\M4A1_Grip.rtm"
		};
	};
	class Aegis_arifle_M4A1_olive_F: Aegis_arifle_M4A1_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_olive_F";
		picture="\ax_weapons_f_jca_aegis\data\ui\Icon_arifle_M4A1_olive_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_olive_F";
		hiddenSelectionsTextures[]=
		{
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_01_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_02_olive_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_05_black_CO.paa"
		};
	};
	class Aegis_arifle_M4A1_short_olive_F: Aegis_arifle_M4A1_short_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_short_olive_F";
		picture="\weapons_f_JCA_IA\Rifles\M4A1\data\UI\Icon_arifle_M4A1_short_olive_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_short_olive_F";
		hiddenSelectionsTextures[]=
		{
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_01_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_02_olive_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_05_black_CO.paa"
		};
	};
	class Aegis_arifle_M4A1_GL_olive_F: Aegis_arifle_M4A1_GL_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_GL_olive_F";
		picture="\ax_weapons_f_jca_aegis\data\ui\Icon_arifle_M4A1_GL_olive_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_GL_olive_F";
		hiddenSelectionsTextures[]=
		{
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_01_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_02_olive_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_03_black_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_04_black_CO.paa"
		};
	};
	class Aegis_arifle_M4A1_grip_olive_F: Aegis_arifle_M4A1_Grip_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_grip_olive_F";
		picture="\weapons_f_JCA_IA\Rifles\M4A1\data\UI\Icon_arifle_M4A1_olive_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_grip_olive_F";
		hiddenSelectionsTextures[]=
		{
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_01_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_02_olive_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_05_black_CO.paa"
		};
	};
	class Aegis_arifle_M4A1_short2_base_F: Aegis_arifle_M4A1_short_base_F
	{
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\data\anim\M4A1.rtm"
		};
	};
	class Aegis_arifle_M4A1_short2_F: Aegis_arifle_M4A1_short2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_short2_F";
		picture="\A3_Aegis\weapons_f_aegis\Rifles\M4A1\Data\UI\Icon_arifle_M4A1_short_black_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_short2_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_01_black_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_02_black_CO.paa",
			""
		};
	};
	class Aegis_arifle_M4A1_short2_sand_F: Aegis_arifle_M4A1_short2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_short2_sand_F";
		picture="\A3_Aegis\weapons_f_aegis\Rifles\M4A1\Data\UI\Icon_arifle_M4A1_short_sand_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_short2_sand_F";
		magazines[]=
		{
			"30Rnd_556x45_Stanag_Sand"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_01_sand_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_02_sand_CO.paa",
			""
		};
	};
	class Aegis_arifle_M4A1_short2_khaki_F: Aegis_arifle_M4A1_short2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_short2_khaki_F";
		picture="\A3_Aegis\weapons_f_aegis\Rifles\M4A1\Data\UI\Icon_arifle_M4A1_short_khaki_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_short2_khaki_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_01_khaki_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_02_khaki_CO.paa",
			""
		};
	};
	class Aegis_arifle_M4A1_short2_olive_F: Aegis_arifle_M4A1_short2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=1;
		scopeCurator=1;
		scopeArsenal=1;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_short2_olive_F";
		picture="\ax_weapons_f_jca_aegis\data\ui\Icon_arifle_M4A1_short_olive_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_short2_olive_F";
		hiddenSelectionsTextures[]=
		{
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_01_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_02_olive_CO.paa",
			""
		};
	};
	class Aegis_arifle_M4A1_GL2_base_F: Aegis_arifle_M4A1_GL_base_F
	{
		model="weapons_f_JCA_IA\Rifles\M4A1\M4A1_GL_F.p3d";
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\weapons_f_JCA_IA\Rifles\M4A1\data\anim\M4A1_GL.rtm"
		};
		reloadAction="JCA_GestureReloadM4A1_GL_Magazine";
		class EGLM: EGLM
		{
			displayName="UGL";
			reloadAction="JCA_GestureReloadM4A1_GL_Shell";
			reloadMagazineSound[]=
			{
				"sounds_f_JCA_IA\arsenal\weapons\Rifles\M4A1\GrenadeLauncher\M4A1_GL_reload",
				1,
				1,
				10
			};
		};
	};
	class Aegis_arifle_M4A1_GL2_F: Aegis_arifle_M4A1_GL2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_GL2_F";
		picture="\weapons_f_JCA_IA\Rifles\M4A1\data\UI\Icon_arifle_M4A1_GL_black_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_GL2_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_01_black_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_02_black_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_03_black_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_04_black_CO.paa"
		};
	};
	class Aegis_arifle_M4A1_GL2_sand_F: Aegis_arifle_M4A1_GL2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_GL2_sand_F";
		picture="\weapons_f_JCA_IA\Rifles\M4A1\data\UI\Icon_arifle_M4A1_GL_sand_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_GL2_sand_F";
		magazines[]=
		{
			"30Rnd_556x45_Stanag_Sand"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_01_sand_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_02_sand_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_03_sand_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_04_black_CO.paa"
		};
	};
	class Aegis_arifle_M4A1_GL2_khaki_F: Aegis_arifle_M4A1_GL2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_GL2_khaki_F";
		picture="\weapons_f_JCA_IA\Rifles\M4A1\data\UI\Icon_arifle_M4A1_GL_olive_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_GL2_khaki_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_01_khaki_CO.paa",
			"\A3_Aegis\Weapons_F_Aegis\Rifles\M4A1\Data\arifle_M4A1_02_khaki_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_03_black_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_04_black_CO.paa"
		};
	};
	class Aegis_arifle_M4A1_GL2_olive_F: Aegis_arifle_M4A1_GL2_base_F
	{
		author="$STR_A3_A_Grave_3dGunsmith";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		weaponpoolavailable=1;
		displayName="$STR_A3_AX_arifle_M4A1_GL2_olive_F";
		picture="\weapons_f_JCA_IA\Rifles\M4A1\data\UI\Icon_arifle_M4A1_GL_olive_F_CA.paa";
		baseWeapon="Aegis_arifle_M4A1_GL2_olive_F";
		hiddenSelectionsTextures[]=
		{
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_01_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_02_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_03_olive_CO.paa",
			"\weapons_f_JCA_IA\Rifles\M4A1\Data\arifle_M4A1_04_black_CO.paa"
		};
	};