	class None_RU: None
	{
		identityTypes[]=
		{
			"G_CHINA_default",
			300,
			"G_CHINA_officer",
			500
		};
	};
	class AX_G_Aviator_cn: G_Aviator
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_CHINA_officer",
			400
		};
	};
	class AX_G_Headset_light_cn: G_Headset_light
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_CHINA_officer",
			400
		};
	};
	class AX_G_Shades_blk_cn: G_Shades_Black
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_CHINA_default",
			50
		};
	};
	class AX_G_Sport_blk: G_Sport_Checkered
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayname="$STR_A3_GRFU_G_Sport_Black_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\facewear\data\sunglasses_sport_black_ca.paa"
		};
		identityTypes[]=
		{
			"G_CHINA_default",
			50
		};
	};
	class AX_G_Squares_cn: G_Squares
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_AX_G_Squares_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\facewear\data\G_Square_Spectacles_CO.paa"
		};
		identityTypes[]=
		{
			"G_CHINA_default",
			50
		};
	};
	class AX_G_Spectacles_Tint_cn: G_Spectacles_Tinted
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]={};
	};
	class AX_G_Goggles_blk_cn: JAM_AE_PLA_G_Goggles_blk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Goggles_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\facewear\data\ui\icon_G_Goggles_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\facewear\data\goggles_pla_ca.paa"
		};
		identityTypes[]=
		{
			"G_CHINA_default",
			50
		};
	};
	class AX_G_Balaclava_blk_cn: JAM_AE_PLA_G_Balaclava_blk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Balaclava_Goggles_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\facewear\data\ui\icon_G_Balaclava_blk_F_ca.paa";
		identityTypes[]={};
	};
	class AX_G_Balaclava_Goggles_blk_cn: JAM_AE_PLA_G_Balaclava_Goggles_blk
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Balaclava_Goggles_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\facewear\data\ui\icon_G_Balaclava_Goggles_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\mask_balaclava_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\facewear\data\goggles_pla_ca.paa"
		};
		identityTypes[]={};
	};
	class AX_G_Headset_blk_cn: None
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Headset_blk_F0";
		model="\JAM_AE\jam_characters_cn_ae\Headgear\headset_pla.p3d";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Headset_pla_blk_ca.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
		identityTypes[]={};
		mass=8;
	};
	class AX_G_Headset_oli_cn: AX_G_Headset_blk_cn
	{
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Headset_oli_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Headset_pla_oli_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_oli_CO.paa"
		};
	};