    class AX_O_CBRN_Man_Oversuit_01_GHex_F: B_CBRN_Man_Oversuit_01_MTP_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CBRN_Suit_01_GHex_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_GHex_CO.paa"
		};
	};
	class AX_O_CBRN_Man_Oversuit_01_DHex_F: B_CBRN_Man_Oversuit_01_MTP_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CBRN_Suit_01_DHex_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_DHex_CO.paa"
		};
	};
	class AX_O_CBRN_Man_Oversuit_01_MHex_F: B_CBRN_Man_Oversuit_01_MTP_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CBRN_Suit_01_MHex_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_MHex_CO.paa"
		};
	};
	class AX_O_CBRN_Man_Oversuit_01_VHex_F: B_CBRN_Man_Oversuit_01_MTP_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CBRN_Suit_01_VHex_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_VHex_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_hex_01_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_O_CombatUniform_T21_T07_hex_01_F";
		model="\ax_grounded_futura\characters_f_china\uniforms\U_Uniform_T21_T07_01.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform.rvmat",
				"A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_injury.rvmat",
				"A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
    };
	class AX_uniform_O_CombatUniform_T21_T07_ghex_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_ghex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_dhex_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_dhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_dst_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_khk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_sahex_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_sahex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_semiarid_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_mhex_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_whex_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_whex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_vhex_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_vhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_vhex_vz_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_vhex_vz_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_vhex_vz_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_mhex_blk_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_blk_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_blk_mhex_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_blk_mhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_blk_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_blk_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_oli_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_oli_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_khk_01_F: AX_uniform_O_CombatUniform_T21_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_khk_01_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_khk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_hex_02_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_O_CombatUniform_T21_T07_hex_02_F";
		model="\ax_grounded_futura\characters_f_china\uniforms\U_Uniform_T21_T07_02.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform.rvmat",
				"A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_injury.rvmat",
				"A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_O_CombatUniform_T21_T07_ghex_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_ghex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_dhex_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_dhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_dst_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_khk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_sahex_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_sahex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_semiarid_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_mhex_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_whex_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_whex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_vhex_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_vhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_vhex_vz_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_vhex_vz_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_vhex_vz_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_mhex_blk_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_blk_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\OCombatUniform_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_blk_mhex_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_blk_mhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_blk_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_blk_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\OCombatUniform_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_oli_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_oli_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T21_T07_khk_02_F: AX_uniform_O_CombatUniform_T21_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T21_T07_khk_02_F";
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\OCombatUniform_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\uniforms\data\CNGloves_khk_CO.paa"
		};
	};
	class AX_uniform_O_Uniform_T07_hex_01_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_O_Uniform_T07_hex_01_F";
		model="\JAM_AE\jam_characters_cn_ae\Uniforms\unif_type07.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_hex_CO.paa",
			""
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_O_Uniform_T07_ghex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_ghex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_ghex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_dhex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_dhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_dhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_sahex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_sahex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_sahex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_mhex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_mhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_whex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_whex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_whex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_vhex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_vhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_oli_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_oli_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_oli2_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_blk_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_blk_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk2_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_khk_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_khk_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_khk_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_hex_02_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_O_Uniform_T07_hex_02_F";
		model="\JAM_AE\jam_characters_cn_ae\Uniforms\unif_type07_roll.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_hex_CO.paa",
			""
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_O_Uniform_T07_ghex_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_ghex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_ghex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_dhex_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_dhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_dhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_sahex_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_sahex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_sahex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_mhex_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_mhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_whex_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_whex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_whex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_vhex_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_vhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_oli_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_oli_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_oli2_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_blk_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_blk_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk2_CO.paa",
			""
		};
	};
	class AX_uniform_O_Uniform_T07_khk_02_F: AX_uniform_O_Uniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_Uniform_T07_khk_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_khk_CO.paa",
			""
		};
	};
	class AX_uniform_O_CombatUniform_T07_hex_01_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_O_CombatUniform_T07_hex_01_F";
		model="\JAM_AE\jam_characters_cn_ae\Uniforms\unif_type07_cmbt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_hex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_O_CombatUniform_T07_ghex_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_ghex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_ghex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_dhex_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_dhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_dhex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_khk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_sahex_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_sahex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_sahex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_mhex_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_mhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_whex_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_whex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_whex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_vhex_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_vhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_oli_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_oli_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_oli2_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_blk_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_blk_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk2_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_khk_01_F: AX_uniform_O_CombatUniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_khk_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_khk_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_khk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_hex_02_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_O_CombatUniform_T07_hex_02_F";
		model="\JAM_AE\jam_characters_cn_ae\Uniforms\unif_type07_roll_cmbt.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_hex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"ax_grounded_futura\characters_f_china\uniforms\data\unif_type07_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
	};
	class AX_uniform_O_CombatUniform_T07_ghex_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_ghex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_ghex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_dhex_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_dhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_dhex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_khk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_sahex_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_sahex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_sahex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_mhex_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_mhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_mhex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_whex_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_whex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_whex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_vhex_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_vhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_vhex_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_oli_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_oli_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_oli2_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_grn_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_blk_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_blk_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_blk2_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_blk_CO.paa"
		};
	};
	class AX_uniform_O_CombatUniform_T07_khk_02_F: AX_uniform_O_CombatUniform_T07_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_CombatUniform_T07_khk_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_khk_CO.paa",
			"",
			"\ax_grounded_futura\characters_f_china\uniforms\data\Tac_khk_CO.paa"
		};
	};
	class AX_uniform_O_OfficerUniform_T07_hex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_hex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_hex_CO.paa",
			""
		};
	};
	class AX_uniform_O_OfficerUniform_T07_ghex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_ghex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_ghex_CO.paa",
			""
		};
	};
	class AX_uniform_O_OfficerUniform_T07_dhex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_dhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_dhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_OfficerUniform_T07_sahex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_sahex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_sahex_CO.paa",
			""
		};
	};
	class AX_uniform_O_OfficerUniform_T07_mhex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_mhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_mhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_OfficerUniform_T07_whex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_whex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_whex_CO.paa",
			""
		};
	};
	class AX_uniform_O_OfficerUniform_T07_vhex_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_vhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_vhex_CO.paa",
			""
		};
	};
	class AX_uniform_O_OfficerUniform_T07_vhex_vz_01_F: AX_uniform_O_Uniform_T07_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_O_OfficerUniform_T07_vhex_vz_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\U_UniformType07_officer_vhex_vz_CO.paa",
			""
		};
	};
