	class AX_H_HelmetO_ghex_F: H_HelmetO_ghex_F
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_china\headgear\data\tech.rvmat"
		};
	};
	class AX_H_HelmetO_dhex_F: H_HelmetO_oicamo
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_china\headgear\data\tech.rvmat"
		};
	};
	class AX_H_HelmetAggressor_ghex_F: H_HelmetAggressor_base_F
	{
		scope=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_H_HelmetAggressor_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\headgear\data\ui\icon_H_HelmetAggressor_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\headgear\data\H_HelmetAggressor_01_GHex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_dhex_F: H_HelmetAggressor_base_F
	{
		scope=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_H_HelmetAggressor_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\headgear\data\ui\icon_H_HelmetAggressor_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\headgear\data\H_HelmetAggressor_01_DHex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_cover_ghex_F: H_HelmetAggressor_cover_base_F
	{
		scope=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_H_HelmetAggressor_cover_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\headgear\data\ui\icon_H_HelmetAggressor_cover_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\headgear\data\H_HelmetAggressor_01_GHex_CO.paa"
		};
	};
	class AX_H_HelmetAggressor_cover_dhex_F: H_HelmetAggressor_cover_base_F
	{
		scope=1;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_H_HelmetAggressor_cover_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\headgear\data\ui\icon_H_HelmetAggressor_cover_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\headgear\data\H_HelmetAggressor_01_DHex_CO.paa"
		};
	};
//Drop sat to 0.9
    class AX_H_FieldCap_t07_hex_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_hex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_hex_CO.paa"
		};
	};
    class AX_H_FieldCap_t07_ghex_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_ghex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_ghex_CO.paa"
		};
	};
    class AX_H_FieldCap_t07_dhex_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_dhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_dhex_CO.paa"
		};
	};
    class AX_H_FieldCap_t07_sahex_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_sahex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_sahex_CO.paa"
		};
	};
    class AX_H_FieldCap_t07_mhex_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_mhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_mhex_CO.paa"
		};
	};
	class AX_H_FieldCap_t07_whex_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_whex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_whex_CO.paa"
		};
	};
	class AX_H_FieldCap_t07_vhex_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_vhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_vhex_CO.paa"
		};
	};
	class AX_H_FieldCap_t07_oli_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_grn_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_oli_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_oli_CO.paa"
		};
	};
	class AX_H_FieldCap_t07_blk_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_blk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_blk_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_blk_CO.paa"
		};
	};
	class AX_H_FieldCap_t07_khk_01_F: JAM_AE_H_PLA_Cap_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_khk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_khk_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_khk_CO.paa"
		};
	};
    class AX_H_FieldCap_t07_hex_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_hex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_hex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_hex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
    class AX_H_FieldCap_t07_ghex_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_ghex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_ghex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_ghex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
    class AX_H_FieldCap_t07_dhex_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_dhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_dhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_dhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
    class AX_H_FieldCap_t07_sahex_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_sahex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_sahex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_sahex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_FieldCap_t07_mhex_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_mhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_mhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_FieldCap_t07_whex_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_whex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_whex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_whex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_FieldCap_t07_vhex_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_vhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_vhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_vhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_FieldCap_t07_oli_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_grn_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_oli_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_oli_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_FieldCap_t07_blk_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_blk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_blk_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_FieldCap_t07_khk_02_F: JAM_AE_H_PLA_Cap_t07_goggles
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_FieldCap_khk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_FieldCap_t07_khk_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Cap_T07_khk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Booniehat_t07_hex_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_hex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_hex_CO.paa"
		};
	};
    class AX_H_Booniehat_t07_ghex_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_ghex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_ghex_CO.paa"
		};
	};
    class AX_H_Booniehat_t07_dhex_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_dhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_dhex_CO.paa"
		};
	};
    class AX_H_Booniehat_t07_sahex_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_sahex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_sahex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_mhex_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_mhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_mhex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_whex_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_whex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_whex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_vhex_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_vhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_vhex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_oli_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_grn_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_oli_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_oli_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_blk_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_blk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_blk_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_blk_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_khk_01_F: JAM_AE_H_PLA_Boonie_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_khk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_khk_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_khk_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_un_01_F: JAM_AE_H_PLA_Boonie_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_un_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_un_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_un_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_hex_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_hex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_hex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_hex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_ghex_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_ghex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_ghex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_ghex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_dhex_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_dhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_dhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_dhex_CO.paa"
		};
	};
    class AX_H_Booniehat_t07_sahex_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_sahex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_sahex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_sahex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_mhex_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_mhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_mhex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_whex_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_whex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_whex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_whex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_vhex_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_vhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_vhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_vhex_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_oli_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_grn_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_oli_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_oli_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_blk_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_blk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_blk_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_blk_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_khk_02_F: JAM_AE_H_PLA_Boonie_Folded_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_khk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_khk_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_khk_CO.paa"
		};
	};
	class AX_H_Booniehat_t07_un_02_F: JAM_AE_H_PLA_Boonie_Folded_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Boonie_un_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Booniehat_t07_un_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Boonie_T07_un_CO.paa"
		};
	};
	class AX_H_Beret_csat_red_F: JAM_AE_H_PLA_Beret_red
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Beret_CSAT_red_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Beret_csat_red_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Beret_csat_red_CO.paa"
		};
    };
    class AX_H_Beret_csat_grn_F: JAM_AE_H_PLA_Beret_red
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Beret_CSAT_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Beret_csat_grn_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Beret_csat_grn_CO.paa"
		};
    };
	class AX_H_Beret_csat_un_F: JAM_AE_H_PLA_Beret_red
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Beret_PLA_un_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Beret_pla_un_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_Beret_pla_un_CO.paa"
		};
	};
	class JAM_AE_H_PLA_Headset_blk: HelmetBase
	{
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Headset_pla_blk_ca.paa";
	};
	class JAM_AE_H_PLA_Headset_oli: JAM_AE_H_PLA_Headset_blk
	{
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Headset_pla_oli_ca.paa";
	};
	class JAM_AE_H_PLA_QGF03_oli: HelmetBase
	{
	};
	class AX_H_Helmet_QGF03_oli: JAM_AE_H_PLA_QGF03_oli
	{
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_oli_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_blk: JAM_AE_H_PLA_QGF03_oli
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_blk_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_khk: JAM_AE_H_PLA_QGF03_oli
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_khk_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_khk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hex_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_hex_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_ghex_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_ghex_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_dhex_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_dhex_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_sahex_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_sahex_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_mhex_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_mhex_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_whex_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_whex_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_vhex_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_vhex_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_un_F: JAM_AE_H_PLA_QGF03_Cover_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_cover_un_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_PLA_QGF03_Cover_un_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_un_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_hex_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_dhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\helmet_qgf03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_hex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_ghex_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_ghex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\helmet_qgf03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_ghex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_dhex_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_dhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\helmet_qgf03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_dhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_sahex_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_sahex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\helmet_qgf03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_sahex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_mhex_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_mhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\helmet_qgf03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_mhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_whex_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_whex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\helmet_qgf03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_whex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_vhex_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_vhex_01_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\helmet_qgf03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_vhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_un_01_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_01_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_un_01_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_PLA_QGF03_Cover_Glasses_01_un_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_un_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_un_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_hex_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_hex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_hex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_hex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_ghex_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_ghex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_ghex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_ghex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_dhex_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_dhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_dhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_dhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_sahex_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_sahex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_sahex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_sahex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_mhex_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_mhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_mhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_whex_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_whex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_whex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_whex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_vhex_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_vhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_goggles_vhex_02_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_vhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_blk_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_goggles_un_02_F: JAM_AE_H_PLA_QGF03_Cover_Glasses_02_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_goggles_un_02_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_PLA_QGF03_Cover_Glasses_02_un_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_un_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_oli_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Facewear\Data\goggles_pla_CA.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_hex_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_hex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_ghex_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_ghex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_dhex_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_dhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_sahex_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_sahex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_mhex_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_mhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_whex_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_whex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_vhex_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_vhex_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};
	class AX_H_Helmet_QGF03_Cover_hs_un_F: JAM_AE_H_PLA_QGF03_Cover_HS_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_H_Helmet_qgf03_hs_un_F0";
		picture="\ax_grounded_futura\characters_f_china\Headgear\data\ui\icon_H_Helmet_QGF03_Cover_hs_un_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\Headgear\data\H_HelmetQGF03_cover_un_CO.paa",
			"\JAM_AE\jam_characters_cn_ae\Headgear\Data\headset_pla_blk_CO.paa"
		};
	};