    class AX_U_O_CBRN_Suit_01_GHex_F: Uniform_Base
	{
		scope=2;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_U_O_CBRN_Suit_01_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CBRN_Suit_01_GHex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_GHex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_GHex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_CBRN_Suit_01_DHex_F: Uniform_Base
	{
		scope=2;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_U_O_CBRN_Suit_01_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CBRN_Suit_01_DHex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_DHex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_DHex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_CBRN_Suit_01_MHex_F: Uniform_Base
	{
		scope=2;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_U_O_CBRN_Suit_01_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CBRN_Suit_01_MHex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_MHex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_MHex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_CBRN_Suit_01_VHex_F: Uniform_Base
	{
		scope=2;
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_U_O_CBRN_Suit_01_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CBRN_Suit_01_VHex_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_original_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\uniforms\data\CBRN_Suit_01_MHex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_O_CBRN_Man_Oversuit_01_VHex_F";
			containerClass="Supply30";
			mass=45;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_hex_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_hex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_hex_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
    class AX_U_O_CombatUniform_T21_T07_ghex_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_ghex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_ghex_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_dhex_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_dhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_dhex_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
    class AX_U_O_CombatUniform_T21_T07_sahex_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_sahex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_sahex_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_mhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_mhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_mhex_01_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_whex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_whex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_whex_01_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_mhex_blk_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_mhex_blk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_mhex_blk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_mhex_blk_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_blk_mhex_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_blk_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_mhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_blk_mhex_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_vhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_vhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_vhex_01_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_vhex_vz_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_vhex_vz_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_vhex_vz_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_vhex_vz_01_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_blk_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_blk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_blk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_blk_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_blk_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_oli_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_oli_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_oli_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_oli_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_khk_01_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_khk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_khk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_khk_01_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_hex_02_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_hex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_hex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_hex_02_F";
			containerClass="Supply40";
			mass=60;
		};
    };
    class AX_U_O_CombatUniform_T21_T07_ghex_02_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_ghex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_ghex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_ghex_02_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_dhex_02_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_dhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_dhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_dhex_02_F";
			containerClass="Supply40";
			mass=60;
		};
    };
    class AX_U_O_CombatUniform_T21_T07_sahex_02_F: Uniform_Base
	{
        author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_sahex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_sahex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_sahex_02_F";
			containerClass="Supply40";
			mass=60;
		};
    };
	class AX_U_O_CombatUniform_T21_T07_mhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_mhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_mhex_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_whex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_whex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_whex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_whex_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_mhex_blk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_mhex_blk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_mhex_blk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_mhex_blk_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_blk_mhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_blk_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_blk_mhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_blk_mhex_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_vhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_vhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_vhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_vhex_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_vhex_vz_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_vhex_vz_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_vhex_vz_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_vhex_vz_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_blk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_blk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_blk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_blk_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_blk_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_oli_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_oli_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_oli_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_oli_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_CombatUniform_T21_T07_khk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T21_T07_khk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T21_T07_khk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T21_T07_khk_02_F";
			containerClass="Supply40";
			mass=60;
		};
	};
	class AX_U_O_Uniform_T07_hex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_hex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_hex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_ghex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_ghex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_ghex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_dhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_dhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_dhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_sahex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_sahex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_sahex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_mhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_mhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_mhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_whex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_whex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_whex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_vhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_vhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_vhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_oli_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_grn_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_oli_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_oli_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_blk_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_blk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_blk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_blk_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_blk_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_khk_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_khk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_khk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_khk_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_hex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_hex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_hex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_hex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_ghex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_ghex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_ghex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_ghex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_dhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_dhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_dhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_dhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_sahex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_sahex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_sahex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_sahex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_mhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_mhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_mhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_whex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_whex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_whex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_whex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_vhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_vhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_vhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_vhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_oli_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_grn_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_oli_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_oli_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_blk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_blk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_blk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_blk_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_Uniform_T07_khk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_Uniform_T07_khk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_Uniform_T07_khk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_Uniform_T07_khk_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_hex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_hex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_hex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_ghex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_ghex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_ghex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_dhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_dhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_dhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_sahex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_sahex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_sahex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_mhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_mhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_mhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_whex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_whex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_whex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_vhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_vhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_vhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_oli_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_grn_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_oli_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_oli_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_blk_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_blk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_blk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_blk_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_khk_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_khk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_khk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_khk_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_hex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_hex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_hex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_hex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_ghex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_ghex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_ghex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_ghex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_dhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_dhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_dhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_dhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_sahex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_sahex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_sahex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_sahex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_mhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_mhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_mhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_whex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_whex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_whex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_whex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_vhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_vhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_vhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_vhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_oli_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_grn_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_oli_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_oli_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_blk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_blk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_blk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_blk_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_CombatUniform_T07_khk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_CombatUniform_T07_khk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_CombatUniform_T07_khk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_CombatUniform_T07_khk_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_hex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_hex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_hex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_ghex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_ghex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_ghex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_dhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_dhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_dhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_sahex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_sahex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_sahex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_mhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_mhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_mhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_whex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_whex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_whex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_vhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_vhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_vhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_OfficerUniform_T07_vhex_vz_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_OfficerUniform_T07_vhex_vz_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_OfficerUniform_T07_vhex_vz_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_OfficerUniform_T07_vhex_vz_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_hex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_hex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_hex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_hex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_ghex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_ghex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_ghex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_ghex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_dhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_dhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_dhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_dhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_sahex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_sahex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_sahex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_sahex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_mhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_mhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_mhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_mhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_whex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_whex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_whex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_whex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_vhex_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_vhex_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_vhex_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_vhex_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_vhex_vz_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_vhex_vz_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_vhex_vz_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_vhex_vz_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_oli_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_grn_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_oli_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_oli_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_blk_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_blk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_blk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_blk_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_khk_01_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_khk_01_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_khk_01_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_khk_01_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_hex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_hex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_hex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_hex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_ghex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_ghex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_ghex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\OPFOR\Data\clothing_tna_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_ghex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_dhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_dhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_dhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Aegis\Characters_F_Aegis\Uniforms\Data\clothing_oicamo_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_dhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_sahex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_sahex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_sahex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_tka_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_sahex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_mhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_mhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_mhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_mhex_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_mhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_whex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_whex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_whex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_whex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_vhex_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_vhex_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_vhex_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_vhex_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_vhex_vz_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_vhex_vz_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_vhex_vz_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Uniforms\Data\clothing_wdl_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_vhex_vz_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_oli_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_grn_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_oli_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_oli_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_blk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_blk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_blk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_blk_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
	class AX_U_O_ParkaUniform_T03_khk_02_F: Uniform_Base
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_U_O_ParkaUniform_T03_khk_02_F0";
		picture="\ax_grounded_futura\characters_f_china\uniforms\data\ui\icon_U_O_ParkaUniform_T03_khk_02_F_ca.paa";
		model="\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Suitpacks\Data\suitpack_soldier_OPFOR_CO.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="AX_uniform_O_ParkaUniform_T03_khk_02_F";
			containerClass="Supply40";
			mass=40;
		};
	};
