    class Atlas_V_ORigLBV_GHex_F: Atlas_V_ORigLBV_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_ghex_CO.paa"
		};
	};
	class AX_V_ORigLBV_MHex_F: Atlas_V_ORigLBV_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_ORigLBV_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_ORigLBV_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_mhex_CO.paa"
		};
	};
	class AX_V_ORigLBV_VHex_F: Atlas_V_ORigLBV_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_ORigLBV_VHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_ORigLBV_VHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_vhex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_CQB_GHex_F: Atlas_V_OCarrierRig_CQB_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_ghex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_GL_GHex_F: Atlas_V_OCarrierRig_GL_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_ghex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_Lite_gHex_F: Atlas_V_OCarrierRig_Lite_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_ghex_CO.paa"
		};
	};
/*
	class Atlas_V_OCarrierRig_whex_F: Atlas_V_OCarrierRig_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_whex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_CQB_WHex_F: Atlas_V_OCarrierRig_CQB_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_whex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_GL_whex_F: Atlas_V_OCarrierRig_GL_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_whex_CO.paa"
		};
	};
	class Atlas_V_OCarrierRig_Lite_whex_F: Atlas_V_OCarrierRig_Lite_Hex_F
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_whex_CO.paa"
		};
	};
*/
	class AX_V_OCarrierRig_CQB_MHex_F: Atlas_V_OCarrierRig_CQB_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_CQB_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_CQB_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_mhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_CQB_VHex_F: Atlas_V_OCarrierRig_CQB_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_CQB_VHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_CQB_VHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_vhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_CQB_MHex_blk_F: Atlas_V_OCarrierRig_CQB_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_V_OCarrierRig_CQB_MHex_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_CQB_MHex_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_mhex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\ORigLBV_blk_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_blk_CO.paa"
		};
	};
	class AX_V_OCarrierRig_CQB_blk_MHex_F: Atlas_V_OCarrierRig_CQB_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_V_OCarrierRig_CQB_blk_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_CQB_blk_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_mhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_MHex_F: Atlas_V_OCarrierRig_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_mhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_VHex_F: Atlas_V_OCarrierRig_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_VHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_VHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_vhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_GL_MHex_F: Atlas_V_OCarrierRig_GL_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_GL_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_GL_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_mhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_GL_VHex_F: Atlas_V_OCarrierRig_GL_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_GL_VHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_GL_VHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_vhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_GL_MHex_blk_F: Atlas_V_OCarrierRig_GL_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_V_OCarrierRig_GL_MHex_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_GL_MHex_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_mhex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\ORigLBV_blk_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_GL_blk_CO.paa"
		};
	};
	class AX_V_OCarrierRig_GL_blk_MHex_F: Atlas_V_OCarrierRig_GL_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_V_OCarrierRig_GL_blk_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_GL_blk_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_GL_mhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_Lite_MHex_F: Atlas_V_OCarrierRig_Lite_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_Lite_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_Lite_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_mhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_Lite_VHex_F: Atlas_V_OCarrierRig_Lite_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_OCarrierRig_Lite_VHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_Lite_VHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_vhex_CO.paa"
		};
	};
	class AX_V_OCarrierRig_Lite_MHex_blk_F: Atlas_V_OCarrierRig_Lite_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_V_OCarrierRig_Lite_MHex_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_Lite_MHex_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\OCarrierRig_mhex_CO.paa",
			"\A3_Atlas\Characters_F_Atlas\Vests\data\ORigLBV_blk_CO.paa"
		};
	};
	class AX_V_OCarrierRig_Lite_blk_MHex_F: Atlas_V_OCarrierRig_Lite_Hex_F
	{
		author="$STR_A3_GRFU_Axle";
		scope=1;
		scopeArsenal=1;
		displayName="$STR_A3_GRFU_V_OCarrierRig_Lite_blk_MHex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_OCarrierRig_Lite_blk_MHex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3_Atlas\Characters_F_Atlas\Vests\data\OCarrierRig_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\ORigLBV_mhex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_hex_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_hex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_ghex_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_ghex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_dhex_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_dhex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_sahex_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_mhex_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_mhex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_whex_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_whex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_vhex_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_oli_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_oli_CO.paa"
		};
	};
    class AX_V_Vest_t04b_blk_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_blk_CO.paa"
		};
	};
    class AX_V_Vest_t04b_khk_F: JAM_AE_V_PLA_Vest_Type04B_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_khk_CO.paa"
		};
	};
    class AX_V_Vest_t04b_lite_hex_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_hex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_lite_ghex_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_ghex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_lite_dhex_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_dhex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_lite_sahex_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_lite_mhex_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_mhex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_lite_whex_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_whex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_lite_vhex_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_lite_oli_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_oli_CO.paa"
		};
	};
    class AX_V_Vest_t04b_lite_blk_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_blk_CO.paa"
		};
	};
    class AX_V_Vest_t04b_lite_khk_F: JAM_AE_V_PLA_Vest_Type04B_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_lite_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_lite_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_khk_CO.paa"
		};
	};
    class AX_V_Vest_t04b_cqb_hex_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_hex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_cqb_ghex_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_ghex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_cqb_dhex_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_dhex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_cqb_sahex_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_cqb_mhex_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_mhex_CO.paa"
		};
	};
    class AX_V_Vest_t04b_cqb_whex_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_whex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_cqb_vhex_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t04b_cqb_oli_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_oli_CO.paa"
		};
	};
    class AX_V_Vest_t04b_cqb_blk_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_blk_CO.paa"
		};
	};
    class AX_V_Vest_t04b_cqb_khk_F: JAM_AE_V_PLA_Vest_Type04B_Pads_Rifle_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t04b_cqb_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t04b_cqb_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type04b_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_khk_CO.paa"
		};
	};
	class AX_V_Vest_t06_hex_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_hex_CO.paa"
		};
	};
	class AX_V_Vest_t06_ghex_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_ghex_CO.paa"
		};
	};
	class AX_V_Vest_t06_dhex_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_dhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_sahex_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mhex_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_mhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_whex_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_whex_CO.paa"
		};
	};
	class AX_V_Vest_t06_vhex_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_oli_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_oli_CO.paa"
		};
	};
	class AX_V_Vest_t06_blk_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_blk_CO.paa"
		};
	};
	class AX_V_Vest_t06_khk_F: JAM_AE_V_PLA_Vest_Type06_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_khk_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_hex_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_hex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_ghex_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_ghex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_dhex_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_dhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_sahex_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_mhex_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_mhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_whex_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_whex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_vhex_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_oli_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_oli_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_blk_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_blk_CO.paa"
		};
	};
	class AX_V_Vest_t06_lite_khk_F: JAM_AE_V_PLA_Vest_Type06_Rifle_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lite_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lite_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_khk_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_hex_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_hex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_ghex_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_ghex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_dhex_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_dhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_sahex_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_mhex_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_mhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_whex_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_whex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_vhex_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_oli_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_oli_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_blk_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_blk_CO.paa"
		};
	};
	class AX_V_Vest_t06_mg_khk_F: JAM_AE_V_PLA_Vest_Type06_MGun_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_mg_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_mg_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_khk_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_hex_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_hex_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_ghex_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_ghex_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_dhex_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_dhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_sahex_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_mhex_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_mhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_whex_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_whex_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_vhex_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_oli_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_oli_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_blk_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_blk_CO.paa"
		};
	};
	class AX_V_Vest_t06_spec_khk_F: JAM_AE_V_PLA_Vest_Type06_Spec_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_spec_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_spec_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_khk_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_hex_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_hex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_hex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_ghex_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_ghex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_ghex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_dhex_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_dhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_dhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_sahex_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_sahex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_sahex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_mhex_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_mhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_mhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_whex_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_whex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_whex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_vhex_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		scopeArsenal=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_vhex_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_vhex_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_oli_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_oli_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_oli_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_blk_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_blk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_blk_CO.paa"
		};
	};
	class AX_V_Vest_t06_lead_khk_F: JAM_AE_V_PLA_Vest_Type06_Leader_t07
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_Vest_t06_lead_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_Vest_t06_lead_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06_khk_CO.paa",
			"\ax_grounded_futura\characters_f_china\vests\data\V_type06pouches_khk_CO.paa"
		};
	};
	class AX_V_LBV_t95_hex_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_hex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_hex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_hex_CO.paa"
		};
	};
	class AX_V_LBV_t95_ghex_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_ghex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_ghex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_ghex_CO.paa"
		};
	};
	class AX_V_LBV_t95_dhex_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_dhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_dhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_dhex_CO.paa"
		};
	};
	class AX_V_LBV_t95_sahex_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_sahex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_sahex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_sahex_CO.paa"
		};
	};
	class AX_V_LBV_t95_mhex_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_mhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_mhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_mhex_CO.paa"
		};
	};
	class AX_V_LBV_t95_whex_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_whex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_whex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_whex_CO.paa"
		};
	};
	class AX_V_LBV_t95_vhex_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_vhex_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_vhex_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_vhex_CO.paa"
		};
	};
	class AX_V_LBV_t95_oli_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_grn_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_oli_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_oli_CO.paa"
		};
	};
	class AX_V_LBV_t95_blk_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_blk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_blk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_blk_CO.paa"
		};
	};
	class AX_V_LBV_t95_khk_F: JAM_AE_V_PLA_LBV_Type95_t99
	{
		author="$STR_A3_GRFU_Axle";
		scope=2;
		displayName="$STR_A3_GRFU_V_LBV_t95_khk_F0";
		picture="\ax_grounded_futura\characters_f_china\vests\data\ui\icon_V_LBV_t95_khk_F_ca.paa";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_china\vests\data\V_type95pouches_khk_CO.paa"
		};
	};