class cfgPatches
{
	class ax_faction_altis_grfu_rf
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"RF_Data_Loadorder",
			"A3_Atlas_Data_F_Atlas_Loadorder"
		};
		author="Axle";
		skipwhenmissingdependencies=1;
	};
};

class cfgWeapons
{
	class H_HelmetIA;
	class H_HelmetIA_sb_digital_RF: H_HelmetIA
	{
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_altis\headgear\data\headgear_helmet_canvas_co.paa",
			"\lxrf\characters_rf\headgear\data\mitznefet_digital_co.paa"
		};
	};
};

class cfgVehicles
{
	class Atlas_I_Pathfinder_base_F;
	class I_support_CMort_RF;
	class Atlas_I_Pathfinder_AR_F: Atlas_I_Pathfinder_base_F
	{
		uniformClass="AX_U_I_CombatUniform_jacket_02_gloves_grn_F";
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Watchcap_camo_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Watchcap_camo_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_Exp_F: Atlas_I_Pathfinder_base_F
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Bandanna_khk_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Bandanna_khk_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_GL_F: Atlas_I_Pathfinder_base_F
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Watchcap_camo_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Watchcap_camo_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_M_F: Atlas_I_Pathfinder_base_F
	{
		uniformClass="AX_U_I_CombatUniform_jacket_02_gloves_grn_F";
		identityTypes[]=
		{
			"LanguageGRE_F",
			"Head_Greek",
			"G_HAF_default"
		};
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_booniehat_dgtl_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_booniehat_dgtl_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_Medic_F: Atlas_I_Pathfinder_base_F
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_booniehat_dgtl_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_booniehat_dgtl_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_F: Atlas_I_Pathfinder_base_F
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_MilCap_dgtl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_MilCap_dgtl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_AT_F: Atlas_I_Pathfinder_base_F
	{
		uniformClass="AX_U_I_CombatUniform_jacket_02_gloves_grn_F";
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_MilCap_dgtl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_MilCap_dgtl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_SL_F: Atlas_I_Pathfinder_base_F
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Cap_blk_Raven_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Cap_blk_Raven_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_TL_F: Atlas_I_Pathfinder_base_F
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Cap_headphones",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Cap_headphones",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_RadioOperator_F: Atlas_I_Pathfinder_F
	{
		uniformClass="AX_U_I_CombatUniform_jacket_02_gloves_grn_F";
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Cap_blk_Raven_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Cap_blk_Raven_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_CMort_F: I_support_CMort_RF
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_MilCap_dgtl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_MilCap_dgtl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_I_Pathfinder_UAV_RF_F: Atlas_I_Pathfinder_base_F
	{
		linkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Bandanna_khk_hs",
			"I_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Chestrig_oli",
			"H_Bandanna_khk_hs",
			"I_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
};