    class O_R_Patrol_Soldier_A_F: O_R_Soldier_Base_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_A_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="lk_U_gorka_khk_F";
        backpack="B_Patrol_Carryall_green_Ammo_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        weapons[]=
		{
			"AX_arifle_AK12U_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_AK12U_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "AX_H_HelmetLuchnik_headset_spray_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
        respawnLinkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "AX_H_HelmetLuchnik_headset_spray_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
    };
    class O_R_Patrol_Soldier_AR2_F: O_R_Soldier_AR_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_AR2_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
        displayName="$STR_A3_CfgVehicles_B_Patrol_Soldier_MG_F0";
		uniformClass="AX_U_O_R_Gorka_taiga_02_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        weapons[]=
		{
			"AX_pkp_mg_bvo_snds_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_pkp_mg_bvo_snds_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "lk_sfera_blk",
            "G_Balaclava_blk",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "lk_sfera_blk",
            "G_Balaclava_blk",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
    };
    class O_R_Patrol_Soldier_AR_F: O_R_Soldier_AR_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_AR_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_khk_taiga_02_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        weapons[]=
        {
            "AX_arifle_AK12_lush_bvo_snds_pointer_BI_F",
            "hgun_Rook40_F",
            "Binocular",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "AX_arifle_AK12_lush_bvo_snds_pointer_BI_F",
            "hgun_Rook40_F",
            "Binocular",
            "Throw",
            "Put"
        };
        linkedItems[]=
        {
            "V_SmershVest_01_F",
            "lk_sfera_blk",
            "G_Balaclava_blk",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
        respawnLinkedItems[]=
        {
            "V_SmershVest_01_F",
            "lk_sfera_blk",
            "G_Balaclava_blk",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
    };
    class O_R_Patrol_Soldier_Medic: O_R_medic_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_Medic.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_khk_taiga_02_F";
        backpack="B_FieldPack_taiga_Medic_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        weapons[]=
		{
			"AX_arifle_AK12_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_AK12_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "H_HelmetLuchnik_headset_grn_F",
            "AX_G_Balaclava_ribbed_G_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
        respawnLinkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "H_HelmetLuchnik_headset_grn_F",
            "AX_G_Balaclava_ribbed_G_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
    };
    class O_R_Patrol_Soldier_Engineer_F: O_R_Soldier_Base_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_Engineer_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_taiga_khk_01_F";
        backpack="B_Patrol_FieldPack_green_eng_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        weapons[]=
		{
			"AX_arifle_AK12U_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"LaserDesignator_01_khk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_AK12U_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"LaserDesignator_01_khk_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "V_SmershVest_01_F",
            "G_AirPurifyingRespirator_02_olive_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
        respawnLinkedItems[]=
        {
            "V_SmershVest_01_F",
            "G_AirPurifyingRespirator_02_olive_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
    };
    class O_R_Patrol_Soldier_GL_F: O_R_Soldier_GL_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_GL_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_khk_taiga_02_F";
        backpack="B_FieldPack_taiga_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        weapons[]=
		{
			"AX_arifle_AK12_GL_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_AK12_GL_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "H_HelmetLuchnik_cover_grn_F",
            "AX_G_Balaclava_ribbed_G_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
        respawnLinkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "H_HelmetLuchnik_cover_grn_F",
            "AX_G_Balaclava_ribbed_G_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
    };
    class O_R_Patrol_Soldier_M_F: O_R_soldier_M_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_M_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_blk_taiga_02_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        linkedItems[]=
        {
            "V_SmershVest_01_F",
            "H_Watchcap_camo",
            "G_Bandanna_oli",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_hs_F"
        };
        respawnLinkedItems[]=
        {
            "V_SmershVest_01_F",
            "H_Watchcap_camo",
            "G_Bandanna_oli",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_hs_F"
        };
    };
    class O_R_Patrol_Soldier_M2_F: O_R_soldier_M_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_M2_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_taiga_02_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"AX_srifle_DMR_04_green_DMS_weathered_Kir_F",
			"hgun_Rook40_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_04_green_DMS_weathered_Kir_F",
			"hgun_Rook40_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "Aegis_H_Milcap_nohs_taiga_F",
            "G_Bandanna_oli",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_ep_F"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "Aegis_H_Milcap_nohs_taiga_F",
            "G_Bandanna_oli",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_ep_F"
        };
    };
    class O_R_Patrol_Soldier_LAT_F: O_R_Soldier_LAT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_LAT_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_taiga_01_F";
        backpack="B_FieldPack_taiga_RPG_AT_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"AX_arifle_AK12_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"launch_RPG32_green_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_AK12_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"launch_RPG32_green_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "Aegis_H_MilCap_tachs_taiga_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
        respawnLinkedItems[]=
        {
            "AX_V_OCarrierLuchnik_SuperLite_F",
            "Aegis_H_MilCap_tachs_taiga_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_grn_F"
        };
    };
    class O_R_Patrol_Soldier_TL_F: O_R_Soldier_TL_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\O_R_Patrol_Soldier_TL_F.jpg";
		editorSubcategory="EdSubcat_Personnel_RUSOF";
		uniformClass="AX_U_O_R_Gorka_taiga_khk_02_F";
        backpack="B_FieldPack_taiga_F";
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
        weapons[]=
		{
			"AX_arifle_AK12_GL_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_AK12_GL_lush_bvo_snds_pointer_F",
			"hgun_Rook40_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "AX_V_OCarrierLuchnik_CQBLite_F",
            "H_Booniehat_taiga",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_hidden_F"
        };
        respawnLinkedItems[]=
        {
            "AX_V_OCarrierLuchnik_CQBLite_F",
            "H_Booniehat_taiga",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "AX_O_NVGoggles_grn_hidden_F"
        };
    };