    class Aegis_O_R_Conscript_Base_F: O_R_Soldier_Base_F
	{
    };
    class Aegis_O_R_Conscript_SL_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_SL_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"AX_H_Helmet6B28_cover_taiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"AX_H_Helmet6B28_cover_taiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_TL_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_TL_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_F.jpg";
        weapons[]=
		{
			"arifle_AK12_545_FL_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AK12_545_FL_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AT_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_AT_F.jpg";
		backpack="AX_B_EAssaultPack_taiga_RPG7_AT_F";
		weapons[]=
		{
			"arifle_AK12U_545_FL_F",
			"Aegis_Launch_RPG7M_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AK12U_545_FL_F",
			"Aegis_Launch_RPG7M_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_M_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_M_F.jpg";
        weapons[]=
		{
			"AX_srifle_DMR_01_black_ARCO_FL_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_01_black_ARCO_FL_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_GL_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_GL_F.jpg";
		weapons[]=
		{
			"AX_arifle_AK12_GL_545_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_AK12_GL_545_flash_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AR_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_AR_F.jpg";
        weapons[]=
		{
			"Ax_arifle_RPK12_545_bvo_flash_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Ax_arifle_RPK12_545_bvo_flash_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Medic_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_Medic_F.jpg";
		backpack="AX_B_EAssaultPack_taiga_Medic_F";
        weapons[]=
		{
			"arifle_AK12U_545_FL_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AK12U_545_FL_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Repair_F: Aegis_O_R_Conscript_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_Repair_F.jpg";
        weapons[]=
		{
			"arifle_AK12U_545_FL_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_AK12U_545_FL_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"lk_6b28_oli",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };

//Arid
	class Aegis_O_R_Conscript_SL_ard_F: Aegis_O_R_Conscript_SL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_SL_ard_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"AX_H_Helmet6B28_cover_arid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"AX_H_Helmet6B28_cover_arid_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_TL_ard_F: Aegis_O_R_Conscript_TL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_TL_ard_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_ard_F: Aegis_O_R_Conscript_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_ard_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AT_ard_F: Aegis_O_R_Conscript_AT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_AT_ard_F.jpg";
		backpack="AX_B_EAssaultPack_arid_RPG7_AT_F";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_M_ard_F: Aegis_O_R_Conscript_M_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_M_ard_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_GL_ard_F: Aegis_O_R_Conscript_GL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_GL_ard_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AR_ard_F: Aegis_O_R_Conscript_AR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_AR_ard_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Medic_ard_F: Aegis_O_R_Conscript_Medic_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_Medic_ard_F.jpg";
		backpack="AX_B_EAssaultPack_arid_Medic_F";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Repair_ard_F: Aegis_O_R_Conscript_Repair_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_russia\enoch\Aegis_O_R_Conscript_Repair_ard_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"lk_6b28_khk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    