	class O_R_Soldier_recon_base: O_R_Soldier_Base_F
	{
    };
    class O_R_recon_TL_F: O_R_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_SmershVest_01_radio_F",
			"H_HelmetAggressor_cover_taiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_radio_F",
			"H_HelmetAggressor_cover_taiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_recon_exp_F: O_R_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_recon_AR_F: O_R_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_cover_taiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_cover_taiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_recon_M_F: O_R_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_Booniehat_taiga_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_Booniehat_taiga_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_recon_medic_F: O_R_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_recon_GL_F: O_R_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_cover_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_cover_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_recon_LAT_F: O_R_Soldier_recon_base
	{
		linkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_cover_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_F",
			"H_HelmetAggressor_cover_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_recon_JTAC_F: O_R_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_pkp_mg_bvo_snds_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_pkp_mg_bvo_snds_F",
			"hgun_Rook40_F",
			"Binocular",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"lk_200Rnd_762x54_Box",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"V_SmershVest_01_radio_F",
			"H_Booniehat_taiga_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_SmershVest_01_radio_F",
			"H_Booniehat_taiga_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
