class CfgPatches
{
	class ax_faction_f_us_grfu_pacific_black_mx
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"A3_Data_F_Decade_Loadorder",
			"data_f_lxWS_Loadorder",
			"A3_Aegis_Data_F_Aegis_Loadorder",
			"ax_faction_f_us_grfu"
		};
	};
};
class CfgVehicles
{
	class B_Soldier_A_F;
	class B_soldier_AAR_F;
	class B_support_AMG_F;
	class B_support_AMort_F;
	class B_soldier_AAA_F;
	class B_soldier_AAT_F;
	class B_soldier_AR_F;
	class B_medic_F;
	class B_crew_F;
	class B_engineer_F;
	class B_soldier_exp_F;
	class B_Soldier_GL_F;
	class B_support_GMG_F;
	class B_support_MG_F;
	class B_support_Mort_F;
	class B_helicrew_F;
	class B_Helipilot_F;
	class B_soldier_M_F;
	class B_Sharpshooter_F;
	class B_soldier_AA_F;
	class B_soldier_AT_F;
	class B_officer_F;
	class B_soldier_PG_F;
	class B_Pilot_F;
	class B_soldier_repair_F;
	class B_Soldier_F;
	class B_soldier_LAT_F;
	class B_soldier_LAT2_F;
	class B_Soldier_lite_F;
	class B_Soldier_CQ_F;
	class B_Soldier_SL_F;
	class B_Soldier_TL_F;
	class B_soldier_UAV_F;
	class B_HeavyGunner_F;
	class B_Soldier_MG_F;
	class B_diver_F;
	class B_diver_exp_F;
	class B_diver_TL_F;
	class B_recon_AR_F;
	class B_recon_exp_F;
	class B_recon_GL_F;
	class B_recon_JTAC_F;
	class B_recon_MG_F;
	class B_recon_M_F;
	class B_recon_medic_F;
	class B_recon_F;
	class B_recon_LAT_F;
	class B_recon_CQ_F;
	class B_Recon_Sharpshooter_F;
	class B_recon_TL_F;
	class B_spotter_F;
	class B_ghillie_ard_F;
	class B_ghillie_lsh_F;
	class B_ghillie_sard_F;
	class B_T_ghillie_tna_F;
	class B_Fighter_Pilot_F;
	class B_T_Soldier_A_F: B_Soldier_A_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_AAR_F: B_soldier_AAR_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Support_AMG_F: B_support_AMG_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Support_AMort_F: B_support_AMort_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_AAA_F: B_soldier_AAA_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_AAT_F: B_soldier_AAT_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_AR_F: B_soldier_AR_F
	{
		weapons[]=
		{
			"arifle_MX_SW_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_SW_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Medic_F: B_medic_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
	};
	class B_T_Crew_F: B_crew_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell"
		};
	};
	class B_T_Engineer_F: B_engineer_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShell"
		};
	};
	class B_T_Soldier_Exp_F: B_soldier_exp_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_GL_F: B_Soldier_GL_F
	{
		weapons[]=
		{
			"arifle_MX_GL_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
	};
	class B_T_Support_GMG_F: B_support_GMG_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Support_MG_F: B_support_MG_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Support_Mort_F: B_support_Mort_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Helicrew_F: B_helicrew_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
	};
	class B_T_Helipilot_F: B_Helipilot_F
	{
		weapons[]=
		{
			"SMG_01_Black_Holo_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_Black_Holo_F",
			"Throw",
			"Put"
		};
	};
	class B_T_soldier_M_F: B_soldier_M_F
	{
		weapons[]=
		{
			"arifle_MXM_Black_MOS_Pointer_Bipod_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MXM_Black_MOS_Pointer_Bipod_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_AA_F: B_soldier_AA_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"launch_B_Titan_olive_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"launch_B_Titan_olive_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AA",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AA",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_AT_F: B_soldier_AT_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"launch_I_Titan_short_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"launch_I_Titan_short_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AT",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"Titan_AT",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Officer_F: B_officer_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_F",
			"hgun_Pistol_heavy_01_black_MRD_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_F",
			"hgun_Pistol_heavy_01_black_MRD_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
	};
	class B_T_Soldier_PG_F: B_soldier_PG_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_Repair_F: B_soldier_repair_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_F: B_Soldier_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_LAT_F: B_soldier_LAT_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"launch_NLAW_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"launch_NLAW_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_SL_F: B_Soldier_SL_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
	};
	class B_T_Soldier_TL_F: B_Soldier_TL_F
	{
		weapons[]=
		{
			"arifle_MX_GL_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_Black_Hamr_pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"30Rnd_65x39_caseless_black_mag_Tracer",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
	};
	class B_T_Soldier_UAV_F: B_soldier_UAV_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_unarmed_F: B_T_Soldier_F
	{
	};
	class B_T_Soldier_Lite_F: B_Soldier_lite_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"HandGrenade",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"HandGrenade",
			"SmokeShell"
		};
	};
	class B_T_Soldier_CQ_F: B_Soldier_CQ_F
	{
		weapons[]=
		{
			"sgun_KSG_ACO_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"sgun_KSG_ACO_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
	};
	class B_T_Sharpshooter_F: B_Sharpshooter_F
	{
		weapons[]=
		{
			"srifle_DMR_03_AMS_LP_BI_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_03_AMS_LP_BI_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class B_T_Soldier_LAT2_F: B_soldier_LAT2_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"launch_MRAWS_green_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"launch_MRAWS_green_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MRAWS_HEAT_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MRAWS_HEAT_F",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_Soldier_CBRN_F: B_T_Soldier_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_Holo_FL_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_Holo_FL_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_RadioOperator_F: B_T_Soldier_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Holo_Pointer_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class B_T_HeavyGunner_F: B_HeavyGunner_F
	{
		weapons[]=
		{
			"MMG_02_black_RCO_LP_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MMG_02_black_RCO_LP_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
	};
	class B_T_Soldier_MG_F: B_Soldier_MG_F
	{
		weapons[]=
		{
			"LMG_Mk200_black_RCO_LP_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_Mk200_black_RCO_LP_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
	};
	class B_T_Pilot_F: B_Pilot_F
	{
		weapons[]=
		{
			"SMG_01_Black_Holo_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_Black_Holo_F",
			"Throw",
			"Put"
		};
	};
	class B_T_Fighter_Pilot_F: B_Fighter_Pilot_F
	{
		weapons[]=
		{
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
	};
	class B_T_Recon_AR_F: B_recon_AR_F
	{
		weapons[]=
		{
			"arifle_MX_SW_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_SW_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"100Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_GL_F: B_recon_GL_F
	{
		weapons[]=
		{
			"arifle_MX_GL_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_GL_Black_RCO_pointer_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
	};
	class B_T_Recon_Exp_F: B_recon_exp_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_JTAC_F: B_recon_JTAC_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_M_F: B_recon_M_F
	{
		weapons[]=
		{
			"arifle_MXM_Black_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MXM_Black_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_Medic_F: B_recon_medic_F
	{
		weapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MXC_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_F: B_recon_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_LAT_F: B_recon_LAT_F
	{
		weapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"launch_NLAW_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_ACO_Pointer_Snds_F",
			"launch_NLAW_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"NLAW_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_TL_F: B_recon_TL_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"30Rnd_556x45_Stanag_Tracer_Red",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Recon_Sharpshooter_F: B_Recon_Sharpshooter_F
	{
		weapons[]=
		{
			"srifle_DMR_03_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_03_DMS_LP_BI_snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class B_T_Recon_MG_F: B_recon_MG_F
	{
		weapons[]=
		{
			"LMG_Mk200_black_RCO_LP_S_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_Mk200_black_RCO_LP_S_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
	};
	class B_T_Recon_CQ_F: B_recon_CQ_F
	{
		weapons[]=
		{
			"sgun_KSG_ACO_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"sgun_KSG_ACO_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"8Rnd_12Gauge_Slug",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_Spotter_F: B_spotter_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class B_T_ghillie_spotter_tna_F: B_T_ghillie_tna_F
	{
		weapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		respawnWeapons[]=
		{
			"arifle_MX_Black_Hamr_Pointer_Snds_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator_01_khk_F"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class Atlas_B_T_Soldier_JSOC_base;
	class Atlas_B_T_JSOC_AR_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MX_SW_blk_HAMR_IR_Snds_BI_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MX_SW_blk_HAMR_IR_Snds_BI_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"100rnd_65x39_caseless_black_mag",
			"100rnd_65x39_caseless_black_mag",
			"100rnd_65x39_caseless_black_mag",
			"100rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"100rnd_65x39_caseless_black_mag",
			"100rnd_65x39_caseless_black_mag",
			"100rnd_65x39_caseless_black_mag",
			"100rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_Exp_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_GL_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MX_GL_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MX_GL_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_HEDP_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_HEDP_Grenade_shell"
		};
	};
	class Atlas_B_T_JSOC_JTAC_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_M_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MXM_blk_SOS_IR_Snds_BI_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXM_blk_SOS_IR_Snds_BI_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_Medic_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_LAT_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"launch_MRAWS_green_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"launch_MRAWS_green_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MRAWS_HEAT_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MRAWS_HEAT_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_TL_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_SL_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MX_GL_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MX_GL_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"30Rnd_65x39_caseless_black_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
	};
	class Atlas_B_T_JSOC_Sharpshooter_F: Atlas_B_T_JSOC_M_F
	{
		weapons[]=
		{
			"Atlas_arifle_SR25_MR_SOS_IR_Snds_BI_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_SR25_MR_SOS_IR_Snds_BI_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"Aegis_20Rnd_762x51_Red_SMAG",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_UAV_F: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MX_blk_HAMR_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class Atlas_B_T_JSOC_UAV_lxWS: Atlas_B_T_Soldier_JSOC_base
	{
		weapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_arifle_MXC_blk_Holo_IR_Snds_F",
			"hgun_P07_blk_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
};
