	class C_Uniform_FormalSuit_01_base_F: Civilian_F
	{
		modelSides[]={6}; //0opf,1blu,2ind,3civ,6moddersresourcesnosiderestriction?,upto7
	};
	class B_RangeMaster_F;
	class C_Marshal_F: B_RangeMaster_F
	{
		modelSides[]={6};
	};
	class vn_b_cia_base: vn_b_men_aircrew_base
	{
		scope=0;
		scopeCurator=0;
		faction="B_CIA";
		editorSubcategory="vn_b_men_cia";
		genericNames="macvmen";
		role="SpecialOperative";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_SF_s"
				};
				speechPlural[]=
				{
					"veh_infantry_SF_p"
				};
			};
		};
		textSingular="$STR_A3_namesound_veh_infantry_sf_s";
		textPlural="$STR_A3_namesound_veh_infantry_sf_p";
		nameSound="veh_infantry_SF_s";
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"vn_g_macv_pilot"
		};
		uniformClass="U_Marshal";
		backpack="";
		Items[]=
		{
			"vn_b_item_firstaidkit"
		};
		respawnItems[]=
		{
			"vn_b_item_firstaidkit"
		};
		weapons[]=
		{
			"vn_mpu",
			"vn_mk21_binocs",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_mpu_t_mag",
			"vn_mpu_t_mag",
			"vn_mpu_t_mag",
			"vn_mpu_t_mag",
			"vn_m61_grenade_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag",
			"vn_m18_red_mag",
			"vn_m18_yellow_mag",
			"vn_m18_yellow_mag",
			"vn_m18_purple_mag",
			"vn_m18_purple_mag"
		};
		respawnweapons[]=
		{
			"vn_mpu",
			"vn_mk21_binocs",
			"Throw",
			"Put"
		};
		respawnmagazines[]=
		{
			"vn_mpu_t_mag",
			"vn_mpu_t_mag",
			"vn_mpu_t_mag",
			"vn_mpu_t_mag",
			"vn_m61_grenade_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag",
			"vn_m18_red_mag",
			"vn_m18_yellow_mag",
			"vn_m18_yellow_mag",
			"vn_m18_purple_mag",
			"vn_m18_purple_mag"
		};
		linkedItems[]=
		{
			"vn_b_vest_aircrew_05",
			"vn_b_helmet_svh4_02_05",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_aircrew_05",
			"vn_b_helmet_svh4_02_05",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
//Field Operative

//Embassy
	class vn_b_men_cia_embassy_01: vn_b_cia_base
	{
		scope=2;
		scopeCurator=2;
        editorSubcategory="EdSubcat_Personnel_Embassy";
		displayName="Agent (Model 10)";
		editorPreview="\vn\editorpreviews_f_vietnam_02\characters\preview_vn_b_men_aircrew_39.jpg";
		uniformClass="U_Marshal";
		weapons[]=
		{
			"vn_m10",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m10",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_m10_mag",
			"vn_m10_mag",
			"vn_m10_mag",
			"vn_m10_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		respawnmagazines[]=
		{
			"vn_m10_mag",
			"vn_m10_mag",
			"vn_m10_mag",
			"vn_m10_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		linkedItems[]=
		{
            "vn_b_aviator",
			"vn_b_vest_usarmy_13",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
            "vn_b_aviator",
			"vn_b_vest_usarmy_13",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_cia_embassy_02: vn_b_cia_base
	{
		scope=2;
		scopeCurator=2;
        editorSubcategory="EdSubcat_Personnel_Embassy";
		displayName="Agent (Hi-Power)";
		editorPreview="\vn\editorpreviews_f_vietnam_02\characters\preview_vn_b_men_aircrew_39.jpg";
		uniformClass="U_Rangemaster";
		weapons[]=
		{
			"vn_hp",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_hp",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_hp_mag",
			"vn_hp_mag",
			"vn_hp_mag",
			"vn_hp_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		respawnmagazines[]=
		{
			"vn_hp_mag",
			"vn_hp_mag",
			"vn_hp_mag",
			"vn_hp_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		linkedItems[]=
		{
            "vn_g_glasses_01",
			"vn_b_vest_usarmy_12",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
            "vn_g_glasses_01",
			"vn_b_vest_usarmy_12",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_cia_embassy_03: vn_b_cia_base
	{
		scope=2;
		scopeCurator=2;
        editorSubcategory="EdSubcat_Personnel_Embassy";
		displayName="Agent (Uzi)";
		editorPreview="\vn\editorpreviews_f_vietnam_02\characters\preview_vn_b_men_aircrew_39.jpg";
		uniformClass="U_Rangemaster";
		weapons[]=
		{
			"vn_mpu",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_mpu",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_mpu_mag",
			"vn_mpu_mag",
			"vn_mpu_mag",
			"vn_mpu_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		respawnmagazines[]=
		{
			"vn_mpu_mag",
			"vn_mpu_mag",
			"vn_mpu_mag",
			"vn_mpu_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		linkedItems[]=
		{
			"vn_b_vest_usarmy_14",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usarmy_14",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_cia_embassy_04: vn_b_cia_base
	{
		scope=2;
		scopeCurator=2;
        editorSubcategory="EdSubcat_Personnel_Embassy";
		displayName="Agent (XM177 1)";
		editorPreview="\vn\editorpreviews_f_vietnam_02\characters\preview_vn_b_men_aircrew_39.jpg";
		uniformClass="U_Marshal";
		weapons[]=
		{
			"vn_xm177",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_xm177",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		respawnmagazines[]=
		{
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		linkedItems[]=
		{
            "vn_g_spectacles_02",
			"vn_b_vest_usarmy_14",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
            "vn_g_spectacles_02",
			"vn_b_vest_usarmy_14",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_cia_embassy_05: vn_b_cia_base
	{
		scope=2;
		scopeCurator=2;
        editorSubcategory="EdSubcat_Personnel_Embassy";
		displayName="Agent (XM177 2)";
		editorPreview="\vn\editorpreviews_f_vietnam_02\characters\preview_vn_b_men_aircrew_39.jpg";
		uniformClass="U_C_FormalSuit_01_black_F";
		weapons[]=
		{
			"vn_xm177",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_xm177",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		respawnmagazines[]=
		{
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m16_20_mag",
			"vn_m61_grenade_mag",
			"vn_m18_red_mag"
		};
		linkedItems[]=
		{
			"vn_b_vest_usarmy_11",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usarmy_11",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_cia_embassy_06: vn_b_cia_base
	{
		scope=2;
		scopeCurator=2;
        editorSubcategory="EdSubcat_Personnel_Embassy";
		displayName="Agent (Incognito)";
		editorPreview="\A3\EditorPreviews_F_AoW\Data\CfgVehicles\C_Man_formal_1_F.jpg";
		uniformClass="U_C_FormalSuit_01_black_F";
		weapons[]=
		{
			"vn_hd",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_hd",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_hd_mag",
			"vn_hd_mag",
			"vn_hd_mag",
			"vn_hd_mag",
		};
		respawnmagazines[]=
		{
			"vn_hd_mag",
			"vn_hd_mag",
			"vn_hd_mag",
			"vn_hd_mag",
		};
		linkedItems[]=
		{
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };