    class vn_c_men_lao_base: vn_c_men_base
	{
        genericNames="cambodianmen";
        faction="C_LAO";
        identityTypes[]=
		{
			"LanguageMUTE_F",
			"vn_b_asian_indig"
		};
    };
    class vn_c_men_lao_01: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_01_DN";
		identityTypes[]=
		{
			"LanguageMUTE_F",
			"vn_c_asian_old"
		};
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_01.p3d";
		uniformClass="vn_o_uniform_vc_01_01";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		role="Rifleman";
		cost=600000;
		camouflage=1.6;
		icon="iconManOfficer";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_officer_s"
				};
				speechPlural[]=
				{
					"veh_infantry_officer_p"
				};
			};
		};
		textSingular="$STR_A3_namesound_veh_infantry_officer_s";
		textPlural="$STR_A3_namesound_veh_infantry_officer_p";
		nameSound="veh_infantry_officer_s";
		linkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_01.jpg";
    };
	class vn_c_men_lao_02: vn_c_men_lao_01
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_02_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_02.p3d";
		uniformClass="vn_o_uniform_vc_02_01";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_02.jpg";
    };
	class vn_c_men_lao_03: vn_c_men_lao_01
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_03_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_03.p3d";
		uniformClass="vn_o_uniform_vc_03_01";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_03.jpg";
    };
	class vn_c_men_lao_04: vn_c_men_lao_01
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_04_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_04.p3d";
		uniformClass="vn_o_uniform_vc_04_01";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_04.jpg";
    };
	class vn_c_men_lao_05: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_05_DN";
		role="CombatLifeSaver";
		cost=300000;
		camouflage=1.6;
		icon="iconManMedic";
		picture="pictureHeal";
		attendant=1;
		canHideBodies=1;
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_medic_s"
				};
				speechPlural[]=
				{
					"veh_infantry_medic_p"
				};
			};
		};
		textSingular="$STR_A3_namesound_veh_infantry_medic_s";
		textPlural="$STR_A3_namesound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_01.p3d";
		uniformClass="vn_o_uniform_vc_01_02";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		backpack="vn_c_pack_01_medic_pl";
		linkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_05.jpg";
    };
	class vn_c_men_lao_06: vn_c_men_lao_05
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_06_DN";
		linkedItems[]=
		{
			"vn_o_boonie_vc_01_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_o_boonie_vc_01_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_02.p3d";
		uniformClass="vn_o_uniform_vc_02_02";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_06.jpg";
    };
	class vn_c_men_lao_07: vn_c_men_lao_05
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_07_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_03.p3d";
		uniformClass="vn_o_uniform_vc_03_02";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_07.jpg";
    };
	class vn_c_men_lao_08: vn_c_men_lao_05
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_08_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_04.p3d";
		uniformClass="vn_o_uniform_vc_04_02";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_03",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_03",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_08.jpg";
    };
	class vn_c_men_lao_09: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_09_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_01.p3d";
		uniformClass="vn_o_uniform_vc_01_03";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_03_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_01_co.paa"
		};
		role="Sapper";
		icon="iconManEngineer";
		picture="pictureRepair";
		engineer=1;
		canDeactivateMines=1;
		detectSkill=24;
		cost=220000;
		camouflage=1.6;
		backpack="vn_c_pack_01_engineer_pl";
		linkedItems[]=
		{
			"vn_c_headband_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_09.jpg";
    };
	class vn_c_men_lao_10: vn_c_men_lao_09
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_10_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_02.p3d";
		uniformClass="vn_o_uniform_vc_02_03";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_03_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_01_co.paa"
		};
		linkedItems[]=
		{
			"vn_o_boonie_vc_01_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_o_boonie_vc_01_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_10.jpg";
    };
	class vn_c_men_lao_11: vn_c_men_lao_09
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_11_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_03.p3d";
		uniformClass="vn_o_uniform_vc_03_03";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_03_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_01_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_11.jpg";
    };
	class vn_c_men_lao_12: vn_c_men_lao_09
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_12_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_04.p3d";
		uniformClass="vn_o_uniform_vc_04_03";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_03_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_01_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_12.jpg";
    };
	class vn_c_men_lao_13: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_13_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_01.p3d";
		uniformClass="vn_o_uniform_vc_01_04";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_08_co.paa"
		};
		backpack="vn_c_pack_02";
		linkedItems[]=
		{
			"vn_c_headband_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_13.jpg";
    };
	class vn_c_men_lao_14: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_14_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_02.p3d";
		uniformClass="vn_o_uniform_vc_02_04";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_08_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_14.jpg";
    };
	class vn_c_men_lao_15: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_15_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_03.p3d";
		uniformClass="vn_o_uniform_vc_03_04";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_08_co.paa"
		};
		linkedItems[]=
		{
			"vn_o_boonie_vc_01_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_o_boonie_vc_01_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_15.jpg";
    };
	class vn_c_men_lao_16: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_16_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_04.p3d";
		uniformClass="vn_o_uniform_vc_04_04";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_08_co.paa"
		};
		backpack="vn_c_pack_01";
		linkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_16.jpg";
    };
	class vn_c_men_lao_17: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_17_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_01.p3d";
		uniformClass="vn_o_uniform_vc_01_05";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_02_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_03",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_03",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_17.jpg";
    };
	class vn_c_men_lao_18: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_18_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_02.p3d";
		uniformClass="vn_o_uniform_vc_02_05";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_02_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		backpack="vn_c_pack_02";
		linkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_18.jpg";
    };
	class vn_c_men_lao_19: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_19_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_03.p3d";
		uniformClass="vn_o_uniform_vc_03_05";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_02_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		backpack="vn_c_pack_02";
		linkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_19.jpg";
    };
	class vn_c_men_lao_20: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_20_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_04.p3d";
		uniformClass="vn_o_uniform_vc_04_05";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_02_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_07_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_20.jpg";
    };
	class vn_c_men_lao_21: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_21_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_01.p3d";
		uniformClass="vn_o_uniform_vc_01_06";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_21.jpg";
    };
	class vn_c_men_lao_22: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_22_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_02.p3d";
		uniformClass="vn_o_uniform_vc_02_06";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_22.jpg";
    };
	class vn_c_men_lao_23: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_23_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_03.p3d";
		uniformClass="vn_o_uniform_vc_03_06";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		backpack="vn_c_pack_02";
		linkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_23.jpg";
    };
	class vn_c_men_lao_24: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_24_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_04.p3d";
		uniformClass="vn_o_uniform_vc_04_06";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_04",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_24.jpg";
    };
	class vn_c_men_lao_25: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_25_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_01.p3d";
		uniformClass="vn_o_uniform_vc_01_07";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_03_co.paa"
		};
		backpack="vn_c_pack_01";
		linkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_25.jpg";
    };
	class vn_c_men_lao_26: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_26_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_02.p3d";
		uniformClass="vn_o_uniform_vc_02_07";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_03_co.paa"
		};
		linkedItems[]=
		{
			"vn_o_boonie_vc_01_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_o_boonie_vc_01_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_26.jpg";
    };
	class vn_c_men_lao_27: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_27_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_03.p3d";
		uniformClass="vn_o_uniform_vc_03_07";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_03_co.paa"
		};
		backpack="vn_c_pack_02";
		linkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_27.jpg";
    };
	class vn_c_men_lao_28: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_28_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_vc_local_bdu_04.p3d";
		uniformClass="vn_o_uniform_vc_04_07";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_03_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_28.jpg";
    };
	class vn_c_men_lao_29: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_29_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_nva_army_bdu_14.p3d";
		uniformClass="vn_o_uniform_vc_05_01";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_co.paa",
			"\vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_29.jpg";
    };
	class vn_c_men_lao_30: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_30_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_nva_army_bdu_14.p3d";
		uniformClass="vn_o_uniform_vc_05_02";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_02_co.paa",
			"\vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_conehat_02",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_30.jpg";
    };
	class vn_c_men_lao_31: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_31_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_nva_army_bdu_14.p3d";
		uniformClass="vn_o_uniform_vc_05_03";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_03_co.paa",
			"\vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_02_co.paa"
		};
		linkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_c_headband_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_31.jpg";
    };
	class vn_c_men_lao_32: vn_c_men_lao_base
    {
        author="$STR_VN_AUTHORSAVAGE";
		dlc="VN";
		appId=1227700;
		scope=2;
		scopeCurator=2;
		displayName="$STR_VN_C_MEN_32_DN";
		model="\vn\characters_f_vietnam\OPFOR\uniforms\vn_o_nva_army_bdu_14.p3d";
		uniformClass="vn_o_uniform_vc_05_04";
		hiddenSelectionsTextures[]=
		{
			"\vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_04_co.paa",
			"\vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_02_co.paa"
		};
		backpack="vn_c_pack_01";
		linkedItems[]=
		{
			"vn_o_boonie_vc_01_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		respawnLinkedItems[]=
		{
			"vn_o_boonie_vc_01_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch"
		};
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_32.jpg";
    };

//Boats
    class vn_c_boat_01_00_lao: vn_c_boat_01_00
    {
        faction="C_LAO";
		crew="vn_c_men_lao_14";
		typicalCargo[]=
		{
			"vn_c_men_lao_14"
		};
    };
	class vn_c_boat_01_01_lao: vn_c_boat_01_01
    {
        faction="C_LAO";
        crew="vn_c_men_lao_14";
		typicalCargo[]=
		{
			"vn_c_men_lao_14"
		};
    };
	class vn_c_boat_01_02_lao: vn_c_boat_01_02
    {
        faction="C_LAO";
        crew="vn_c_men_lao_14";
		typicalCargo[]=
		{
			"vn_c_men_lao_14"
		};
    };
	class vn_c_boat_01_03_lao: vn_c_boat_01_03
    {
        faction="C_LAO";
        crew="vn_c_men_lao_09";
		typicalCargo[]=
		{
			"vn_c_men_lao_09"
		};
    };
	class vn_c_boat_01_04_lao: vn_c_boat_01_04
    {
        faction="C_LAO";
        crew="vn_c_men_lao_09";
		typicalCargo[]=
		{
			"vn_c_men_lao_09"
		};
    };
	class vn_c_boat_02_00_lao: vn_c_boat_02_00
    {
        faction="C_LAO";
        crew="vn_c_men_lao_17";
		typicalCargo[]=
		{
			"vn_c_men_lao_17"
		};
    };
	class vn_c_boat_02_01_lao: vn_c_boat_02_01
    {
        faction="C_LAO";
        crew="vn_c_men_lao_17";
		typicalCargo[]=
		{
			"vn_c_men_lao_17"
		};
    };
	class vn_c_boat_02_02_lao: vn_c_boat_02_02
    {
        faction="C_LAO";
        crew="vn_c_men_lao_17";
		typicalCargo[]=
		{
			"vn_c_men_lao_17"
		};
    };
	class vn_c_boat_02_03_lao: vn_c_boat_02_03
    {
        faction="C_LAO";
        crew="vn_c_men_lao_17";
		typicalCargo[]=
		{
			"vn_c_men_lao_17"
		};
    };
	class vn_c_boat_02_04_lao: vn_c_boat_02_04
    {
        faction="C_LAO";
        crew="vn_c_men_lao_17";
		typicalCargo[]=
		{
			"vn_c_men_lao_17"
		};
    };
    class vn_c_boat_07_01_lao: vn_c_boat_07_01
    {
        faction="C_LAO";
        crew="vn_c_men_lao_14";
		typicalCargo[]=
		{
			"vn_c_men_lao_14"
		};
    };
	class vn_c_boat_07_02_lao: vn_c_boat_07_02
    {
        faction="C_LAO";
        crew="vn_c_men_lao_14";
		typicalCargo[]=
		{
			"vn_c_men_lao_14"
		};
    };
    class vn_c_boat_08_01_lao: vn_c_boat_08_01
    {
        faction="C_LAO";
        crew="vn_c_men_lao_17";
		typicalCargo[]=
		{
			"vn_c_men_lao_17"
		};
    };
	class vn_c_boat_08_02_lao: vn_c_boat_08_02
    {
        faction="C_LAO";
        crew="vn_c_men_lao_17";
		typicalCargo[]=
		{
			"vn_c_men_lao_17"
		};
    };

//Cars
    class vn_c_bicycle_01_lao: vn_c_bicycle_01
    {
        faction="C_LAO";
		crew="vn_c_men_lao_15";
		typicalCargo[]=
		{
			"vn_c_men_lao_16"
		};
    };
    class vn_c_bicycle_02_lao: vn_c_bicycle_02
    {
        faction="C_LAO";
		crew="vn_c_men_lao_15";
		typicalCargo[]=
		{
			"vn_c_men_lao_16"
		};
    };
    class vn_c_car_01_01_lao: vn_c_car_01_01
    {
        faction="C_LAO";
		crew="vn_c_men_lao_13";
    };
    class vn_c_car_01_02_lao: vn_c_car_01_02
    {
        faction="C_LAO";
		crew="vn_c_men_lao_13";
    };
	class vn_c_car_02_01_lao: vn_c_car_02_01
    {
        faction="C_LAO";
		crew="vn_c_men_lao_13";
    };
	class vn_c_car_03_01_lao: vn_c_car_03_01
    {
        faction="C_LAO";
		crew="vn_c_men_lao_13";
    };
	class vn_c_car_04_01_lao: vn_c_car_04_01
    {
        faction="C_LAO";
		crew="vn_c_men_lao_13";
    };
    class vn_c_wheeled_m151_01_lao: vn_c_wheeled_m151_01
    {
        faction="C_LAO";
		crew="vn_c_men_lao_13";
        class Turrets: Turrets
		{
			class codriver_ffv: codriver_ffv
			{
				gunnerType="vn_c_men_lao_17";
			};
			class cargoturret_rear: cargoturret_rear
			{
				gunnerType="vn_c_men_lao_31";
			};
		};
    };
	class vn_c_wheeled_m151_02_lao: vn_c_wheeled_m151_02
    {
        faction="C_LAO";
		crew="vn_c_men_lao_13";
        class Turrets: Turrets
		{
			class codriver_ffv: codriver_ffv
			{
				gunnerType="vn_c_men_lao_17";
			};
			class cargoturret_rear: cargoturret_rear
			{
				gunnerType="vn_c_men_lao_31";
			};
		};
    };