    //Men
	class vn_o_men_ussr_adv_base: O_R_Man_Base_F
	{
        scope=0;
		scopeCurator=0;
		identityTypes[]=
		{
			"LanguageRUS_F",
			"Head_Russian",
			"Head_Euro",
			"Head_Enoch",
			//"Head_Asian",
			"vn_g_vc_default"
		};
		faceType="Man_A3";
		side=0;
		faction="O_vn_USSR_Adv";
		genericNames="RussianMen";
		editorSubcategory="EdSubcat_Personnel";
		vehicleClass="Men";
		portrait="";
		picture="";
		icon="iconMan";
		accuracy=2.3;
		threat[]={1,0.1,0.1};
		camouflage=1.4;
		minFireTime=7;
		canCarryBackPack=1;
		nakedUniform="vn_o_uniform_basecharacter_01";
		modelSides[]={0,3};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"insignia"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_navy_bdu_01.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_navy_bdu_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_navy_bdu_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_01.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_pants_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_vc_bdu_shirt_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_shirt_01.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_shirt_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_shirt_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_01.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_01_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_shirt_02.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_shirt_02_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_shirt_02_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_02.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_02_injury.rvmat",
				"vn\characters_f_vietnam\OPFOR\uniforms\data\vn_o_nva_army_bdu_pants_02_injury.rvmat",
				"vn\characters_f_vietnam\opfor\uniforms\data\vn_o_nva_air_bdu_01.rvmat",
				"vn\characters_f_vietnam\opfor\uniforms\data\vn_o_nva_air_bdu_01_injury.rvmat",
				"vn\characters_f_vietnam\opfor\uniforms\data\vn_o_nva_air_bdu_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_shirt_01.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_shirt_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_shirt_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_pants_01.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_pants_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_pants_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_shirt_06.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_shirt_06_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_shirt_06_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_pants_06.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_pants_06_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_b_uniform_pants_06_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_01.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_02.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_02_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\uniforms\data\vn_basecharacter_02_injury.rvmat",
				"A3\Characters_F\BLUFOR\Data\clothing1.rvmat",
				"A3\Characters_F\BLUFOR\Data\clothing1_injury.rvmat",
				"A3\Characters_F\BLUFOR\Data\clothing1_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\characters_f\common\data\coveralls.rvmat",
				"A3\Characters_F\Common\Data\coveralls_injury.rvmat",
				"A3\Characters_F\Common\Data\coveralls_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\heads\data\m_white_01.rvmat",
				"vn\characters_f_vietnam\BLUFOR\heads\data\m_white_01_injury.rvmat",
				"vn\characters_f_vietnam\BLUFOR\heads\data\m_white_01_injury.rvmat"
			};
		};
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		class HitPoints: HitPoints
		{
			class HitFace
			{
				armor=1;
				material=-1;
				name="face_hub";
				passThrough=0.80000001;
				radius=0.079999998;
				explosionShielding=0.1;
				minimalHit=0.0099999998;
			};
			class HitNeck: HitFace
			{
				armor=1;
				material=-1;
				name="neck";
				passThrough=0.80000001;
				radius=0.1;
				explosionShielding=0.5;
				minimalHit=0.0099999998;
			};
			class HitHead: HitNeck
			{
				armor=1;
				material=-1;
				name="head";
				passThrough=0.80000001;
				radius=0.2;
				explosionShielding=0.5;
				minimalHit=0.0099999998;
				depends="HitFace max HitNeck";
			};
			class HitPelvis: HitHead
			{
				armor=6;
				material=-1;
				name="pelvis";
				passThrough=0.80000001;
				radius=0.23999999;
				explosionShielding=1;
				visual="injury_body";
				minimalHit=0.0099999998;
				depends="0";
			};
			class HitAbdomen: HitPelvis
			{
				armor=1;
				material=-1;
				name="spine1";
				passThrough=0.80000001;
				radius=0.16;
				explosionShielding=1;
				visual="injury_body";
				minimalHit=0.0099999998;
			};
			class HitDiaphragm: HitAbdomen
			{
				armor=1;
				material=-1;
				name="spine2";
				passThrough=0.80000001;
				radius=0.18000001;
				explosionShielding=2.4000001;
				visual="injury_body";
				minimalHit=0.0099999998;
			};
			class HitChest: HitDiaphragm
			{
				armor=1;
				material=-1;
				name="spine3";
				passThrough=0.80000001;
				radius=0.18000001;
				explosionShielding=2.4000001;
				visual="injury_body";
				minimalHit=0.0099999998;
			};
			class HitBody: HitChest
			{
				armor=1000;
				material=-1;
				name="body";
				passThrough=1;
				radius=0;
				explosionShielding=2.4000001;
				visual="injury_body";
				minimalHit=0.0099999998;
				depends="HitPelvis max HitAbdomen max HitDiaphragm max HitChest";
			};
			class HitArms: HitBody
			{
				armor=5;
				material=-1;
				name="arms";
				passThrough=1;
				radius=0.1;
				explosionShielding=0.30000001;
				visual="injury_hands";
				minimalHit=0.0099999998;
				depends="0";
			};
			class HitHands: HitArms
			{
				armor=5;
				material=-1;
				name="hands";
				passThrough=1;
				radius=0.1;
				explosionShielding=0.30000001;
				visual="injury_hands";
				minimalHit=0.0099999998;
				depends="HitArms";
			};
			class HitLegs: HitHands
			{
				armor=5;
				material=-1;
				name="legs";
				passThrough=1;
				radius=0.14;
				explosionShielding=0.30000001;
				visual="injury_legs";
				minimalHit=0.0099999998;
				depends="0";
			};
			class Incapacitated: HitLegs
			{
				armor=1000;
				material=-1;
				name="body";
				passThrough=1;
				radius=0;
				explosionShielding=1;
				visual="";
				minimalHit=0;
				depends="(((Total - 0.25) max 0) + ((HitHead - 0.25) max 0) + ((HitBody - 0.25) max 0)) * 2";
			};
		};
		role="Rifleman";
		cost=100000;
		canHideBodies=0;
		detectSkill=12;
		canDeactivateMines=0;
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_s"
				};
				speechPlural[]=
				{
					"veh_infantry_p"
				};
			};
		};
		textSingular="$STR_A3_namesound_veh_infantry_s";
		textPlural="$STR_A3_namesound_veh_infantry_p";
		nameSound="veh_infantry_s";
		maxSpeed=24;
		maxTurnAngularVelocity=3;
		lyingLimitSpeedHiding=0.80000001;
		crouchProbabilityHiding=0.80000001;
		lyingLimitSpeedCombat=1.8;
		crouchProbabilityCombat=0.40000001;
		crouchProbabilityEngage=0.75;
		lyingLimitSpeedStealth=2;
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		Items[]=
		{
			"vn_o_item_firstaidkit"
		};
		RespawnItems[]=
		{
			"vn_o_item_firstaidkit"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]=
		{
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_01: vn_o_men_ussr_adv_base
    {
        scope=2;
		scopeCurator=2;
        displayName="Advisor (PM/ Flashlight)";
		role="Rifleman";
		cost=600000;
		camouflage=1.6;
		icon="iconManOfficer";
        textSingular="$STR_A3_namesound_veh_infantry_officer_s";
		textPlural="$STR_A3_namesound_veh_infantry_officer_p";
        nameSound="veh_infantry_officer_s";
        editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_o_men_nva_65_15.jpg";
        uniformClass="vn_o_uniform_nva_army_04_01";
        weapons[]=
		{
			"vn_fkb1_pm",
			"Throw",
			"Put"
		};
        respawnweapons[]=
		{
			"vn_fkb1_pm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
        respawnmagazines[]=
		{
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
        linkedItems[]=
		{
			"vn_b_vest_usarmy_01",
			"vn_o_cap_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
			"vn_o_vest_07",
			"vn_o_cap_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_02: vn_o_men_ussr_adv_01
    {
        displayName="Advisor (PPS-43 1)";
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_o_men_nva_65_01.jpg";
        uniformClass="vn_o_uniform_nva_army_02_01";
        weapons[]=
		{
			"vn_pps43",
			"vn_pm",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_pps43",
			"vn_pm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		respawnmagazines[]=
		{
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		linkedItems[]=
		{
			"vn_o_vest_07",
			//"vn_o_cap_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
			"vn_o_vest_07",
			//"vn_o_cap_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_03: vn_o_men_ussr_adv_01
    {
        displayName="Advisor (AK 1)";
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_o_men_nva_65_05.jpg";
        uniformClass="vn_o_uniform_nva_army_02_02";
        weapons[]=
		{
			"vn_ak_01",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_ak_01",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		respawnmagazines[]=
		{
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		linkedItems[]=
		{
            "vn_b_scarf_01_01",
			"vn_o_vest_01",
			"vn_o_helmet_nva_09",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
            "vn_b_scarf_01_01",
			"vn_o_vest_01",
			"vn_o_helmet_nva_09",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_04: vn_o_men_ussr_adv_01
    {
        displayName="Advisor (PM 1)";
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_o_men_nva_65_13.jpg";
        uniformClass="vn_o_uniform_pl_army_02_11";
        weapons[]=
		{
			"vn_pm",
			"Throw",
			"Put"
		};
        respawnweapons[]=
		{
			"vn_pm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
        respawnmagazines[]=
		{
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
        linkedItems[]=
		{
			"vn_o_vest_05",
			"vn_o_helmet_nva_06",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
			"vn_o_vest_05",
			"vn_o_helmet_nva_06",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_05: vn_o_men_ussr_adv_01
    {
        displayName="Advisor (PPS-43 2)";
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_o_men_nva_22.jpg";
        uniformClass="vn_o_uniform_nva_army_02_03";
        weapons[]=
		{
			"vn_pps43",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_pps43",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		respawnmagazines[]=
		{
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		linkedItems[]=
		{
			"vn_o_boonie_nva_02_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
			"vn_o_boonie_nva_02_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_06: vn_o_men_ussr_adv_01
    {
        displayName="Advisor (PM 2)";
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_c_men_17.jpg";
        uniformClass="vn_o_uniform_vc_01_05";
        weapons[]=
		{
			"vn_pm",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_pm",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
        respawnmagazines[]=
		{
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_pm_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		linkedItems[]=
		{
			"vn_o_pl_cap_02_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
			"vn_o_pl_cap_02_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_07: vn_o_men_ussr_adv_01
    {
        displayName="Advisor (PPS-43 3)";
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_o_men_vc_01.jpg";
        uniformClass="vn_o_uniform_vc_02_06";
        weapons[]=
		{
			"vn_pps43",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_pps43",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		respawnmagazines[]=
		{
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_pps_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		linkedItems[]=
		{
            "vn_b_scarf_01_03",
            "vn_o_vest_07",
			"vn_o_cap_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
            "vn_b_scarf_01_03",
            "vn_o_vest_07",
			"vn_o_cap_01",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };
    class vn_o_men_ussr_adv_08: vn_o_men_ussr_adv_01
    {
        displayName="Advisor (AK 2)";
		editorPreview="\vn\editorpreviews_f_vietnam\characters\preview_vn_o_men_vc_06.jpg";
        uniformClass="vn_o_uniform_vc_reg_12_10";
        weapons[]=
		{
			"vn_ak_01",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_ak_01",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		respawnmagazines[]=
		{
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_type56_t_mag",
			"vn_rdg2_mag",
			"vn_t67_grenade_mag",
			"vn_t67_grenade_mag"
		};
		linkedItems[]=
		{
            "vn_b_scarf_01_03",
			"vn_o_vest_07",
			"vn_o_helmet_nva_09",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
		respawnLinkedItems[]=
		{
            "vn_b_scarf_01_03",
			"vn_o_vest_07",
			"vn_o_helmet_nva_09",
			"vn_o_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_o_item_radio_m252"
		};
    };

	//Cars
    class vn_o_ussr_adv_bicycle_01: vn_o_bicycle_01
    {
		faction="O_vn_USSR_Adv";
		editorSubcategory="EdSubcat_Cars";
		crew="vn_o_men_ussr_adv_02";
    };
    class vn_o_ussr_adv_bicycle_02: vn_o_bicycle_02
    {
        scope=1
        scopeCurator=1;
		faction="O_vn_USSR_Adv";
		editorSubcategory="EdSubcat_Cars";
		crew="vn_o_men_ussr_adv_02";
    };