	class I_Soldier_base_F;
	class I_Soldier_02_F;
	class I_Soldier_A_F: I_Soldier_02_F
	{
		backpack="I_Fieldpack_oli_249_Ammo";
	};
	class I_Soldier_AR_F: I_Soldier_02_F
	{
		weapons[]=
		{
			"LMG_03_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_03_F",
			"hgun_ACPC2_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_Tracer_F",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_Tracer_F",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"9Rnd_45ACP_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class I_Soldier_support_base_F;
	class I_Soldier_AAR_F: I_Soldier_support_base_F
	{
		backpack="B_TacticalPack_oli_249_AAR";
	};
    class Aegis_I_Soldier_recon_base: I_Soldier_base_F{};
	class Aegis_I_recon_AR_F: Aegis_I_Soldier_recon_base
    {
        weapons[]=
		{
			"AX_LMG_03_MRCO_LP_Snds_BI_F",
			"Aegis_hgun_Pistol_R57_MRD_LP_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_03_MRCO_LP_Snds_BI_F",
			"Aegis_hgun_Pistol_R57_MRD_LP_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"Aegis_20Rnd_570x28_RP57_Mag",
			"Aegis_20Rnd_570x28_RP57_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"200Rnd_556x45_Box_F",
			"Aegis_20Rnd_570x28_RP57_Mag",
			"Aegis_20Rnd_570x28_RP57_Mag",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_exp_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_chops_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_chops_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_GL_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_JTAC_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_M_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_medic_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_LAT_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_chops_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_chops_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class Aegis_I_recon_TL_F: Aegis_I_Soldier_recon_base
    {
		linkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_rig_oli_RF",
			"AX_H_HelmetHBK_aaf_ear_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };