class cfgPatches
{
	class ax_faction_iran_grfu_rf
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"RF_Data_Loadorder",
			"A3_Atlas_Data_F_Atlas_Loadorder"
		};
		author = "Axle";
		skipwhenmissingdependencies = 1;
	};
};

class cfgWeapons
{
	class H_HelmetAggressor_F;
	class H_HelmetHeavy_Black_RF: H_HelmetAggressor_F
	{
	};
	class SMG_02_F;
	class srifle_DMR_01_black_RF;
	class arifle_ash12_blk_RF;
	class arifle_ash12_LR_blk_RF;
	class arifle_ash12_GL_blk_RF;
	class AX_arifle_ash12_blk_ACO_Pointer_RF: arifle_ash12_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_ACO_grn";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class AX_arifle_ash12_LR_blk_vrco_Pointer_RF: arifle_ash12_LR_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_VRCO_RF";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class AX_arifle_ash12_GL_blk_ACO_Pointer_RF: arifle_ash12_GL_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_ACO_grn";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class AX_arifle_ash12_GL_blk_Pointer_RF: arifle_ash12_GL_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class AX_srifle_DMR_01_black_DMS_BI_Pointer_RF: srifle_DMR_01_black_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_DMS";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_02_F_blk";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
		};
	};
	class AX_srifle_DMR_01_black_DMS_BI_Pointer_snds_RF: srifle_DMR_01_black_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_DMS";
			};
			class LinkedItemsMuzzle
			{
				slot="MuzzleSlot";
				item="aegis_muzzle_snds_pbs_762_blk";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_02_F_blk";
			};
		};
	};
	class AX_srifle_DMR_01_black_ARCO_IRFL_BI_F: srifle_DMR_01_black_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_Arco_blk_F";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="saber_light_ir_lxWS";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_02_F_blk";
			};
		};
	};
	class AX_arifle_ash12_LR_blk_DMS_BI_Pointer_RF: arifle_ash12_LR_blk_RF
	{
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_DMS_weathered_Kir_F";
			};
			class LinkedItemsAcc
			{
				slot="PointerSlot";
				item="acc_pointer_IR";
			};
			class LinkedItemsUnder
			{
				slot="UnderBarrelSlot";
				item="bipod_02_F_blk";
			};
		};
	};
};

class cfgVehicles
{
	class SoldierEB;
	class O_Soldier_base_F: SoldierEB
	{
	};
	class O_Soldier_Urban_base;
	class O_Soldier_recon_base;
	class O_support_AMort_F;
	class O_support_CMort_RF: O_support_AMort_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_support_CMort_RF.jpg";
	};
	class O_Soldier_SL_F;
	class O_Soldier_F;
	class O_Soldier_GL_F;
	class O_medic_F;
	class O_Soldier_AR_F;
	class O_soldier_UAV_F;
	class O_Soldier_HAT_F;
	class O_soldier_M_F: O_Soldier_base_F
	{
		weapons[]=
		{
			"AX_srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_soldierU_M_F: O_Soldier_Urban_base
	{
		weapons[]=
		{
			"AX_srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_01_black_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_recon_M_F: O_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_srifle_DMR_01_black_DMS_BI_Pointer_snds_RF",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_01_black_DMS_BI_Pointer_snds_RF",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_QRF_Soldier_SL_RF: O_Soldier_SL_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_Soldier_SL_RF.jpg";
        uniformClass="AX_U_CombatUniform_PCU_chex_01_F";
		backpack="AX_B_TacticalPack_blk_SL_QRF";
		weapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_Beret_csat_nohed_grn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_O_NVGoggles_blk_hidden_headset_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_Beret_csat_nohed_grn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_O_NVGoggles_blk_hidden_headset_F"
		};
	};
	class O_QRF_Soldier_RF: O_Soldier_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_Soldier_RF.jpg";
        uniformClass="AX_U_CombatUniform_PCU_chex_01_F";
		backpack="AX_B_TacticalPack_blk_RI_QRF";
		weapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class O_QRF_Soldier_GL_RF: O_Soldier_GL_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_Soldier_GL_RF.jpg";
		uniformClass="AX_U_CombatUniform_PCU_chex_02_F";
		backpack="AX_B_TacticalPack_blk_GL_QRF";
		weapons[]=
		{
			"AX_arifle_ash12_GL_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_ash12_GL_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"1Rnd_HE_Grenade_shell",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"1Rnd_HE_Grenade_shell",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class O_QRF_medic_RF: O_medic_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_medic_RF.jpg";
        uniformClass="AX_U_CombatUniform_PCU_chex_02_F";
		backpack="AX_B_FieldPack_blk_Medic_QRF";
		weapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_Beret_csat_nohed_grn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_O_NVGoggles_blk_hidden_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_Beret_csat_nohed_grn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_O_NVGoggles_blk_hidden_F"
		};
	};
	class O_QRF_Soldier_AR_RF: O_Soldier_AR_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_Soldier_AR_RF.jpg";
        uniformClass="AX_U_CombatUniform_PCU_chex_01_F";
		backpack="AX_B_TacticalPack_blk_AR_QRF";
		weapons[]=
		{
			"LMG_Zafir_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"LMG_Zafir_pointer_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"150Rnd_762x54_Box",
			"150Rnd_762x54_Box",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class O_QRF_soldier_M_RF: O_soldier_M_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_soldier_M_RF.jpg";
        uniformClass="AX_U_CombatUniform_PCU_chex_02_F";
		backpack="AX_B_TacticalPack_blk_M_QRF";
		weapons[]=
		{
			"AX_arifle_ash12_LR_blk_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"AX_arifle_ash12_LR_blk_DMS_BI_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class O_QRF_Soldier_UAV_RF: O_soldier_UAV_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_Soldier_UAV_RF.jpg";
        uniformClass="AX_U_CombatUniform_PCU_chex_02_F";
		weapons[]=
		{
			"AX_arifle_ash12_GL_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_ash12_GL_blk_ACO_Pointer_RF",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_SmokeRed_shell_RF",
			"1Rnd_RC40_SmokeGreen_shell_RF",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_HE_shell_RF",
			"1Rnd_RC40_SmokeRed_shell_RF",
			"1Rnd_RC40_SmokeGreen_shell_RF",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class O_QRF_Soldier_HAT_RF: O_Soldier_HAT_F
	{
		editorSubcategory="EdSubcat_Personnel_IRABSF";
		editorPreview="\ax_grounded_futura\editor_previews_iran\futura\O_QRF_Soldier_HAT_RF.jpg";
        uniformClass="AX_U_CombatUniform_PCU_chex_02_F";
		backpack="AX_B_FieldPack_blk_HAT_QRF";
		weapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"launch_O_Vorona_brown_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_ash12_blk_ACO_Pointer_RF",
			"launch_O_Vorona_brown_F",
			"hgun_Rook40_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Vorona_HEAT",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		respawnMagazines[]=
		{
			"20Rnd_127x55_Mag_RF",
			"20Rnd_127x55_Mag_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Vorona_HEAT",
			"SmokeShell",
			"SmokeShellRed",
			"Chemlight_red",
			"Chemlight_red"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_MilCap_chex",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_blk_F"
		};
	};
	class Atlas_O_Soldier_R_base_F: O_Soldier_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_Medic_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
	};
	class Atlas_O_Soldier_R_Exp_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_GL_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell"
		};
	};
  	class Atlas_O_Soldier_R_M_F: Atlas_O_Soldier_R_base_F
	{
		weapons[]=
		{
			"AX_srifle_DMR_01_black_ARCO_IRFL_BI_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_01_black_ARCO_IRFL_BI_F",
			"hgun_Rook40_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class Atlas_O_Soldier_R_AA_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AA",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AA",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_AT_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AT",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"Titan_AT",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_LAT_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"RPG32_F",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"RPG32_F",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShell"
		};
	};
	class Atlas_O_Soldier_R_SL_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"HandGrenade_East",
			"HandGrenade_East",
			"O_IR_Grenade",
			"O_IR_Grenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
	};
	class Atlas_O_Soldier_R_TL_F: Atlas_O_Soldier_R_base_F
	{
		magazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"Aegis_20Rnd_65x39_caseless_green_mag_Tracer_RF",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"HandGrenade_East",
			"HandGrenade_East",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeRed_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell",
			"1Rnd_SmokeYellow_Grenade_shell"
		};
	};
};