    class O_Soldier_A_F;
    class O_Soldier_AAR_F;
	class O_support_AMG_F;
	class O_support_AMort_F;
    class O_Soldier_AHAT_F;
	class O_Soldier_AAA_F;
	class O_Soldier_AAT_F;
	class O_Soldier_AR_F;
	class O_medic_F;
	class O_crew_F;
	class O_engineer_F;
	class O_soldier_exp_F;
	class O_Soldier_GL_F;
	class O_support_GMG_F;
	class O_support_MG_F;
	class O_support_Mort_F;
    class O_HeavyGunner_F;
	class O_helicrew_F;
	class O_helipilot_F;
	class O_soldier_M_F;
	class O_Soldier_AA_F;
	class O_Soldier_AT_F;
	class O_officer_F;
	class O_soldier_PG_F;
	class O_Pilot_F;
	class O_soldier_repair_F;
	class O_Soldier_F;
	class O_Soldier_LAT_F;
    class O_Soldier_HAT_F;
    class O_Soldier_lite_F;
    class O_Soldier_CQ_F;
	class O_Sharpshooter_F;
	class O_Soldier_SL_F;
	class O_Soldier_TL_F;
    class O_soldier_UAV_F;
	class O_recon_exp_F;
	class O_recon_JTAC_F;
	class O_recon_M_F;
	class O_recon_medic_F;
	class O_recon_F;
	class O_recon_LAT_F;
	class O_recon_TL_F;
	class O_recon_CQ_F;
	class O_recon_AR_F;
	class O_recon_GL_F;
	class O_Pathfinder_F;
	class O_Fighter_Pilot_F;
	class O_T_Soldier_A_F: O_Soldier_A_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_A_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_AAR_F: O_Soldier_AAR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_AAR_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Support_AMG_F: O_support_AMG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Support_AMG_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Support_AMort_F: O_support_AMort_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Support_AMort_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_AHAT_F: O_Soldier_AHAT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_AHAT_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
	class O_T_Soldier_AAA_F: O_Soldier_AAA_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_AAA_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_AAT_F: O_Soldier_AAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_AAT_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_AR_F: O_Soldier_AR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_AR_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTARS_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTARS_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_CQB_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_CQB_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
    class O_T_Medic_F: O_medic_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Medic_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_CQB_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_CQB_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Crew_F: O_crew_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Crew_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"H_HelmetCrew_O_ghex_F",
			"Atlas_V_OCarrierRig_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_O_ghex_F",
			"Atlas_V_OCarrierRig_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Engineer_F: O_engineer_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Engineer_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_Exp_F: O_soldier_exp_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_Exp_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_GL_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_GL_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_soldier_mine_F: O_T_Soldier_Exp_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_soldier_mine_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
	};
	class O_T_Soldier_GL_F: O_Soldier_GL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_GL_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_GL_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_GL_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Support_GMG_F: O_support_GMG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Support_GMG_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
    class O_T_Support_MG_F: O_support_MG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Support_MG_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Support_Mort_F: O_support_Mort_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Support_Mort_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
    class O_T_HeavyGunner_F: O_HeavyGunner_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_HeavyGunner_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"MMG_01_ghex_ARCO_LP_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MMG_01_ghex_ARCO_LP_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_CQB_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_CQB_GHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
	class O_T_Helicrew_F: O_helicrew_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Helicrew_F.jpg";
        uniformClass="U_O_T_Pilot_F";
        linkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Helipilot_F: O_helipilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Helipilot_F.jpg";
        uniformClass="U_O_T_Pilot_F";
        linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_M_F: O_soldier_M_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_M_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"srifle_DMR_07_blk_DMS_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_07_blk_DMS_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_AA_F: O_Soldier_AA_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_AA_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_O_Titan_ghex_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_O_Titan_ghex_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_AT_F: O_Soldier_AT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_AT_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_O_Titan_short_ghex_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_O_Titan_short_ghex_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Officer_F: O_officer_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Officer_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_officer"
		};
        uniformClass="U_O_T_Officer_F";
		weapons[]=
		{
			"arifle_CTAR_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
		respawnMagazines[]=
		{
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"30Rnd_580x42_Mag_F",
			"17Rnd_9x21_Mag",
			"17Rnd_9x21_Mag",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellYellow"
		};
        linkedItems[]=
		{
			"AX_H_Beret_CSAT_red",
			"V_Rangemaster_belt_ghex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_H_Beret_CSAT_red",
			"V_Rangemaster_belt_ghex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_T_Soldier_PG_F: O_soldier_PG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_PG_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Pilot_F: O_Pilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Pilot_F.jpg";
        uniformClass="U_O_T_Pilot_F";
        linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_Repair_F: O_soldier_repair_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_Repair_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_F: O_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Fighter_Pilot_F: O_Fighter_Pilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Fighter_Pilot_F.jpg";
		weapons[]=
		{
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"H_PilotHelmetFighter_O",
			"AX_G_Balaclava_nylon_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetFighter_O",
			"AX_G_Balaclava_nylon_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_T_Soldier_CBRN_F: O_T_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_CBRN_F.jpg";
        uniformClass="AX_U_O_CBRN_Suit_01_GHex_F";
		backpack="B_CombinationUnitRespirator_01_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
            "ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
            "ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
	class O_T_RadioOperator_F: O_T_Soldier_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_RadioOperator_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
    class O_T_Soldier_LAT_F: O_Soldier_LAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_LAT_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_RPG32_ghex_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_RPG32_ghex_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_HAT_F: O_Soldier_HAT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_HAT_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_O_Vorona_green_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_O_Vorona_green_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
	class O_T_Soldier_Lite_F: O_Soldier_lite_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_Lite_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
    };
	class O_T_Soldier_CQ_F: O_Soldier_CQ_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_CQ_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"Aegis_sgun_AA40_ACO_LP_LxWS",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_sgun_AA40_ACO_LP_LxWS",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
	class O_T_Soldier_unarmed_F: O_T_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_unarmed_F.jpg";
		uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class O_T_Sharpshooter_F: O_Sharpshooter_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Sharpshooter_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"srifle_DMR_05_KHS_LP_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_05_KHS_LP_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_SL_F: O_Soldier_SL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_SL_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_TL_F: O_Soldier_TL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_TL_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_GL_GHex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_GL_GHex_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Soldier_UAV_F: O_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_UAV_F.jpg";
		identityTypes[]=
		{
			"LanguageCHI_F",
			"Head_Asian",
			"G_CHINA_default"
		};
        uniformClass="Aegis_U_O_CombatFatigues_02_ghex_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_ghex_F",
			"Atlas_V_OCarrierRig_Lite_gHex_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_soldier_UAV_06_F: O_T_Soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_soldier_UAV_06_F.jpg";
	};
	class O_T_soldier_UAV_06_medical_F: O_T_Soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_soldier_UAV_06_medical_F.jpg";
	};
	class O_T_Soldier_UAV_02_lxWS_F: O_T_Soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Soldier_UAV_02_lxWS_F.jpg";
	};
	class O_T_soldier_UGV_02_Demining_F: O_T_Soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_soldier_UGV_02_Demining_F.jpg";
	};
	class O_T_Survivor_F: O_T_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Survivor_F.jpg";
	};
	class O_T_Recon_Exp_F: O_recon_exp_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_Exp_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"V_HarnessO_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessO_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_JTAC_F: O_recon_JTAC_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_JTAC_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02_ghex_F"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02_ghex_F"
		};
		linkedItems[]=
		{
			"AX_H_HelmetAggressor_ghex_F",
			"V_HarnessOGL_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetAggressor_ghex_F",
			"V_HarnessOGL_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_M_F: O_recon_M_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_M_F.jpg";
		weapons[]=
		{
			"srifle_DMR_07_blk_DMS_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_07_blk_DMS_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"V_TacVest_oli",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_Medic_F: O_recon_medic_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_Medic_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_H_HelmetAggressor_ghex_F",
			"V_HarnessO_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"AX_H_HelmetAggressor_ghex_F",
			"V_HarnessO_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_F: O_recon_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"V_HarnessOSpec_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOSpec_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_LAT_F: O_recon_LAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_LAT_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"launch_RPG32_ghex_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_Snds_F",
			"launch_RPG32_ghex_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"V_TacVest_oli",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_TL_F: O_recon_TL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_TL_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"V_HarnessOSpec_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOSpec_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_CQ_F: O_recon_CQ_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_CQ_F.jpg";
		weapons[]=
		{
			"Aegis_sgun_AA40_ACO_LP_snds_LxWS",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_sgun_AA40_ACO_LP_snds_LxWS",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"V_TacVest_oli",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_oli",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_AR_F: O_recon_AR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_AR_F.jpg";
		weapons[]=
		{
			"arifle_CTARS_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTARS_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"V_HarnessOSpec_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOSpec_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Recon_GL_F: O_recon_GL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Recon_GL_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"V_HarnessOGL_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOGL_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
	class O_T_Pathfinder_F: O_Pathfinder_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\O_T_Pathfinder_F.jpg";
		weapons[]=
		{
			"srifle_DMR_04_NS_LP_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02_ghex_F"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_04_NS_LP_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02_ghex_F"
		};
		linkedItems[]=
		{
			"V_HarnessO_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessO_ghex_F",
			"AX_H_HelmetAggressor_ghex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
	};
