    class Aegis_O_C_D_Soldier_A_F: O_T_Soldier_A_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_A_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_AAR_F: O_T_Soldier_AAR_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_AAR_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Support_AMG_F: O_T_Support_AMG_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Support_AMG_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Support_AMort_F: O_T_Support_AMort_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Support_AMort_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_AHAT_F: O_T_Soldier_AHAT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_AHAT_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_AAA_F: O_T_Soldier_AAA_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_AAA_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_AAT_F: O_T_Soldier_AAT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_AAT_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_AR_F: O_T_Soldier_AR_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_AR_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTARS_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTARS_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_CQB_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_CQB_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Medic_F: O_T_Medic_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Medic_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_CQB_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_CQB_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Crew_F: O_T_Crew_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Crew_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_f",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_f",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"H_HelmetCrew_O",
			"Atlas_V_OCarrierRig_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_HelmetCrew_O",
			"Atlas_V_OCarrierRig_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Engineer_F: O_T_Engineer_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Engineer_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_Exp_F: O_T_Soldier_Exp_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_Exp_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_Mine_F: O_T_soldier_mine_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_Mine_F.jpg";
		Author="$STR_A3_A_Ravenholme";
		faction="OPF_CD_F";
		uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		backpack="B_Carryall_ghex_Mine";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_GL_F: O_T_Soldier_GL_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_GL_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_GL_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_GL_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Support_GMG_F: O_T_Support_GMG_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Support_GMG_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Support_MG_F: O_T_Support_MG_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Support_MG_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Support_Mort_F: O_T_Support_Mort_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Support_Mort_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_HeavyGunner_F: O_T_HeavyGunner_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_HeavyGunner_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_MMG_01_tan_ARCO_LP_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_MMG_01_tan_ARCO_LP_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_CQB_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_CQB_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Helicrew_F: O_T_Helicrew_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Helicrew_F.jpg";
        uniformClass="U_O_PilotCoveralls";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_CrewHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Helipilot_F: O_T_Helipilot_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Helipilot_F.jpg";
        uniformClass="U_O_PilotCoveralls";
        linkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_O",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_M_F: O_T_Soldier_M_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_M_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_AA_F: O_T_Soldier_AA_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_AA_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"launch_O_Titan_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"launch_O_Titan_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_AT_F: O_T_Soldier_AT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_AT_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"launch_O_Titan_short_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"launch_O_Titan_short_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Officer_F: O_T_Officer_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Officer_F.jpg";
        uniformClass="U_O_OfficerUniform_oicamo";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"AX_H_Beret_CSAT_red",
			"V_Rangemaster_belt_cbr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_H_Beret_CSAT_red",
			"V_Rangemaster_belt_cbr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class Aegis_O_C_D_Soldier_PG_F: O_T_Soldier_PG_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_PG_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Pilot_F: O_T_Pilot_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Pilot_F.jpg";
		uniformClass="U_O_PilotCoveralls";
    };
	class Aegis_O_C_D_Soldier_Repair_F: O_T_Soldier_Repair_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_Repair_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_F: O_T_Soldier_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Fighter_Pilot_F: O_T_Fighter_Pilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Fighter_Pilot_F.jpg";
		uniformClass="U_O_PilotCoveralls";
	};
	class Aegis_O_C_D_Soldier_CBRN_F: O_T_Soldier_CBRN_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_CBRN_F.jpg";
        uniformClass="AX_U_O_CBRN_Suit_01_DHex_F";
		backpack="B_CombinationUnitRespirator_01_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"G_AirPurifyingRespirator_02_sand_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"G_AirPurifyingRespirator_02_sand_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
    class Aegis_O_C_D_RadioOperator_F: O_T_RadioOperator_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_RadioOperator_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_LAT_F: O_T_Soldier_LAT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_LAT_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_HAT_F: O_T_Soldier_HAT_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_HAT_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"launch_O_Vorona_brown_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"launch_O_Vorona_brown_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_Lite_F: O_T_Soldier_Lite_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_Lite_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
        linkedItems[]=
		{
			"H_MilCap_oicamo",
			"V_BandollierB_cbr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"H_MilCap_oicamo",
			"V_BandollierB_cbr",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_CQ_F: O_T_Soldier_CQ_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_CQ_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_sgun_AA40_tan_ACO_LP_LxWS",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_sgun_AA40_tan_ACO_LP_LxWS",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_unarmed_F: O_T_Soldier_unarmed_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_unarmed_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class Aegis_O_C_D_Sharpshooter_F: O_T_Sharpshooter_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Sharpshooter_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_SL_F: O_T_Soldier_SL_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_SL_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Binocular",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_TL_F: O_T_Soldier_TL_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_TL_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_GL_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Binocular",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_GL_tan_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Binocular",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_GL_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_UAV_F: O_T_Soldier_UAV_F
    {
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_UAV_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_UAV_06_F: O_T_soldier_UAV_06_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_UAV_06_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_UAV_06_medical_F: O_T_soldier_UAV_06_medical_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_UAV_06_medical_F.jpg";
        uniformClass="Aegis_U_O_CombatFatigues_02_dst_F";
		weapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Aegis_arifle_CTAR_tan_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"Atlas_H_HelmetCCH_Cover_dst_F",
			"Atlas_V_OCarrierRig_Lite_Dst_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal",
			"O_NVGoggles_hex_F"
		};
    };
	class Aegis_O_C_D_Soldier_UGV_02_Demining_F: Aegis_O_C_D_Soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Soldier_UGV_02_Demining_F.jpg";
	};
	class Aegis_O_C_D_Recon_Exp_F: O_T_Recon_Exp_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_Exp_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_HarnessO_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessO_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_JTAC_F: O_T_Recon_JTAC_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_JTAC_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put",
            "Laserdesignator_02"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put",
            "laserdesignator_02"
        };
		linkedItems[]=
		{
			"V_HarnessOGL_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOGL_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_M_F: O_T_Recon_M_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_M_F.jpg";
		linkedItems[]=
		{
			"V_TacVest_brn",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_brn",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_Medic_F: O_T_Recon_Medic_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_Medic_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_HarnessO_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessO_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_F: O_T_Recon_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTAR_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTAR_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_HarnessOSpec_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOSpec_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_LAT_F: O_T_Recon_LAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_LAT_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "launch_RPG32_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTAR_tan_ACO_Pointer_Snds_F",
            "launch_RPG32_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_TacVest_brn",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_brn",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_TL_F: O_T_Recon_TL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_TL_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTAR_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Rangefinder",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTAR_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Rangefinder",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_HarnessOSpec_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOSpec_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_CQ_F: O_T_Recon_CQ_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_CQ_F.jpg";
        weapons[]=
        {
            "Aegis_sgun_AA40_tan_ACO_LP_snds_LxWS",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_sgun_AA40_tan_ACO_LP_snds_LxWS",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_TacVest_brn",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_brn",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_AR_F: O_T_Recon_AR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_AR_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTARS_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTARS_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_HarnessOSpec_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOSpec_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Recon_GL_F: O_T_Recon_GL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Recon_GL_F.jpg";
        weapons[]=
        {
            "Aegis_arifle_CTAR_GL_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "Aegis_arifle_CTAR_GL_tan_ARCO_Pointer_Snds_F",
            "AX_hgun_QSZ92_snds_F",
            "Throw",
            "Put"
        };
		linkedItems[]=
		{
			"V_HarnessOGL_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessOGL_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Pathfinder_F: O_T_Pathfinder_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\expansion\Aegis_O_C_D_Pathfinder_F.jpg";
		linkedItems[]=
		{
			"V_HarnessO_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"V_HarnessO_oicamo",
			"AX_H_HelmetAggressor_dhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};