class CfgPatches
{
	class sog_wbk_shoulderlight
	{
		units[]={};
		weapons[]={};
		requiredAddons[]=
		{
			"WBK_Headlamps",
			"loadorder_f_vietnam"
		};
		requiredVersion=0.1;
		author="Axle";
		skipwhenmissingdependencies=1;
	}; 
};

class cfgVehicles
{
	class vn_b_men_army_base;
	class vn_b_men_lrrp_base;
	class vn_b_men_rok_army_68_base;
	class vn_b_men_rok_army_65_base;
	class vn_b_men_rok_marine_68_base;
	class vn_b_men_rok_marine_65_base;
	class vn_i_men_army_base;
	class vn_b_men_lrrp_09: vn_b_men_lrrp_base
	{
		weapons[]=
		{
			"vn_m79",
			"vn_m1911_sd",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m79",
			"vn_m1911_sd",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
		respawnItems[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
	};
	class vn_b_men_army_09: vn_b_men_army_base
	{
		weapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
		respawnItems[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
	};
	class vn_b_men_rok_army_68_09: vn_b_men_rok_army_68_base
	{
		weapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
		respawnItems[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
	};
	class vn_b_men_rok_army_65_09: vn_b_men_rok_army_65_base
	{
		weapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
		respawnItems[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
	};
	class vn_b_men_rok_marine_68_09: vn_b_men_rok_marine_68_base
	{
		weapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
		respawnItems[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
	};
	class vn_b_men_rok_marine_65_09: vn_b_men_rok_marine_65_base
	{
		weapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m1897",
			"vn_m1911_sd",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		Items[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
		respawnItems[]=
		{
			"vn_b_item_firstaidkit",
			"AX_ShoulderLampItem_Regular"
		};
	};
	class vn_i_men_army_09: vn_i_men_army_base
	{
		weapons[]=
		{
			"vn_m1897",
			"vn_m1911",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
		respawnweapons[]=
		{
			"vn_m1897",
			"vn_m1911",
			"vn_m19_binocs_grn",
			"Throw",
			"Put"
		};
	};
};