#include "\vn\modules_f_vietnam\vn_sam_defines.inc"
/*
    File: fn_sam_globals.sqf
    Author: veteran29
    Date: 2022-07-15
    Last Update: 2022-08-11
    Public: No

    Description:
        Initialize global variables for SAM system.

    Parameter(s):
        NONE

    Returns:
        NOTHING

    Example(s):
        [] call vn_fnc_sam_globals;
*/

if (missionNamespace getVariable ["vn_sam_globals_initialized", false]) exitWith {};
vn_sam_globals_initialized = true;

// Mapping of [faction, face] or unit side as a fallback to the voiceset
vn_sam_voiceHash = createHashMapFromArray [

	[["B_MACV", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_MACV", SAM_FACE_ASIAN], SAM_VOICE_INDIGENOUS],
	
	[["B_vn_USARMY", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USARMY", SAM_FACE_ASIAN], SAM_VOICE_AMERICAN],
	
	[["B_vn_USARMY_65", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USARMY_65", SAM_FACE_ASIAN], SAM_VOICE_INDIGENOUS],
	
	[["B_vn_USN", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USN", SAM_FACE_ASIAN], SAM_VOICE_INDIGENOUS],
	
	[["B_vn_USAF", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USAF", SAM_FACE_ASIAN], SAM_VOICE_AMERICAN],
	
	[["B_vn_USMC_68", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USMC_68", SAM_FACE_ASIAN], SAM_VOICE_INDIGENOUS],
	
	[["B_vn_USMC_66", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USMC_66", SAM_FACE_ASIAN], SAM_VOICE_INDIGENOUS],
	
	[["B_vn_USMC_70", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USMC_70", SAM_FACE_ASIAN], SAM_VOICE_INDIGENOUS],
	
	[["B_CIA", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_CIA", SAM_FACE_ASIAN], SAM_VOICE_INDIGENOUS],
	
	[["B_MEDT", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_MEDT", SAM_FACE_ASIAN], SAM_VOICE_AMERICAN],
	
	[["B_vn_USSF", SAM_FACE_WHITE], SAM_VOICE_AMERICAN],
	[["B_vn_USSF", SAM_FACE_ASIAN], SAM_VOICE_AMERICAN],
	

	// TODO new faction B_MACV_ARMY (?) so asian faces in the army will speak american

	[["B_AUS", SAM_FACE_WHITE],  SAM_VOICE_AUSTRALIAN],
	[["B_AUS", SAM_FACE_ASIAN],  SAM_VOICE_AUSTRALIAN],
	
	[["B_vn_AUS_66", SAM_FACE_WHITE],  SAM_VOICE_AUSTRALIAN],
	[["B_vn_AUS_66", SAM_FACE_ASIAN],  SAM_VOICE_AUSTRALIAN],
	
	[["B_vn_AUS_70", SAM_FACE_WHITE],  SAM_VOICE_AUSTRALIAN],
	[["B_vn_AUS_70", SAM_FACE_ASIAN],  SAM_VOICE_AUSTRALIAN],
	
	[["B_vn_AUS_SASR", SAM_FACE_WHITE],  SAM_VOICE_AUSTRALIAN],
	[["B_vn_AUS_SASR", SAM_FACE_ASIAN],  SAM_VOICE_AUSTRALIAN],
	
	[["B_NZ", SAM_FACE_WHITE],   SAM_VOICE_NEW_ZEALAND],
	[["B_NZ", SAM_FACE_ASIAN],   SAM_VOICE_NEW_ZEALAND],
	
	[["B_vn_NZ_66", SAM_FACE_WHITE],  SAM_VOICE_NEW_ZEALAND],
	[["B_vn_NZ_66", SAM_FACE_ASIAN],  SAM_VOICE_NEW_ZEALAND],
	
	[["B_vn_NZ_70", SAM_FACE_WHITE],  SAM_VOICE_NEW_ZEALAND],
	[["B_vn_NZ_70", SAM_FACE_ASIAN],  SAM_VOICE_NEW_ZEALAND],
	
	[["B_vn_NZ_SAS", SAM_FACE_WHITE],   SAM_VOICE_NEW_ZEALAND],
	[["B_vn_NZ_SAS", SAM_FACE_ASIAN],   SAM_VOICE_NEW_ZEALAND],

	//Vietnamese Voices
	[["O_PAVN", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_PAVN", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_PAVN_65", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_PAVN_65", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_PAVN_75", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_PAVN_75", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_PAVN_DC", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_PAVN_DC", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_VPN", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_VPN", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_VPN_marines", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_VPN_marines", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_VPAF", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_VPAF", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_VC", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_VC", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_VC_regional", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_VC_regional", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
	[["O_vn_VC_local", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
	[["O_vn_VC_local", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
//	[["O_CAM", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
//	[["O_CAM", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],
	
//	[["O_vn_CAM_75", SAM_FACE_WHITE],   SAM_VOICE_VIETNAMESE],
//	[["O_vn_CAM_75", SAM_FACE_ASIAN],   SAM_VOICE_VIETNAMESE],

	//Indigenous
	[["I_ARVN", SAM_FACE_WHITE],   SAM_VOICE_INDIGENOUS],
	[["I_ARVN", SAM_FACE_ASIAN],   SAM_VOICE_INDIGENOUS],
	
	[["I_vn_ARVN_65", SAM_FACE_WHITE],   SAM_VOICE_INDIGENOUS],
	[["I_vn_ARVN_65", SAM_FACE_ASIAN],   SAM_VOICE_INDIGENOUS],
	
	[["I_vn_ARVN_75", SAM_FACE_WHITE],   SAM_VOICE_INDIGENOUS],
	[["I_vn_ARVN_75", SAM_FACE_ASIAN],   SAM_VOICE_INDIGENOUS],
	
	[["I_vn_ARVN_marines", SAM_FACE_WHITE],   SAM_VOICE_INDIGENOUS],
	[["I_vn_ARVN_marines", SAM_FACE_ASIAN],   SAM_VOICE_INDIGENOUS],
	
	[["I_vn_ARVN_sf", SAM_FACE_WHITE],   SAM_VOICE_INDIGENOUS],
	[["I_vn_ARVN_sf", SAM_FACE_ASIAN],   SAM_VOICE_INDIGENOUS],
	
	// The 'SAM_VOICE_VN_CIVILIAN' index is muted
	
	[["B_ROK", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	[["B_vn_ROK_army_65", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["B_vn_ROK_marines_68", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	[["B_vn_ROK_marines_65", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["B_vn_KOT_army_68", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["I_LAO", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],

	//[["I_vn_PRC", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	[["I_vn_PRC_Adv", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],

	[["O_PL", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],

	[["O_vn_USSR_Adv", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["O_vn_USSR_Adv", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],

/*
	//Extra Factions
	[["BLU_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["BLU_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["BLU_G_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["BLU_G_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["BLU_T_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["BLU_T_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["BLU_W_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["BLU_W_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["BLU_CTRG_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["BLU_CTRG_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["BLU_GEN_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["BLU_GEN_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["IND_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["IND_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["IND_G_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["IND_G_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["IND_C_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["IND_C_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["IND_E_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["IND_E_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["IND_L_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["IND_L_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],

	[["OPF_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["OPF_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["OPF_G_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["OPF_G_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["OPF_T_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["OPF_T_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
	
	[["OPF_R_F", SAM_FACE_WHITE],  SAM_VOICE_VN_CIVILIAN],
	[["OPF_R_F", SAM_FACE_ASIAN],  SAM_VOICE_VN_CIVILIAN],
*/
	// defaults for side
	[WEST, SAM_VOICE_AMERICAN],
	[EAST, SAM_VOICE_VIETNAMESE],
	[INDEPENDENT, SAM_VOICE_INDIGENOUS],
	[CIVILIAN, SAM_VOICE_VN_CIVILIAN]
];

nil
