    class G_Balaclava_blk: None
	{
		identityTypes[]=
		{
			"G_RUS_default",
			25,
			"G_RUS_SF",
			25,
			"NoGlasses",
			0,
			"G_IRAN_SF",
			0
		};
	};
	class AX_G_Balaclava_combat_blk_lxWS: G_Balaclava_combat
	{
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Balaclava_combat_blk_lxWS";
		hiddenSelectionsTextures[]=
		{
			"\lxws\characters_f_lxws\headgear\a3\data\headgear_balaclava_blk_co.paa",
			"\ax_grounded_futura\characters_f_iran\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\lxws\characters_f_lxws\headgear\a3\data\headgear_balaclava.rvmat"
		};
		identityTypes[]={};
	};
	class AX_G_Bandanna_blk_ir: G_Bandanna_blk
	{
		scope=1;
        scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_IRAN_default",
			250
		};
	};
	class AX_G_Shemag_tan_ir: G_Shemag_tan
	{
		scope=1;
        scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_IRAN_default",
			500
		};
	};
	class AX_G_Lowprofile_ir: G_Lowprofile
	{
		scope=1;
        scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_IRAN_default",
			250
		};
	};
	class AX_G_Squares_ir: G_Squares
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\facewear\data\G_Square_Spectacles_CO.paa"
		};
		identityTypes[]=
		{
			"G_IRAN_default",
			100
		};
	};
	class AX_G_Headset_light_ir: G_Headset_light
	{
		scope=1;
		scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_IRAN_officer",
			400
		};
	};
	class AX_G_Balaclava_blk_lxWS_ir: G_Balaclava_blk_lxWS
	{
		scope=1;
        scopeArsenal=1;
		author="$STR_A3_GRFU_Axle";
		identityTypes[]=
		{
			"G_IRAN_SF",
			100,
			"G_IRAN_default",
			100
		};
	};
	class AX_G_Balaclava_mesh_blk_ir: G_Balaclava_TI_blk_F
	{
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Balaclava_mesh_blk_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\facewear\data\G_Balaclava_mesh_blk_F_CO.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_iran\facewear\data\G_Mesh_Balaclava.rvmat"
		};
		identityTypes[]={};
		mass=6;
	};
	class AX_G_Balaclava_mesh_G_blk_ir: G_Balaclava_TI_G_blk_F
	{
		author="$STR_A3_GRFU_Axle";
		displayName="$STR_A3_GRFU_G_Balaclava_mesh_G_blk_F0";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\facewear\data\G_Balaclava_mesh_blk_F_CO.paa",
			"\ax_grounded_futura\characters_f_iran\facewear\data\G_Combat_Goggles_blk_tint_F_CA.paa"
		};
		hiddenSelectionsMaterials[]=
		{
			"\ax_grounded_futura\characters_f_iran\facewear\data\G_Mesh_Balaclava.rvmat"
		};
		identityTypes[]={};
		mass=6;
	};
	