    class AX_O_CBRN_Man_Oversuit_01_Hex_F: B_CBRN_Man_Oversuit_01_MTP_F
	{
		uniformClass="AX_U_O_CBRN_Suit_01_Hex_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CBRN_Suit_01_Hex_CO.paa"
		};
	};
	class AX_O_CBRN_Man_Oversuit_01_UHex_F: B_CBRN_Man_Oversuit_01_MTP_F
	{
		uniformClass="AX_U_O_CBRN_Suit_01_UHex_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CBRN_Suit_01_UHex_CO.paa"
		};
	};
    class AX_uniform_CombatUniform_PCU_hex_01_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_CombatUniform_PCU_hex_01_F";
		model="\ax_grounded_futura\characters_f_iran\uniforms\U_UniformPCU_01_F.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
    };
	class AX_uniform_CombatUniform_PCU_uhex_01_F: AX_uniform_CombatUniform_PCU_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_CombatUniform_PCU_uhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};
	 class AX_uniform_CombatUniform_PCU_hex_02_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_CombatUniform_PCU_hex_02_F";
		model="\ax_grounded_futura\characters_f_iran\uniforms\U_UniformPCU_02_F.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
    };
	class AX_uniform_CombatUniform_PCU_uhex_02_F: AX_uniform_CombatUniform_PCU_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_CombatUniform_PCU_uhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};
	class AX_uniform_OfficerUniform_PCU_hex_01_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_OfficerUniform_PCU_hex_01_F";
		model="\ax_grounded_futura\characters_f_iran\uniforms\U_UniformPCU_Officer_01_F.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_officer_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
    };
	class AX_uniform_OfficerUniform_PCU_uhex_01_F: AX_uniform_OfficerUniform_PCU_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_OfficerUniform_PCU_uhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_officer_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};
	class AX_uniform_OfficerUniform_PCU_hex_02_F: O_A_officer_F
	{
		scope=1;
		scopeCurator=0;
		modelSides[]={6};
		uniformClass="AX_U_OfficerUniform_PCU_hex_02_F";
		model="\ax_grounded_futura\characters_f_iran\uniforms\U_UniformPCU_Officer_02_F.p3d";
		hiddenSelections[]=
		{
			"camo",
			"camo1",
			"camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_officer_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
		class Wounds
		{
			tex[]={};
			mat[]=
			{
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"A3_Atlas\Characters_F_Atlas\Uniforms\Data\U_UniformBDU_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"a3\characters_f\heads\data\m_white_01_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"A3\Characters_F\Common\Data\basicbody_injury.rvmat",
				"a3\characters_f\heads\data\hl_white.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"a3\characters_f\heads\data\hl_white_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_02_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_black_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_hairy_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_white_old_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F\Heads\Data\hl_asian_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_tanoan_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat",
				"A3\Characters_F_Exp\Heads\Data\hl_asian_02_bald_muscular_injury.rvmat"
			};
		};
		armorstructural=4;
    };
	class AX_uniform_OfficerUniform_PCU_uhex_02_F: AX_uniform_OfficerUniform_PCU_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_OfficerUniform_PCU_uhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_officer_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};
	class AX_uniform_Uniform_PCU_hex_01_F: AX_uniform_OfficerUniform_PCU_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_Uniform_PCU_hex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};
	class AX_uniform_Uniform_PCU_uhex_01_F: AX_uniform_OfficerUniform_PCU_hex_01_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_Uniform_PCU_uhex_01_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};
	class AX_uniform_Uniform_PCU_hex_02_F: AX_uniform_OfficerUniform_PCU_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_Uniform_PCU_hex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_hex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};
	class AX_uniform_Uniform_PCU_uhex_02_F: AX_uniform_OfficerUniform_PCU_hex_02_F
	{
		scope=1;
		scopeCurator=0;
		uniformClass="AX_U_Uniform_PCU_uhex_02_F";
		hiddenSelectionsTextures[]=
		{
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformPCU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\U_UniformBDU_uhex_CO.paa",
			"\ax_grounded_futura\characters_f_iran\uniforms\data\CNGloves_blk_khk_CO.paa"
		};
	};