	class Atlas_O_C_Marine_base_F: O_T_Soldier_F
	{
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_01_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_A_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_A_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_02_F";
	};
    class Atlas_O_C_Marine_AR_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_AR_F.jpg";
		weapons[]=
		{
			"arifle_CTARS_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTARS_blk_ARCO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_OCarrierRig_CQB_blk_MHex_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_CQB_blk_MHex_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_Medic_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_Medic_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_blk_01_F";
		backpack="AX_B_CombatPack_t07_blk_Medic_F";
		linkedItems[]=
		{
			"AX_V_OCarrierRig_CQB_blk_MHex_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_CQB_blk_MHex_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_Engineer_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_Engineer_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_blk_01_F";
		linkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_MHex_F",
			"H_Watchcap_blk",
			"G_AirPurifyingRespirator_02_black_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierRig_Lite_MHex_F",
			"H_Watchcap_blk",
			"G_AirPurifyingRespirator_02_black_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_Exp_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_Exp_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_02_F";
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_GL_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_GL_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_ACO_Pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_HG_F: Atlas_O_C_Marine_base_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_HG_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_blk_mhex_02_F";
		weapons[]=
		{
			"Atlas_MMG_01_black_ARCO_BI_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Atlas_MMG_01_black_ARCO_BI_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"lxWS_H_BMask_base",
			"G_Balaclava_blk_lxWS",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"lxWS_H_BMask_base",
			"G_Balaclava_blk_lxWS",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class Atlas_O_C_Marine_M_F: Atlas_O_C_Marine_base_F
    {
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_M_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_blk_mhex_01_F";
		weapons[]=
		{
			"srifle_DMR_07_blk_DMS_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_DMR_07_blk_DMS_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"Atlas_V_OCarrierRig_lite_blk_F",
			"JAM_AE_H_PLA_Headset_blk",
			"AX_G_Balaclava_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_lite_blk_F",
			"JAM_AE_H_PLA_Headset_blk",
			"AX_G_Balaclava_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class Atlas_O_C_Marine_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_F.jpg";	
	};
	class Atlas_O_C_Marine_AA_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_AA_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_02_F";
		backpack="AX_B_CombatPack_t07_blk_AA_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_B_Titan_Olive_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_B_Titan_Olive_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_AT_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_AT_F.jpg";
		backpack="AX_B_CombatPack_t07_blk_AT_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_I_Titan_short_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_I_Titan_short_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_LAT_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_LAT_F.jpg";
		//backpack="AX_B_CombatPack_t07_blk_LAT_F";
		weapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_RPG32_green_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ACO_Pointer_F",
			"launch_RPG32_green_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_SL_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_SL_F.jpg";
		weapons[]=
		{
			"arifle_CTAR_blk_ARCO_pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_blk_ARCO_pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_TL_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_TL_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_02_F";
		weapons[]=
		{
			"arifle_CTAR_GL_blk_ARCO_pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_CTAR_GL_blk_ARCO_pointer_F",
			"AX_hgun_QSZ92_F",
			"Throw",
			"Put",
			"Binocular"
		};
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_RadioOp_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_RadioOp_F.jpg";
	};
	class Atlas_O_C_Marine_UAV_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_UAV_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_02_F";
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"O_NVGoggles_blk_F",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_Crew_F: Atlas_O_C_Marine_base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Atlas_O_C_Marine_Crew_F.jpg";
		uniformClass="AX_U_O_CombatUniform_T21_T07_mhex_01_F";
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_blk_F",
			"H_tank_black_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_blk_F",
			"H_tank_black_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
