    class O_V_Soldier_base_F: O_Soldier_base_F{};
	class O_V_Soldier_hex_F: O_V_Soldier_base_F
	{
		weapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_V_Soldier_TL_hex_F: O_V_Soldier_base_F
	{
		weapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_V_Soldier_Exp_hex_F: O_V_Soldier_base_F
	{
		weapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
	};
	class O_V_Soldier_Medic_hex_F: O_V_Soldier_base_F
	{
		weapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put"
		};
	};
	class O_V_Soldier_M_hex_F: O_V_Soldier_base_F
	{
		weapons[]=
		{
			"arifle_ARX_hex_DMS_Pointer_Snds_Bipod_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_hex_DMS_Pointer_Snds_Bipod_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_V_Soldier_LAT_hex_F: O_V_Soldier_base_F
	{
		weapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"launch_RPG32_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"launch_RPG32_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
	};
	class O_V_Soldier_JTAC_hex_F: O_V_Soldier_base_F
	{
		weapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_hex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02"
		};
	};
	class O_V_Soldier_ghex_F: O_V_Soldier_hex_F
	{
		weapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
	class O_V_Soldier_TL_ghex_F: O_V_Soldier_TL_hex_F
	{
		weapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
	class O_V_Soldier_Exp_ghex_F: O_V_Soldier_Exp_hex_F
	{
		weapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
	class O_V_Soldier_Medic_ghex_F: O_V_Soldier_Medic_hex_F
	{
		weapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
	class O_V_Soldier_M_ghex_F: O_V_Soldier_M_hex_F
	{
		weapons[]=
		{
			"arifle_ARX_ghex_DMS_Pointer_Snds_Bipod_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_ghex_DMS_Pointer_Snds_Bipod_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
	class O_V_Soldier_LAT_ghex_F: O_V_Soldier_LAT_hex_F
	{
		weapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"launch_RPG32_ghex_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"launch_RPG32_ghex_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
	class O_V_Soldier_JTAC_ghex_F: O_V_Soldier_JTAC_hex_F
	{
		weapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02_ghex_F"
		};
		respawnWeapons[]=
		{
			"arifle_ARX_ghex_ARCO_Pointer_Snds_F",
			"AX_hgun_QSZ92_snds_F",
			"Throw",
			"Put",
			"Laserdesignator_02_ghex_F"
		};
    };