class CfgPatches
{
	class ax_faction_f_us_grfu_reconhood
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"ReconCloaks_Characters_Headgear",
			"ax_faction_f_us_grfu"
		};
		author="Axle";
		skipwhenmissingdependencies=1;
	};
};

class CfgVehicles
{
	class B_Soldier_sniper_base_F;
	class B_sniper_F: B_Soldier_sniper_base_F
	{
		uniformClass="AddGis_U_UniformUS_mcam_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_mcam",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_mcam",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_spotter_F: B_Soldier_sniper_base_F
	{
		uniformClass="AddGis_U_UniformUS_mcam_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_mcam",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_mcam",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class B_T_Sniper_F: B_sniper_F
	{
		uniformClass="AddGis_U_UniformUS_tna_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_T_Spotter_F: B_spotter_F
	{
		uniformClass="AddGis_U_UniformUS_tna_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
    };
	class B_W_Sniper_F: B_sniper_F
	{
		uniformClass="AddGis_U_UniformUS_wdl_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
	class B_W_Spotter_F: B_spotter_F
	{
		uniformClass="AddGis_U_UniformUS_wdl_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_tna",
			"V_Chestrig_rgr",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_INDEP"
		};
	};
};