    class EF_B_Marine_R_Des: EF_B_Marine_Des_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_R_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AR_Des: EF_B_Marine_Des_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AR_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Light_Des: EF_B_Marine_Des_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Light_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Des",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Des",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class EF_B_Marine_TL_Des: EF_B_Marine_Des_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_TL_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_GL_Des: EF_B_Marine_Des_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_GL_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_SL_Des: EF_B_Marine_Des_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_SL_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Des_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Des_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_JTAC_Des: EF_B_Marine_Des_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_JTAC_Des.jpg";
		displayName="$STR_A3_C_B_W_RadioOperator_F0";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		Backpack="AX_B_RadioBag_01_coy_F";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Des_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Des_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_LAT_Des: EF_B_Marine_Des_Base_2
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_LAT_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		backpack="AX_B_RaiderPack_coy_dirty_LAT";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_LAT2_Des: EF_B_Marine_Des_Base_2
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_LAT2_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		backpack="AX_B_RaiderPack_coy_dirty_LAT2";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Mark_Des: EF_B_Marine_Des_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Mark_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_BasicNet_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_BasicNet_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Medic_Des: EF_B_Marine_Des_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Medic_Des.jpg";
		//displayName="$STR_B_medic_F0";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		backpack="AX_B_RaiderPack_coy_dirty_Medic";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Repair_Des: EF_B_Marine_Des_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Repair_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		backpack="AX_B_RaiderPack_coy_dirty_Repair";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Exp_Des: EF_B_Marine_Des_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Exp_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};	
	};
	class EF_B_Marine_AT_Des: EF_B_Marine_Des_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AT_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AA_Des: EF_B_Marine_Des_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AA_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Eng_Des: EF_B_Marine_Des_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Eng_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Crew_Des: EF_B_Marine_Des_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Crew_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Officer_Des: EF_B_Marine_Des_Base_6
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Officer_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		weapons[]=
		{
			"ef_arifle_mxar_coy_Holo_pointer",
			"ef_hgun_Pistol_heavy_01_coy",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_mxar_coy_Holo_pointer",
			"ef_hgun_Pistol_heavy_01_coy",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Des",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Des",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class EF_B_Marine_UAV_Des: EF_B_Marine_Des_Base_5
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_UAV_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Unarmed_Des: EF_B_Marine_R_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Unarmed_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"AX_H_MCH_BasicNet_Des_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class EF_B_Marine_Support_Base_Des: EF_B_Marine_Des_Base_4
	{
		//uniformClass="AX_U_B_MC_CombatUniform_tshirt3_des";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AAT_Des: EF_B_Marine_Support_Base_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AAT_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AAA_Des: EF_B_Marine_AAT_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AAA_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_HMG_Des: EF_B_Marine_Support_Base_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_HMG_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_GMG_Des: EF_B_Marine_Support_Base_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_GMG_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Mort_Des: EF_B_Marine_Support_Base_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Mort_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AMG_Des: EF_B_Marine_Support_Base_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AMG_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AMort_Des: EF_B_Marine_Support_Base_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AMG_Des.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_CMort_Des: EF_B_Marine_R_Des
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_R_Des.jpg";
	};
	class EF_B_Marine_BoatCrew_Des: EF_B_Marine_Des_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_BoatCrew_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_des";
		linkedItems[]=
		{
			"AX_V_AAV_Sailor_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Sailor_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AB_Des: EF_B_Marine_Des_Base_5
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AB_Des.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_des";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	
	class AX_B_MJTF_D_Helipilot_F: EF_B_Marine_Des_Base_1
    {
        scope=2;
        scopeCurator=2;
        author="$STR_A3_IMUS_Axle";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_Helipilot_F.jpg";
        class SpeechVariants
        {
            class Default
            {
                speechSingular[]=
                {
                    "veh_infantry_pilot_s"
                };
                speechPlural[]=
                {
                    "veh_infantry_pilot_p"
                };
            };
        };
        textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
        textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
        nameSound="veh_infantry_pilot_s";
        identityTypes[]=
        {
            "LanguageENG_F",
            "Head_NATO",
            "G_NATO_pilot"
        };
        role="Crewman";
        camouflage=2;
        faction="EF_B_MJTF_Des";
        uniformClass="AX_U_B_MC_HeliPilotCoveralls_Gloves_tan";
        displayName="$STR_B_Helipilot_F0";
        weapons[]=
        {
            "SMG_01_black_Holo_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "SMG_01_black_Holo_F",
            "Throw",
            "Put"
        };
        magazines[]=
        {
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
        respawnMagazines[]=
        {
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
		linkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class AX_B_MJTF_D_Helicrew_F: AX_B_MJTF_D_Helipilot_F
    {
        author="$STR_A3_IMUS_Axle";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_Helicrew_F.jpg";
        displayName="$STR_B_helicrew_F0";
        role="Crewman";
        faction="EF_B_MJTF_Des";
        uniformClass="AX_U_B_MC_HeliPilotCoveralls_Gloves_tan";
        weapons[]=
        {
            "ef_arifle_mxc_coy_Holo",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "ef_arifle_mxc_coy_Holo",
            "Throw",
            "Put"
        };
        magazines[]=
        {
            "EF_30Rnd_65x39_caseless_coy_mag",
            "EF_30Rnd_65x39_caseless_coy_mag",
            "EF_30Rnd_65x39_caseless_coy_mag",
            "EF_30Rnd_65x39_caseless_coy_mag",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
        respawnMagazines[]=
        {
            "EF_30Rnd_65x39_caseless_coy_mag",
            "EF_30Rnd_65x39_caseless_coy_mag",
            "EF_30Rnd_65x39_caseless_coy_mag",
            "EF_30Rnd_65x39_caseless_coy_mag",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
		linkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class AX_B_MJTF_D_Fighter_Pilot_F: EF_B_Marine_Des_Base_1
    {
        scope=2;
        scopeCurator=2;
        author="$STR_A3_IMUS_Axle";
        class SpeechVariants
        {
            class Default
            {
                speechSingular[]=
                {
                    "veh_infantry_pilot_s"
                };
                speechPlural[]=
                {
                    "veh_infantry_pilot_p"
                };
            };
        };
        textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
        textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
        nameSound="veh_infantry_pilot_s";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_Fighter_Pilot_F.jpg";
        displayName="$STR_A3_B_Fighter_Pilot_name";
        camouflage=2;
        cost=160000;
        role="Crewman";
        uniformClass="AX_U_B_MC_PilotCoveralls_Gloves_tan";
        weapons[]=
        {
            "ef_hgun_P07_coy",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "ef_hgun_P07_coy",
            "Throw",
            "Put"
        };
        magazines[]=
        {
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "SmokeShellBlue",
            "SmokeShellBlue"
        };
        respawnMagazines[]=
        {
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "SmokeShellBlue",
            "SmokeShellBlue"
        };
        linkedItems[]=
        {
            "H_PilotHelmetFighter_B",
            "V_TacVest_khk",
			"G_Balaclava_TI_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "H_PilotHelmetFighter_B",
            "V_TacVest_khk",
			"G_Balaclava_TI_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
	class AX_B_MJTF_D_HeavyGunner_F: EF_B_Marine_Des_Base_1
    {		
        scope=2;
        scopeCurator=2;
        author="$STR_A3_IMUS_Axle";
        class SpeechVariants
        {
            class Default
            {
                speechSingular[]=
                {
                    "veh_infantry_MG_s"
                };
                speechPlural[]=
                {
                    "veh_infantry_MG_p"
                };
            };
        };
        textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
        textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
        nameSound="veh_infantry_MG_s";
        icon="iconManMG";
        role="MachineGunner";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_HeavyGunner_F.jpg";
        displayName="$STR_A3_CfgVehicles_B_HeavyGunner_F0";
        uniformClass="EF_U_B_MarineCombatUniform_Des_4";
        weapons[]=
        {
            "AX_MMG_02_coy_RCO_LP_F",
            "ef_hgun_P07_coy",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "AX_MMG_02_coy_RCO_LP_F",
            "ef_hgun_P07_coy",
            "Throw",
            "Put"
        };
        magazines[]=
        {
            "130Rnd_338_Mag",
            "130Rnd_338_Mag",
            "130Rnd_338_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "SmokeShell",
            "SmokeShell"
        };
        respawnMagazines[]=
        {
            "130Rnd_338_Mag",
            "130Rnd_338_Mag",
            "130Rnd_338_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "SmokeShell",
            "SmokeShell"
        };
        linkedItems[]=
        {
            "AX_V_AAV_Support_Coy_dirty",
            "AX_H_MCH_Basic_dirty",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "NVGoggles"
        };
        respawnLinkedItems[]=
        {
            "AX_V_AAV_Support_Coy_dirty",
            "AX_H_MCH_Basic_dirty",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "NVGoggles"
        };
    };
