    class AX_B_MJTF_D_Soldier_MARSOC_base: EF_B_Marine_Des_Base_1
	{
		scope=0;
		scopeCurator=0;
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_SF_s"
				};
				speechPlural[]=
				{
					"veh_infantry_SF_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_SF_s";
		textPlural="$STR_A3_nameSound_veh_infantry_SF_p";
		nameSound="veh_infantry_SF_s";
		items[]=
		{
			"FirstAidKit",
			"optic_NVS"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_NVS"
		};
		vehicleClass="MenRecon";
		editorSubcategory="EdSubcat_Personnel_MARSOC";
		icon="iconManRecon";
		role="Rifleman";
		camouflage=0.60000002;
		detectSkill=18;
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_F";
		class EventHandlers: EventHandlers
		{
			init="[_this select 0,'USMC_MARSOC_Low'] call bis_fnc_setUnitInsignia;";
		};
		class AttributeValues
		{
			unitInsignia="USMC_MARSOC_Low";
		};
	};
	class AX_B_MJTF_W_Soldier_MARSOC_base: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		faction="EF_B_MJTF_Wdl";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_wdl_F";
	};
    class AX_B_D_MARSOC_AR_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_AR_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_soldier_AR_F0";
		cost=220000;
		icon="iconManMG";
		role="MachineGunner";
		threat[]={1,0.1,0.30000001};
		uniformClass="AX_U_B_MC_CombatUniform_IHWCU_NCU_02_des_F";
		backpack="AX_B_Carryall_mdes_MARSOC_AR";
		weapons[]=
		{
			"AX_LMG_Mk200_coy_RCO_LP_S_V2_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_coy_RCO_LP_S_V2_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"200Rnd_65x39_cased_Box",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_MG_coy_F",
			"AX_H_MCH_Velcro_Full_dirty",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_gg_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_MG_coy_F",
			"AX_H_MCH_Velcro_Full_dirty",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_gg_Hidden"
		};
	};
	class AX_B_D_MARSOC_AR2_F: AX_B_D_MARSOC_AR_F
	{
		displayName="$STR_A3_MCFU_character_support_F0";
		scope=1;
		scopeCurator=1;
		backpack="AX_B_Carryall_coy_MARSOC_Ammo2";
		weapons[]=
		{
			"AX_LMG_Mk200_coy_Holo_IR_snds_BI_V2_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_LMG_Mk200_coy_Holo_IR_snds_BI_V2_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"200Rnd_65x39_cased_Box_Red",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
	};
	class AX_B_D_MARSOC_Exp_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_Exp_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_exp_F0";
		backpack="AX_B_AssaultPackSpec_mdes_MARSOC_Exp_F";
		canDeactivateMines=1;
		detectSkill=38;
		icon="iconManExplosive";
		picture="pictureExplosive";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_des_F";
		role="Sapper";
		weapons[]=
		{
			"AX_arifle_mxc_spray_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxc_spray_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"APERSMine_Range_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Cap_coy_hs",
			"Aegis_G_Condor_EyePro_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Cap_coy_hs",
			"Aegis_G_Condor_EyePro_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
	};
	class AX_B_D_MARSOC_GL_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_GL_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_GL_F0";
		cost=200000;
		role="Grenadier";
		weapons[]=
		{
			"AX_arifle_mxar_gl_coy_tt_Holo_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxar_gl_coy_tt_Holo_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_HEDP_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"3Rnd_HEDP_Grenade_shell"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
	};
	class AX_B_D_MARSOC_JTAC_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_JTAC_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_B_CTRG_Soldier_JTAC_tna_F0";
		role="SpecialOperative";
		backpack="AX_B_RadioBag_01_mdes_F";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_F";
		weapons[]=
		{
			"AX_arifle_mxar_coy_tt_MBS_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxar_coy_tt_MBS_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
	};
	class AX_B_D_MARSOC_M_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_M_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_soldier_M_F0";
		cost=250000;
		role="Marksman";
		primaryAmmoCoef=0.2;
		secondaryAmmoCoef=0.050000001;
		handgunAmmoCoef=0.1;
		threat[]={1,0.1,0.30000001};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_Cloak_unbl_01_des_F";
		weapons[]=
		{
			"AX_arifle_mxm_coy_tt_DMS_LP_BI_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxm_coy_tt_DMS_LP_BI_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Booniehat_des_hs",
			"AX_G_Bandanna_shemag_tan",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Booniehat_des_hs",
			"AX_G_Bandanna_shemag_tan",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
	};
	class AX_B_D_MARSOC_M2_F: AX_B_D_MARSOC_M_F
	{
		displayName="$STR_A3_MCFU_character_recon_F0";
		scope=1;
		scopeArsenal=1;
		backpack="AX_B_AssaultPackSpec_coy";
	};
	class AX_B_D_MARSOC_Medic_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_Medic_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Medic_F0";
		backpack="AX_B_AssaultPackSpec_mdes_MARSOC_Medic_F";
		attendant=1;
		icon="iconManMedic";
		picture="pictureHeal";
		role="CombatLifeSaver";
		threat[]={1,0.1,0.30000001};
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb_F";
		weapons[]=
		{
			"AX_arifle_mxc_spray_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxc_spray_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_G_coy_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_G_coy_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
	};
	class AX_B_D_MARSOC_Medic2_F: AX_B_D_MARSOC_Medic_F
	{
		displayName="$STR_A3_MCFU_character_assault_F0";
		scope=1;
		scopeArsenal=1;
		backpack="AX_B_AssaultPack_coy_MARSOC_Medic_F";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_01_des_cb2_F";
	};
	class AX_B_D_MARSOC_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_A_cfgVehicles_Atlas_B_JSOC_F0";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_cb_F";
		weapons[]=
		{
			"AX_arifle_mxar_coy_tt_RCO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxar_coy_tt_RCO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_G_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_G_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
	};
	class AX_B_D_MARSOC_LAT_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_LAT_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_A_cfgVehicles_Atlas_B_JSOC_LAT_F0";
		backpack="AX_B_AssaultPackSpec_mdes_MARSOC_LAT_F";
		cost=130000;
		threat[]={1,0.60000002,0.1};
		secondaryAmmoCoef=0.5;
		icon="iconManAT";
		role="MissileSpecialist";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_F";
		weapons[]=
		{
			"AX_arifle_mxc_coy_tt_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"launch_MRAWS_green_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxc_coy_tt_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"launch_MRAWS_green_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MRAWS_HEAT_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MRAWS_HEAT_F",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Cap_headphones_coy",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Cap_headphones_coy",
			"G_Tactical_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
	};
	class AX_B_D_MARSOC_LAT2_F: AX_B_D_MARSOC_LAT_F
	{
		displayName="$STR_A3_MCFU_character_engineer_F0";
		scope=1;
		scopeArsenal=1;
		engineer=1;
		backpack="AX_B_TacticalPack_coy_MARSOC_LAT";
	};
	class AX_B_D_MARSOC_TL_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_TL_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_TL_F0";
		cost=250000;
		icon="iconManLeader";
		role="Rifleman";
		threat[]={1,0.1,0.30000001};
		weapons[]=
		{
			"AX_arifle_mxar_coy_tt_MBS_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxar_coy_tt_MBS_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_TL_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_TL_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
	};
	class AX_B_D_MARSOC_SL_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_SL_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_B_Soldier_SL_F0";
		cost=250000;
		icon="iconManLeader";
		role="Grenadier";
		threat[]={1,0.1,0.30000001};
		weapons[]=
		{
			"AX_arifle_mxar_gl_coy_tt_RCO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxar_gl_coy_tt_RCO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"EF_30Rnd_65x39_caseless_coy_mag_tracer",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"3Rnd_HE_Grenade_shell",
			"3Rnd_HE_Grenade_shell",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue",
			"3Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_TL_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Shemag_tan_tactical_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_TL_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_coy_worn_F",
			"AX_G_Shemag_tan_tactical_blk",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"EF_LPNVG_Tan"
		};
	};
	class AX_B_D_MARSOC_Sharpshooter_F: AX_B_D_MARSOC_M_F
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_Sharpshooter_F.jpg";
		displayName="$STR_A3_cfgVehicles_B_Sharpshooter_F0";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_tee_unbl_des_brn_F";
		weapons[]=
		{
			"AX_arifle_SR25_twotone_SOS_pointer_snds_BI_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_arifle_SR25_twotone_SOS_pointer_snds_BI_F",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"Aegis_20Rnd_762x51_Red_Sand_SMAG",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"H_ShemagOpen_tan",
			"Aegis_G_Headset_Black_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"H_ShemagOpen_tan",
			"Aegis_G_Headset_Black_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"AX_LPNVG_Tan_sm_Hidden"
		};
	};
	class AX_B_D_MARSOC_UAV_F: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_UAV_F.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_A_cfgVehicles_Atlas_B_JSOC_UAV_F0";
		uavHacker=1;
		cost=150000;
		role="SpecialOperative";
		backpack="EF_B_UAV_01_backpack_coy";
		uniformClass="AX_U_B_MC_CombatUniform_G3_NCU_unbl_02_des_F";
		weapons[]=
		{
			"AX_arifle_mxar_coy_tt_RCO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxar_coy_tt_RCO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_snk_ard_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"EF_LPNVG_Tan"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_snk_ard_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"EF_LPNVG_Tan"
		};
	};
	class AX_B_D_MARSOC_UAV_lxWS: AX_B_MJTF_D_Soldier_MARSOC_base
	{
		author="$STR_A3_A_Ravenholme";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_D_MARSOC_UAV_lxWS.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_A_cfgVehicles_Atlas_B_JSOC_UAV_lxWS0";
		uavHacker=1;
		cost=150000;
		role="SpecialOperative";
		backpack="B_UAV_02_backpack_lXWS";
		weapons[]=
		{
			"AX_arifle_mxc_coy_tt_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_arifle_mxc_coy_tt_ACO_pointer_snds",
			"hgun_P07_blk_Snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag_v2",
			"16Rnd_9x21_Mag_v2",
			"MiniGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_blue",
			"Chemlight_blue"
		};
		linkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_snk_ard_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"EF_LPNVG_Tan"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AssaultCarrier_Lite_coy_F",
			"AX_H_Helmet_FASTMT_ARCrail_snk_ard_worn_F",
			"AX_G_Balaclava_mesh_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UAVTerminal",
			"EF_LPNVG_Tan"
		};
	};