    class EF_B_Marine_Recon_Des: EF_B_Marine_Recon_Des_base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Recon_Des.jpg";
        uniformClass="AX_U_B_MC_UniformUS_02_des_F";
		backpack="AX_B_Hydrationpack_coy";
		weapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Binocular"
		};
        linkedItems[]=
		{
			"AX_V_CCR_Scout_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_Scout_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class EF_B_Marine_Recon_LAT_Des: EF_B_Marine_Recon_Des_base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Recon_LAT_Des.jpg";
		uniformClass="AX_U_B_MC_UniformUS_02_des_F";
		backpack="AX_B_RaiderPack_coy_dirty_ReconLAT";
		weapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"launch_NLAW_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"launch_NLAW_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_CCR_Support_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_Support_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class EF_B_Marine_Recon_Exp_Des: EF_B_Marine_Recon_Des_base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Recon_Exp_Des.jpg";
		uniformClass="AX_U_B_MC_UniformUS_des_F";
		backpack="AX_B_RaiderPack_coy_dirty_ReconExp";
		weapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_CCR_Rifleman_Coy_dirty",
			"AX_H_Booniehat_des_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_Rifleman_Coy_dirty",
			"AX_H_Booniehat_des_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class EF_B_Marine_Recon_Medic_Des: EF_B_Marine_Recon_Des_base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Recon_Medic_Des.jpg";
		uniformClass="AX_U_B_MC_UniformUS_02_des_F";
		backpack="AX_B_RaiderPack_coy_dirty_ReconMedic";
		weapons[]=
		{
			"ef_arifle_MXC_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MXC_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_CCR_Scout_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_Scout_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class EF_B_Marine_Recon_TL_Des: EF_B_Marine_Recon_Des_base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Recon_TL_Des.jpg";
		uniformClass="AX_U_B_MC_UniformUS_02_des_F";
		backpack="AX_B_Hydrationpack_coy";
		weapons[]=
		{
			"ef_arifle_MX_coy_RCO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_RCO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"AX_V_CCR_TL_Coy_dirty",
			"AX_H_Booniehat_des_hs",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_TL_Coy_dirty",
			"AX_H_Booniehat_des_hs",
			"G_Shades_Black",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class EF_B_Marine_Recon_M_Des: EF_B_Marine_Recon_Des_base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Recon_M_Des.jpg";
		uniformClass="AX_U_B_MC_UniformUS_des_F";
		backpack="AX_B_Hydrationpack_coy";
		weapons[]=
		{
			"ef_arifle_mxm_MBS_LP_BI_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"ef_arifle_mxm_MBS_LP_BI_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		linkedItems[]=
		{
			"AX_V_CCR_Rifleman_Coy_dirty",
			"AX_H_Booniehat_des_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_Rifleman_Coy_dirty",
			"AX_H_Booniehat_des_hs",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class EF_B_Marine_Recon_JTAC_Des: EF_B_Marine_Recon_Des_base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Recon_JTAC_Des.jpg";
		uniformClass="AX_U_B_MC_UniformUS_02_des_F";
		Backpack="AX_B_RadioBag_01_coy_F";
		weapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AX_V_CCR_TL_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_TL_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
	class EF_B_Marine_Diver_Des: EF_B_Marine_Diver_Des_Base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Diver_Des.jpg";
		//uniformClass="AX_U_B_MC_SurvivalFatigues_des";
		backpack="AX_B_RaiderPack_black_dirty_Diver";
		weapons[]=
		{
			"arifle_SDAR_F",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"arifle_SDAR_F",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class EF_B_Marine_Diver_TL_Des: EF_B_Marine_Diver_Des_Base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Diver_TL_Des.jpg";
		//uniformClass="AX_U_B_MC_SurvivalFatigues_des";
		backpack="AX_B_RaiderPack_coy_dirty_Diver_TL";
		weapons[]=
		{
			"ef_arifle_MX_coy_Holo_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_Holo_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
        linkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class EF_B_Marine_Diver_Eng_Des: EF_B_Marine_Diver_Des_Base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Diver_Eng_Des.jpg";
		//uniformClass="AX_U_B_MC_SurvivalFatigues_des";
		backpack="AX_B_RaiderPack_coy_dirty_Diver_Eng";
		weapons[]=
		{
			"ef_arifle_MXC_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MXC_coy_ACO_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
        linkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class EF_B_Marine_Diver_Pointman_Des: EF_B_Marine_Diver_Des_Base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Diver_Pointman_Des.jpg";
		//uniformClass="AX_U_B_MC_SurvivalFatigues_des";
		backpack="AX_B_RaiderPack_coy_dirty_Diver_Pointman";
		weapons[]=
		{
			"SMG_01_Holo_pointer_snds_F",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_Holo_pointer_snds_F",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class EF_B_Marine_Diver_Scout_Des: EF_B_Marine_Diver_Des_Base
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Diver_Scout_Des.jpg";
		//uniformClass="AX_U_B_MC_SurvivalFatigues_des";
		backpack="AX_B_RaiderPack_coy_dirty_Diver_TL";
		weapons[]=
		{
			"ef_arifle_MX_coy_MBS_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_MBS_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		linkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Diver_Coy_dirty",
			"AX_H_Helmet_FASTMT_coy_worn_F",
			"NVGoggles",
			"G_B_Diving",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };

	class AX_B_MJTF_D_Recon_AR: EF_B_Marine_Recon_Des_base
	{
		author="$STR_A3_IMUS_Axle";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_Recon_AR.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_C_O_R_Recon_AR_F0";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		role="MachineGunner";
		icon="iconManMG";
		cost=220000;
		threat[]={1,0.1,0.30000001};
		uniformClass="AX_U_B_MC_UniformUS_des_F";
		backpack="AX_B_Hydrationpack_coy";
		weapons[]=
		{
			"ef_arifle_mxar_coy_MBS_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_mxar_coy_MBS_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"EF_100Rnd_65x39_caseless_coy_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AX_V_CCR_Support_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_Support_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class AX_B_MJTF_D_Recon_GL: EF_B_Marine_Recon_Des_base
	{
		author="$STR_A3_IMUS_Axle";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_Recon_GL.jpg";
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_C_O_R_Recon_GL_F0";
		role="Grenadier";
		cost=210000;
		uniformClass="AX_U_B_MC_UniformUS_des_F";
		backpack="AX_B_Hydrationpack_coy";
		weapons[]=
		{
			"ef_arifle_MX_GL_coy_Holo_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_GL_coy_Holo_pointer_snds",
			"AX_hgun_Pistol_heavy_01_coy_snds_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"11Rnd_45ACP_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"1Rnd_HE_Grenade_shell",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_Smoke_Grenade_shell",
			"1Rnd_SmokeBlue_Grenade_shell",
			"1Rnd_SmokeGreen_Grenade_shell",
			"1Rnd_SmokeOrange_Grenade_shell"
		};
		linkedItems[]=
		{
			"AX_V_CCR_Scout_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_CCR_Scout_Coy_dirty",
			"AX_H_Helmet_FASTMT_ARCrail_Cover_Scrim_mpd_worn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class AX_B_MJTF_D_sniper_F: EF_B_Marine_Recon_Des_base
	{
		scope=2;
		scopeCurator=2;
		author="$STR_A3_IMUS_Axle";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
		nameSound="veh_infantry_sniper_s";
		role="Marksman";
		cost=250000;
		threat[]={0.80000001,0.30000001,0.30000001};
		camouflage=0.40000001;
		tLightInfluence=0.015;
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_sniper_F.jpg";
		displayName="$STR_B_sniper_F0";
		faction="EF_B_MJTF_Des";
		uniformClass="U_B_FullGhillie_ard";
		weapons[]=
		{
			"srifle_LRR_LRPS_F",
			"AX_hgun_P07_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"srifle_LRR_LRPS_F",
			"AX_hgun_P07_coy_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		magazines[]=
		{
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"7Rnd_408_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_black"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws_sniper",
			"muzzle_snds_408_black"
		};
		linkedItems[]=
		{
			"EF_V_CCR_Support_Coy",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"EF_V_CCR_Support_Coy",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class AX_B_MJTF_D_spotter_F: AX_B_MJTF_D_sniper_F
	{		
        scope=2;
		scopeCurator=2;
		author="$STR_A3_IMUS_Axle";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_SF_s"
				};
				speechPlural[]=
				{
					"veh_infantry_SF_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_SF_s";
		textPlural="$STR_A3_nameSound_veh_infantry_SF_p";
		nameSound="veh_infantry_SF_s";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_D_spotter_F.jpg";
		displayName="$STR_B_spotter_F0";
		cost=250000;
		weapons[]=
		{
			"ef_arifle_MX_coy_RCO_pointer_snds",
			"AX_hgun_P07_coy_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		respawnWeapons[]=
		{
			"ef_arifle_MX_coy_RCO_pointer_snds",
			"AX_hgun_P07_coy_snds_F",
			"Throw",
			"Put",
			"Laserdesignator"
		};
		magazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"EF_30Rnd_65x39_caseless_coy_mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"APERSTripMine_Wire_Mag",
			"MiniGrenade",
			"MiniGrenade",
			"B_IR_Grenade",
			"B_IR_Grenade",
			"Laserbatteries",
			"SmokeShell",
			"SmokeShell",
			"Chemlight_green",
			"Chemlight_green"
		};
		items[]=
		{
			"FirstAidKit",
			"optic_tws"
		};
		respawnItems[]=
		{
			"FirstAidKit",
			"optic_tws"
		};
		linkedItems[]=
		{
			"EF_V_CCR_Scout_Coy",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"EF_V_CCR_Scout_Coy",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
