	class EF_B_Marine_R_Wdl: EF_B_Marine_Wdl_Base_3
    {
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_R_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
        linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
    };
    class EF_B_Marine_AR_Wdl: EF_B_Marine_Wdl_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AR_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Light_Wdl: EF_B_Marine_Wdl_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Light_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Wdl",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class EF_B_Marine_TL_Wdl: EF_B_Marine_Wdl_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_TL_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Coy_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_GL_Wdl: EF_B_Marine_Wdl_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_GL_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Olive_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Olive_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_SL_Wdl: EF_B_Marine_Wdl_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_SL_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_JTAC_Wdl: EF_B_Marine_Wdl_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_JTAC_Wdl.jpg";
		displayName="$STR_A3_C_B_W_RadioOperator_F0";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		Backpack="AX_B_RadioBag_01_coy_F";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_LAT_Wdl: EF_B_Marine_Wdl_Base_2
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_LAT_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		backpack="AX_B_RaiderPack_coy_dirty_LAT";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_LAT2_Wdl: EF_B_Marine_Wdl_Base_2
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_LAT2_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		backpack="AX_B_RaiderPack_coy_dirty_LAT2";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_Basic_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Mark_Wdl: EF_B_Marine_Wdl_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Mark_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_BasicNet_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_BasicNet_Coy_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Medic_Wdl: EF_B_Marine_Wdl_Base_4
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Medic_Wdl.jpg";
		//displayName="$STR_B_medic_F0";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		backpack="AX_B_RaiderPack_coy_dirty_Medic";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Repair_Wdl: EF_B_Marine_Wdl_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Repair_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		backpack="AX_B_RaiderPack_coy_dirty_Repair";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Exp_Wdl: EF_B_Marine_Wdl_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Exp_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_FullCamo_Olive_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_FullCamo_Olive_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};	
	};
	class EF_B_Marine_AT_Wdl: EF_B_Marine_Wdl_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AT_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AA_Wdl: EF_B_Marine_Wdl_Base_1
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AA_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Eng_Wdl: EF_B_Marine_Wdl_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Eng_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_FullCamo_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Crew_Wdl: EF_B_Marine_Wdl_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Crew_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Officer_Wdl: EF_B_Marine_Wdl_Base_6
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Officer_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		weapons[]=
		{
			"ef_arifle_mxar_coy_Holo_pointer",
			"ef_hgun_Pistol_heavy_01_coy",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_mxar_coy_Holo_pointer",
			"ef_hgun_Pistol_heavy_01_coy",
			"Throw",
			"Put"
		};
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Wdl",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"EF_H_UtilityCap_Wdl",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class EF_B_Marine_UAV_Wdl: EF_B_Marine_Wdl_Base_5
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_UAV_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Unarmed_Wdl: EF_B_Marine_R_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Unarmed_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Coy_dirty",
			"AX_H_MCH_BasicNet_Wdl_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class EF_B_Marine_Support_Base_Wdl: EF_B_Marine_Wdl_Base_4
	{
		//uniformClass="AX_U_B_MC_CombatUniform_tshirt3_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AAT_Wdl: EF_B_Marine_Support_Base_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AAT_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AAA_Wdl: EF_B_Marine_AAT_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AAA_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_HMG_Wdl: EF_B_Marine_Support_Base_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_HMG_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Support_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_GMG_Wdl: EF_B_Marine_Support_Base_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_GMG_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_Mort_Wdl: EF_B_Marine_Support_Base_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_Mort_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Rifleman_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_CMort_Wdl: EF_B_Marine_R_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_R_Wdl.jpg";
	};
	class EF_B_Marine_AMG_Wdl: EF_B_Marine_Support_Base_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AMG_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AMort_Wdl: EF_B_Marine_Support_Base_Wdl
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AMort_Wdl.jpg";
		linkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_TL_Coy_dirty",
			"AX_H_MCH_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_BoatCrew_Wdl: EF_B_Marine_Wdl_Base_3
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_BoatCrew_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_vest_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Sailor_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Sailor_Coy_dirty",
			"EF_H_HelmetCrew_Coy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};
	class EF_B_Marine_AB_Wdl: EF_B_Marine_Wdl_Base_5
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\EF_B_Marine_AB_Wdl.jpg";
		//uniformClass="AX_U_B_MC_CombatUniform_wdl";
		linkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Scout_Coy_dirty",
			"AX_H_MCH_Full_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles"
		};
	};

	class AX_B_MJTF_W_Helipilot_F: AX_B_MJTF_D_Helipilot_F
    {
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_W_Helipilot_F.jpg";
        faction="EF_B_MJTF_Wdl";
        uniformClass="AX_U_B_MC_HeliPilotCoveralls_Gloves";
    };
    class AX_B_MJTF_W_Helicrew_F: AX_B_MJTF_D_Helicrew_F
    {
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_W_Helicrew_F.jpg";
        faction="EF_B_MJTF_Wdl";
        uniformClass="AX_U_B_MC_HeliPilotCoveralls_Gloves";
    };
    class AX_B_MJTF_W_Fighter_Pilot_F: AX_B_MJTF_D_Fighter_Pilot_F
    {
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_W_Fighter_Pilot_F.jpg";
        faction="EF_B_MJTF_Wdl";
        uniformClass="AX_U_B_MC_PilotCoveralls_Gloves";
    };
    class AX_B_MJTF_W_HeavyGunner_F: AX_B_MJTF_D_HeavyGunner_F
    {
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_MJTF_W_HeavyGunner_F.jpg";
        faction="EF_B_MJTF_Wdl";
        uniformClass="EF_U_B_MarineCombatUniform_Wdl_4";
    };