    class Aegis_O_C_D_Soldier_A_F: O_T_Soldier_A_F
    {
    };
    class Aegis_O_C_D_Recon_Exp_F: O_T_Recon_Exp_F
    {
        linkedItems[]=
        {
            "V_HarnessO_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessO_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_JTAC_F: O_T_Recon_JTAC_F
    {
        linkedItems[]=
        {
            "V_HarnessOGL_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessOGL_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_M_F: O_T_Recon_M_F
    {
        linkedItems[]=
        {
            "V_TacVest_brn",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_TacVest_brn",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_Medic_F: O_T_Recon_Medic_F
    {
        linkedItems[]=
        {
            "V_HarnessO_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessO_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_F: O_T_Recon_F
    {
        linkedItems[]=
        {
            "V_HarnessOSpec_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessOSpec_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_LAT_F: O_T_Recon_LAT_F
    {
        linkedItems[]=
        {
            "V_TacVest_brn",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_TacVest_brn",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_TL_F: O_T_Recon_TL_F
    {
        linkedItems[]=
        {
            "V_HarnessOSpec_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessOSpec_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_CQ_F: O_T_Recon_CQ_F
    {
        linkedItems[]=
        {
            "V_TacVest_brn",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_TacVest_brn",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_AR_F: O_T_Recon_AR_F
    {
        linkedItems[]=
        {
            "V_HarnessOSpec_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessOSpec_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Recon_GL_F: O_T_Recon_GL_F
    {
        linkedItems[]=
        {
            "V_HarnessOGL_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessOGL_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
    class Aegis_O_C_D_Pathfinder_F: O_T_Pathfinder_F
    {
        linkedItems[]=
        {
            "V_HarnessO_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
        respawnLinkedItems[]=
        {
            "V_HarnessO_oicamo",
            "AX_H_HelmetAggressor_dhex_F",
            "AX_G_Balaclava_G_nylon_blk",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio",
            "O_NVGoggles_hex_F"
        };
    };
