    class Atlas_O_C_Marine_base_F: O_T_Soldier_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
    class Atlas_O_C_Marine_AR_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_Medic_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_Engineer_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"H_Watchcap_blk",
			"G_AirPurifyingRespirator_02_black_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"H_Watchcap_blk",
			"G_AirPurifyingRespirator_02_black_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_Exp_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_GL_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_GL_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_HG_F: Atlas_O_C_Marine_base_F
    {
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"lxWS_H_BMask_base",
			"AX_G_Balaclava_cloth_blk_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_cqb_blk_F",
			"lxWS_H_BMask_base",
			"AX_G_Balaclava_cloth_blk_F",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class Atlas_O_C_Marine_M_F: Atlas_O_C_Marine_base_F
    {
        linkedItems[]=
		{
			"Atlas_V_OCarrierRig_lite_blk_F",
			"H_Headset_Black_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_lite_blk_F",
			"H_Headset_Black_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
	class Atlas_O_C_Marine_AA_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_AT_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_LAT_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_SL_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_TL_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
	class Atlas_O_C_Marine_UAV_F: Atlas_O_C_Marine_base_F
	{
		linkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Atlas_V_OCarrierRig_Lite_blk_F",
			"Atlas_H_HelmetCCH_HiCut_Cover_mhex_F",
			"AX_G_Balaclava_G_nylon_blk",
			"O_NVGoggles_blk_F",
			"O_UAVTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
	};
