	class vn_b_men_usmc_68_base;
    class vn_b_men_usmc_68_01;
    class vn_b_men_usmc_68_04: vn_b_men_usmc_68_base
	{
        linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_68_06: vn_b_men_usmc_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_03",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_19_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_03",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_19_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_07: vn_b_men_usmc_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_04",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_15_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_04",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_15_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_09: vn_b_men_usmc_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_16_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_16_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_10: vn_b_men_usmc_68_base{}; //Sniper has towel only
	class vn_b_men_usmc_68_12: vn_b_men_usmc_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_16_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_16_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_14: vn_b_men_usmc_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_06",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_06",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_15: vn_b_men_usmc_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_16_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_16_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_68_16: vn_b_men_usmc_68_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_16_01",
			"vn_b_acc_towel_02",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_16_01",
			"vn_b_acc_towel_02",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_19: vn_b_men_usmc_68_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_16_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_16_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_21: vn_b_men_usmc_68_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_68_26: vn_b_men_usmc_68_01
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_66_base;
    class vn_b_men_usmc_66_01;
    class vn_b_men_usmc_66_04: vn_b_men_usmc_66_base
	{
        linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_66_06: vn_b_men_usmc_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_03",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_19_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_03",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_19_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_07: vn_b_men_usmc_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_04",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_15_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_04",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_15_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_09: vn_b_men_usmc_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_10: vn_b_men_usmc_66_base{};
	class vn_b_men_usmc_66_12: vn_b_men_usmc_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_17_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_14: vn_b_men_usmc_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_15: vn_b_men_usmc_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_66_16: vn_b_men_usmc_66_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"vn_b_acc_towel_02",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"vn_b_acc_towel_02",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_19: vn_b_men_usmc_66_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_21: vn_b_men_usmc_66_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_17_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_66_26: vn_b_men_usmc_66_01
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_70_base;
    class vn_b_men_usmc_70_01;
    class vn_b_men_usmc_70_04: vn_b_men_usmc_70_base
	{
        linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_70_06: vn_b_men_usmc_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_03",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_03",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_07: vn_b_men_usmc_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_04",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_04",
			"vn_b_acc_towel_02",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_09: vn_b_men_usmc_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_10: vn_b_men_usmc_70_base{};
	class vn_b_men_usmc_70_12: vn_b_men_usmc_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"ax_b_acc_towel_01_nv",
			"vn_b_helmet_m1_14_01",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_14: vn_b_men_usmc_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_06",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_06",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_15: vn_b_men_usmc_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_14_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_14_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
    class vn_b_men_usmc_70_16: vn_b_men_usmc_70_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_14_01",
			"vn_b_acc_towel_02",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_14_01",
			"vn_b_acc_towel_02",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_19: vn_b_men_usmc_70_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_14_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_14_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_21: vn_b_men_usmc_70_15
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_14_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_02",
			"vn_b_helmet_m1_14_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_70_26: vn_b_men_usmc_70_01
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_01",
			"vn_b_helmet_m1_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
    };
	class vn_b_men_usmc_recon_66_base;
	class vn_b_men_usmc_recon_66_01: vn_b_men_usmc_recon_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_66_02: vn_b_men_usmc_recon_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_04_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_04_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_66_05: vn_b_men_usmc_recon_66_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_08",
			"vn_b_headband_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_08",
			"vn_b_headband_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_68_base;
	class vn_b_men_usmc_recon_68_01: vn_b_men_usmc_recon_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_68_02: vn_b_men_usmc_recon_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_04_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_04_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_68_05: vn_b_men_usmc_recon_68_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_08",
			"vn_b_headband_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_08",
			"vn_b_headband_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_70_base;
	class vn_b_men_usmc_recon_70_01: vn_b_men_usmc_recon_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_02_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_70_02: vn_b_men_usmc_recon_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_04_08",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_07",
			"vn_b_boonie_04_08",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};
	class vn_b_men_usmc_recon_70_05: vn_b_men_usmc_recon_70_base
	{
		linkedItems[]=
		{
			"vn_b_vest_usmc_08",
			"vn_b_headband_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
		respawnLinkedItems[]=
		{
			"vn_b_vest_usmc_08",
			"vn_b_headband_01",
			"ax_b_acc_towel_01_nv",
			"vn_b_item_map",
			"vn_b_item_compass",
			"vn_b_item_watch",
			"vn_b_item_radio_urc10"
		};
	};