    class EF_B_Marine_Des_Base_1;
	class EF_B_Marine_Medic_Des;
	class EF_B_Marine_Medic_Wdl;
	class EF_B_Marine_Officer_Des;
	class EF_B_Marine_Repair_Des;
	class EF_B_Marine_BoatCrew_Des;
	class EF_B_Navy_FlightDeckCrew;
	class EF_B_Navy_Sailor;
	class AX_B_Navy_FlightDeckCrew_white: EF_B_Navy_FlightDeckCrew
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_FlightDeckCrew_white.jpg";
		displayName="$STR_A3_MCFU_flightdeck_white_F0";
        uniformClass="AX_U_B_USN_CrewCoveralls_White_Gloves";
		linkedItems[]=
		{
			"V_DeckCrew_white_F",
			"EF_H_HelmetCrew_White",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_DeckCrew_white_F",
			"EF_H_HelmetCrew_White",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class AX_B_Navy_FlightDeckCrew_yellow: EF_B_Navy_FlightDeckCrew
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_FlightDeckCrew_yellow.jpg";
		displayName="$STR_A3_MCFU_flightdeck_yellow_F0";
        uniformClass="AX_U_B_USN_CrewCoveralls_Yellow_Gloves";
		linkedItems[]=
		{
			"V_DeckCrew_yellow_F",
			"EF_H_HelmetCrew_Yellow",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_DeckCrew_yellow_F",
			"EF_H_HelmetCrew_Yellow",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class AX_B_Navy_FlightDeckCrew_red: EF_B_Navy_FlightDeckCrew
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_FlightDeckCrew_red.jpg";
		displayName="$STR_A3_MCFU_flightdeck_red_F0";
        uniformClass="AX_U_B_USN_CrewCoveralls_Red_Gloves";
		linkedItems[]=
		{
			"V_DeckCrew_red_F",
			"AX_H_HelmetCrew_Red",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_DeckCrew_red_F",
			"AX_H_HelmetCrew_Red",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class AX_B_Navy_FlightDeckCrew_green: EF_B_Navy_FlightDeckCrew
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_FlightDeckCrew_green.jpg";
		displayName="$STR_A3_MCFU_flightdeck_green_F0";
        uniformClass="AX_U_B_USN_CrewCoveralls_Green_Gloves";
		linkedItems[]=
		{
			"V_DeckCrew_green_F",
			"AX_H_HelmetCrew_Green",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_DeckCrew_green_F",
			"AX_H_HelmetCrew_Green",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class AX_B_Navy_FlightDeckCrew_brown: EF_B_Navy_FlightDeckCrew
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_FlightDeckCrew_brown.jpg";
		displayName="$STR_A3_MCFU_flightdeck_brown_F0";
        uniformClass="AX_U_B_USN_CrewCoveralls_Brown_Gloves";
		linkedItems[]=
		{
			"V_DeckCrew_brown_F",
			"AX_H_HelmetCrew_Brown",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_DeckCrew_brown_F",
			"AX_H_HelmetCrew_Brown",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class AX_B_Navy_FlightDeckCrew_blue: EF_B_Navy_FlightDeckCrew
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_FlightDeckCrew_blue.jpg";
		displayName="$STR_A3_MCFU_flightdeck_blue_F0";
        uniformClass="AX_U_B_USN_CrewCoveralls_Blue_Gloves";
		linkedItems[]=
		{
			"V_DeckCrew_blue_F",
			"AX_H_HelmetCrew_Blue",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_DeckCrew_blue_F",
			"AX_H_HelmetCrew_Blue",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class AX_B_Navy_FlightDeckCrew_violet: EF_B_Navy_FlightDeckCrew
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_FlightDeckCrew_violet.jpg";
		displayName="$STR_A3_MCFU_flightdeck_violet_F0";
        uniformClass="AX_U_B_USN_CrewCoveralls_Violet_Gloves";
		linkedItems[]=
		{
			"V_DeckCrew_violet_F",
			"AX_H_HelmetCrew_Violet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_DeckCrew_violet_F",
			"AX_H_HelmetCrew_Violet",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
    class AX_B_Navy_Sailor_Armed: EF_B_Navy_Sailor
	{
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Sailor_Armed.jpg";
        displayName="$STR_A3_MCFU_sailor_armed_F0";
        weapons[]=
        {
            "SMG_01_black_Holo_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "SMG_01_black_Holo_F",
            "Throw",
            "Put"
        };
        magazines[]=
        {
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
        respawnMagazines[]=
        {
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
        linkedItems[]=
		{
			"V_TacVest_blk",
			"EF_H_Cap_Navy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"EF_H_Cap_Navy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
    };
    class AX_B_Navy_Captain: EF_B_Marine_Officer_Des
    {
		scope=1;
		scopeCurator=1;
		faction="EF_B_MJTF_Navy";
		displayName="$STR_A3_MCFU_sailor_captain_F0";
        uniformClass="U_B_ParadeUniform_01_US_F";
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]=
		{
			"H_ParadeDressCap_01_US_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"H_ParadeDressCap_01_US_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class AX_B_Navy_Officer: EF_B_Marine_Officer_Des
    {
		scope=1;
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Officer.jpg";
		faction="EF_B_MJTF_Navy";
        uniformClass="EF_U_B_CrewCoveralls_Navy";
		weapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
            "V_TacVest_blk",
			"AX_H_MilCap_usn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_TacVest_blk",
			"AX_H_MilCap_usn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class AX_B_Navy_Corpsman_Marine_Des: EF_B_Marine_Medic_Des
	{
		scope=1;
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Corpsman_Marine_Des.jpg";
		faction="EF_B_MJTF_Navy";
		displayName="$STR_A3_MCFU_sailor_corpsman_usmc_des_F0";
		weapons[]=
		{
			"ef_arifle_mxc_coy_Holo",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_mxc_coy_Holo",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
	};
	class AX_B_Navy_Corpsman_Marine_Wdl: EF_B_Marine_Medic_Wdl
	{
		scope=1;
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Corpsman_Marine_Wdl.jpg";
		faction="EF_B_MJTF_Navy";
		displayName="$STR_A3_MCFU_sailor_corpsman_usmc_wdl_F0";
		weapons[]=
		{
			"ef_arifle_mxc_coy_Holo",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"ef_arifle_mxc_coy_Holo",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
	};
	class AX_B_Navy_Corpsman: EF_B_Marine_Medic_Des
	{
		scope=1;
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Corpsman.jpg";
		faction="EF_B_MJTF_Navy";
		displayName="$STR_A3_MCFU_sailor_corpsman_F0";
		uniformClass="AX_U_B_USN_CrewCoveralls_Gloves";
		backpack="AX_B_RaiderPack_black_Medic";
		weapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_Cap_Headphones_navyblue",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_NV_G_Armband_Medic_alt_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"AX_H_Cap_Headphones_navyblue",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"Aegis_NV_G_Armband_Medic_alt_F"
		};
	};
    class AX_B_Navy_BoatCrew: EF_B_Marine_BoatCrew_Des
    {
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_BoatCrew.jpg";
		faction="EF_B_MJTF_Navy";
		displayName="$STR_EF_B_boatCrew";
		uniformClass="AX_U_B_USN_CrewCoveralls_Gloves";
        weapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"AX_V_AAV_Sailor_Black_dirty",
			"AX_H_HelmetCrew_Navy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"AX_V_AAV_Sailor_Black_dirty",
			"AX_H_HelmetCrew_Navy",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
    };
    class AX_B_Navy_Pilot: EF_B_Marine_Des_Base_1
	{
        author="$STR_A3_IMUS_Axle";
		class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_pilot_s"
				};
				speechPlural[]=
				{
					"veh_infantry_pilot_p"
				};
			};
		};
		textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
		textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
		nameSound="veh_infantry_pilot_s";
		cost=93000;
		role="Crewman";
		camouflage=2;
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Pilot.jpg";
		scope=2;
		scopeCurator=2;
		faction="EF_B_MJTF_Navy";
		displayName="$STR_B_Pilot_F0";
		uniformClass="AX_U_B_USN_PilotCoveralls_Gloves";
		backpack="B_Parachute";
		weapons[]=
		{
			"SMG_01_black_Holo_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_black_Holo_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		respawnMagazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
		};
		linkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
            "V_TacVest_grn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
            "V_TacVest_grn",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
	};
    class AX_B_Navy_Fighter_Pilot_F: EF_B_Marine_Des_Base_1
    {
        scope=2;
        scopeCurator=2;
        author="$STR_A3_IMUS_Axle";
        class SpeechVariants
        {
            class Default
            {
                speechSingular[]=
                {
                    "veh_infantry_pilot_s"
                };
                speechPlural[]=
                {
                    "veh_infantry_pilot_p"
                };
            };
        };
        textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
        textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
        nameSound="veh_infantry_pilot_s";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Fighter_Pilot_F.jpg";
        displayName="$STR_A3_B_Fighter_Pilot_name";
        camouflage=2;
        cost=160000;
        role="Crewman";
		faction="EF_B_MJTF_Navy";
        uniformClass="AX_U_B_USN_PilotCoveralls_Gloves";
        weapons[]=
        {
            "hgun_P07_blk_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "hgun_P07_blk_F",
            "Throw",
            "Put"
        };
        magazines[]=
        {
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "SmokeShellBlue",
            "SmokeShellBlue"
        };
        respawnMagazines[]=
        {
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "16Rnd_9x21_Mag",
            "SmokeShellBlue",
            "SmokeShellBlue"
        };
        linkedItems[]=
        {
            "H_PilotHelmetFighter_B",
            "V_TacVest_grn",
			"G_Balaclava_TI_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "H_PilotHelmetFighter_B",
            "V_TacVest_grn",
			"G_Balaclava_TI_blk_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class AX_B_Navy_Helipilot: EF_B_Marine_Des_Base_1
    {
        scope=2;
        scopeCurator=2;
        author="$STR_A3_IMUS_Axle";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Helipilot.jpg";
        class SpeechVariants
        {
            class Default
            {
                speechSingular[]=
                {
                    "veh_infantry_pilot_s"
                };
                speechPlural[]=
                {
                    "veh_infantry_pilot_p"
                };
            };
        };
        textSingular="$STR_A3_nameSound_veh_infantry_pilot_s";
        textPlural="$STR_A3_nameSound_veh_infantry_pilot_p";
        nameSound="veh_infantry_pilot_s";
        identityTypes[]=
        {
            "LanguageENG_F",
            "Head_NATO",
            "G_NATO_pilot"
        };
        role="Crewman";
        camouflage=2;
        faction="EF_B_MJTF_Navy";
        uniformClass="AX_U_B_USN_HeliPilotCoveralls_Gloves";
        displayName="$STR_B_Helipilot_F0";
        weapons[]=
        {
            "SMG_01_black_Holo_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "SMG_01_black_Holo_F",
            "Throw",
            "Put"
        };
        magazines[]=
        {
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
        respawnMagazines[]=
        {
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "30Rnd_45ACP_Mag_SMG_01",
            "SmokeShellGreen",
            "SmokeShellBlue",
            "SmokeShellOrange"
        };
		linkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Black_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Black_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
    };
	class AX_B_Navy_Helicrew: AX_B_Navy_Helipilot
    {
        author="$STR_A3_IMUS_Axle";
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Helicrew.jpg";
        displayName="$STR_B_helicrew_F0";
        role="Crewman";
        faction="EF_B_MJTF_Navy";
        uniformClass="AX_U_B_USN_HeliPilotCoveralls_Gloves";
        weapons[]=
        {
            "arifle_MXC_Black_Holo_F",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "arifle_MXC_Black_Holo_F",
            "Throw",
            "Put"
        };
        magazines[]=
        {
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
        };
        respawnMagazines[]=
        {
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"30Rnd_65x39_caseless_black_mag",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange"
        };
		linkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Black_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
		respawnLinkedItems[]=
		{
			"H_PilotHelmetHeli_White_RF",
			"AX_V_AAV_Pilot_Black_dirty",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"NVGoggles_OPFOR"
		};
    };
	class AX_B_Navy_Repair: EF_B_Marine_Repair_Des
    {
		scope=1;
		editorPreview="\ax_alternateusmc\editorpreviews_f_usmc\ef\AX_B_Navy_Repair.jpg";
		faction="EF_B_MJTF_Navy";
		displayName="$STR_A3_MCFU_sailor_mechanic_F0";
		uniformClass="AX_U_B_USN_CrewCoveralls_Gloves";
		backpack="AX_B_RaiderPack_black_Repair";
        weapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_01_black_Holo_F",
			"hgun_P07_blk_F",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"30Rnd_45ACP_Mag_SMG_01",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_green"
		};
		linkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"H_Watchcap_blk_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_TacVest_RigB_blk_RF",
			"H_Watchcap_blk_hs",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };