        class SpanishMen
		{
			class FirstNames
			{
				alfredo="Alfredo";
				antonio="Antonio";
				armando="Armando";
				artuo="Artuo";
				carlos="Carlos";
				diego="Diego";
				eduardo="Eduardo";
				elijah="Elijah";
				emmanuel="Emmanuel";
				felipe="Felipe";
				fernando="Fernando";
				francisco="Francisco";
				gabriel="Gabriel";
				gerardo="Gerardo";
				guillermo="Guillermo";
				hector="Hector";
				hugo="Hugo";
				isaac="Isaac";
				jorge="Jorge";
				jose="Jose";
				juan="Juan";
				julian="Julián";
				manuel="Manuel";
				mario="Mario";
				martin="Martín";
				oscar="Oscar";
				orlando="Orlando";
				pablo="Pablo";
				ramon="Ramon";
				raul="Raúl";
				ricardo="Ricardo";
				roberto="Roberto";
				salvador="Salvador";
				santiago="Santiago";
				sebastian="Sebastian";
				victor="Victor";
				xavier="Xavier";
			};
			class LastNames
			{
				alvarez="Alvarez";
				diaz="Diaz";
				fernandez="Fernandez";
				flores="Flores";
				garcia="Garcia";
				gonzalez="Gonzalez";
				guzman="Guzman";
				hernandez="Hernandez";
				jimenez="Jimenez";
				marquez="Marquez";
				mendez="Mendez";
				mendoza="Mendoza";
				morales="Morales";
				moreno="Moreno";
				parra="Parra";
				pena="Peña";
				perez="Perez";
				quintero="Quintero";
				ramirez="Ramirez";
				ramos="Ramos";
				sanchez="Sanchez";
				vargas="Vargas";
				velasquez="Velasquez";
			};
		};