class CfgPatches
{
	class ax_faction_china_grfu_reconhood
	{
		units[]={};
		weapons[]={};
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"ReconCloaks_Characters_Headgear",
			"ax_faction_china_grfu"
		};
		author="Axle";
		skipwhenmissingdependencies=1;
	};
};

class CfgVehicles
{
	class O_sniper_F;
	class O_spotter_F;
	class O_T_Sniper_F: O_sniper_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\O_T_Sniper_F.jpg";
		uniformClass="U_O_T_Soldier_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_ghex",
			"V_TacChestrig_oli_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_ghex",
			"V_TacChestrig_oli_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
	class O_T_Spotter_F: O_spotter_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\O_T_Spotter_F.jpg";
		uniformClass="U_O_T_Soldier_F";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_ghex",
			"V_TacChestrig_oli_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_ghex",
			"V_TacChestrig_oli_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_ghex_F"
		};
    };
	class Aegis_O_C_D_Sniper_F: O_sniper_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Aegis_O_C_D_Sniper_F.jpg";
		uniformClass="U_O_CombatUniform_oicamo";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_hex",
			"V_TacChestrig_cbr_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_hex",
			"V_TacChestrig_cbr_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
	class Aegis_O_C_D_Spotter_F: O_spotter_F
	{
		editorPreview="\ax_grounded_futura\editor_previews_china\expansion\Aegis_O_C_D_Spotter_F.jpg";
		uniformClass="U_O_CombatUniform_oicamo";
		linkedItems[]=
		{
			"ReconCloaks_H_SniperHood_hex",
			"V_TacChestrig_cbr_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
		respawnLinkedItems[]=
		{
			"ReconCloaks_H_SniperHood_hex",
			"V_TacChestrig_cbr_F",
			"AX_G_Balaclava_Goggles_blk_cn",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_hex_F"
		};
	};
};