    class O_R_Patrol_Soldier_A_F: O_R_Soldier_Base_F
    {
        backpack="B_Patrol_Carryall_green_Ammo_F";
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_AR2_F: O_R_Soldier_AR_F
    {
        displayName="$STR_A3_CfgVehicles_B_Patrol_Soldier_MG_F0";
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_AR_F: O_R_Soldier_AR_F
    {
        uniformClass="lk_u_csat_jacket_taiga_oli";
        weapons[]=
        {
            "arifle_AK12_lush_holo_snds_pointer_bipod_F",
            "hgun_Rook40_F",
            "Binocular",
            "Throw",
            "Put"
        };
        respawnWeapons[]=
        {
            "arifle_AK12_lush_holo_snds_pointer_bipod_F",
            "hgun_Rook40_F",
            "Binocular",
            "Throw",
            "Put"
        };
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_Medic: O_R_medic_F
    {
        backpack="B_Patrol_Carryall_taiga_medic_F";
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_Engineer_F: O_R_Soldier_Base_F
    {
        backpack="B_Patrol_FieldPack_green_eng_F";
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_CQB_F",
            "H_HelmetAggressor_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_CQB_F",
            "H_HelmetAggressor_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_GL_F: O_R_Soldier_GL_F
    {
        backpack="B_FieldPack_taiga_F";
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_GL_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_GL_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_M_F: O_R_soldier_M_F
    {
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_M2_F: O_R_soldier_M_F
    {
		weapons[]=
		{
			"AX_srifle_DMR_04_green_DMS_weathered_Kir_F",
			"hgun_Rook40_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_04_green_DMS_weathered_Kir_F",
			"hgun_Rook40_F",
			"RangeFinder",
			"Throw",
			"Put"
		};
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_LAT_F: O_R_Soldier_LAT_F
    {
        backpack="B_FieldPack_taiga_RPG_AT_F";
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_Lite_F",
            "H_HelmetAggressor_cover_taiga_F",
            "O_NVGoggles_grn_F",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };
    class O_R_Patrol_Soldier_TL_F: O_R_Soldier_TL_F
    {
        backpack="B_FieldPack_taiga_F";
        linkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_CQB_F",
            "H_HelmetAggressor_F",
            "O_NVGoggles_grn_F",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
        respawnLinkedItems[]=
        {
            "Aegis_V_OCarrierLuchnik_CQB_F",
            "H_HelmetAggressor_F",
            "O_NVGoggles_grn_F",
            "ItemGPS",
            "ItemMap",
            "ItemCompass",
            "ItemWatch",
            "ItemRadio"
        };
    };