    class O_Soldier_F;
	class O_R_Man_Base_F: O_Soldier_F
	{
	};
    class O_soldier_PG_F;
    class O_R_Soldier_Base_F: O_R_Man_Base_F
	{
        uniformClass="Aegis_U_O_Luchnik_taiga_F";
    };
    class O_R_Soldier_TL_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_TL_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_GL_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_GL_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_exp_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_exp_F.jpg";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AR_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AR_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_M_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_M_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_medic_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_medic_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
		backpack="AX_B_EAssaultPack_taiga_Medic_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_CQBLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_CQBLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_LAT_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_LAT_F.jpg";
		backpack="AX_B_EAssaultPack_taiga_RPG_AT_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_JTAC_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_JTAC_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
        respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_recon_base: O_R_Soldier_Base_F
	{
    };
    class O_R_recon_TL_F: O_R_Soldier_recon_base
	{
    };
    class O_R_recon_exp_F: O_R_Soldier_recon_base
	{
    };
    class O_R_recon_AR_F: O_R_Soldier_recon_base
	{
    };
    class O_R_recon_M_F: O_R_Soldier_recon_base
	{
		weapons[]=
		{
			"AX_srifle_DMR_04_green_DMS_weathered_Kir_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_04_green_DMS_weathered_Kir_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
    class O_R_recon_medic_F: O_R_Soldier_recon_base
	{
    };
    class O_R_recon_GL_F: O_R_Soldier_recon_base
	{
    };
    class O_R_recon_LAT_F: O_R_Soldier_recon_base
	{
    };
    class O_R_recon_JTAC_F: O_R_Soldier_recon_base
	{
    };
    class O_R_Soldier_A_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_A_F.jpg";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AAR_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AAA_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
		backpack="AX_B_EAssaultPack_green_AAR_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_AMG_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_AMG_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_AMort_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_AMort_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AHAT_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_AMort_F.jpg";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AAA_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AAA_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AAT_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AAT_F.jpg";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_crew_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_crew_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_F",
			"H_Tank_black_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_F",
			"H_Tank_black_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_engineer_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_engineer_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_mine_F: O_R_soldier_exp_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_mine_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_GMG_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_GMG_F.jpg";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_MG_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_MG_F.jpg";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_Mort_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_Mort_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_helipilot_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_helipilot_F.jpg";
    };
    class O_R_helicrew_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_helicrew_F.jpg";
    };
    class O_R_soldier_AA_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_AA_F.jpg";
		backpack="AX_B_EAssaultPack_green_AA_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_AT_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_AT_F.jpg";
		backpack="AX_B_EAssaultPack_green_AT_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_officer_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_officer_F.jpg";
        linkedItems[]=
		{
			"V_Rangemaster_belt_taiga_F",
			"H_MilCap_taiga",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_Rangemaster_belt_taiga_F",
			"H_MilCap_taiga",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_R_soldier_repair_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_repair_F.jpg";
		backpack="AX_B_EAssaultPack_taiga_Repair_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_HAT_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_HAT_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
		backpack="AX_B_EAssaultPack_taiga_HAT_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_lite_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_lite_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"V_BandollierB_taiga_F",
			"H_MilCap_taiga",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_taiga_F",
			"H_MilCap_taiga",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_R_Soldier_CQ_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_CQ_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_SL_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_SL_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_CBRN_F: O_R_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_CBRN_F.jpg";
        uniformClass="AX_U_O_CBRN_Suit_01_Taiga_F";
		backpack="B_CombinationUnitRespirator_01_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_RadioOperator_F: O_R_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_RadioOperator_F.jpg";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
	class Aegis_O_R_Sharpshooter_F: O_R_soldier_M_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\Aegis_O_R_Sharpshooter_F.jpg";
	};
    class O_R_soldier_UAV_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_taiga_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"O_UavTerminal",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_UAV_06_F: O_R_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_06_F.jpg";
    };
    class O_R_soldier_UAV_06_medical_F: O_R_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_06_medical_F.jpg";
    };
    class O_R_soldier_UGV_02_Demining_F: O_R_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UGV_02_Demining_F.jpg";
    };
    class O_R_soldier_UAV_02_lxWS_F: O_R_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_02_lxWS_F.jpg";
    };
    class O_R_Soldier_PG_F: O_soldier_PG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_PG_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_taiga_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_diver_base: O_R_Soldier_Base_F
	{
    };
    class O_R_diver_F: O_R_Soldier_diver_base
	{
    };
    class O_R_diver_exp_F: O_R_Soldier_diver_base
	{
    };
    class O_R_diver_TL_F: O_R_Soldier_diver_base
	{
    };
    class O_R_recon_F: O_R_Soldier_recon_base
	{
    };
    class O_R_recon_CQ_F: O_R_Soldier_recon_base
	{
    };
    class O_R_Soldier_sniper_base: O_R_Soldier_Base_F
	{
    };
    class O_R_ghillie_base_F: O_R_Soldier_sniper_base
	{
    };
	class O_R_spotter_F: O_R_ghillie_base_F
	{
		uniformClass="AX_U_O_R_FullGhillie_frst_F";
    };
    class O_R_sniper_F: O_R_ghillie_base_F
	{
		uniformClass="AX_U_O_R_FullGhillie_frst_F";
    };
    class O_R_Soldier_universal_F: O_R_Soldier_F
	{
    };
    class O_R_Survivor_F: O_R_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Survivor_F.jpg";
    };
    class O_R_Soldier_unarmed_F: O_R_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_unarmed_F.jpg";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_F",
			"H_HelmetLuchnik_cover_rutaiga_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_R_ghillie_wdl_F: O_R_ghillie_base_F
	{
    };
    class O_R_ghillie_spotter_wdl_F: O_R_ghillie_wdl_F
	{
    };
    class O_R_Fighter_Pilot_F: O_R_Soldier_Base_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Fighter_Pilot_F.jpg";
    };