    class O_R_Soldier_A_ard_F: O_R_Soldier_A_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_A_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AAR_ard_F: O_R_Soldier_AAR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AAR_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
		backpack="AX_B_EAssaultPack_green_AAR_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_AMG_ard_F: O_R_support_AMG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_AMG_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_AMort_ard_F: O_R_support_AMort_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_AMort_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AHAT_ard_F: O_R_Soldier_AHAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AHAT_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AAA_ard_F: O_R_Soldier_AAA_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AAA_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_AAT_ard_F: O_R_Soldier_AAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_AAT_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_AR_ard_F: O_R_Soldier_AR_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_AR_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_CQB_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_medic_ard_F: O_R_medic_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_medic_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
		backpack="AX_B_EAssaultPack_arid_Medic_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_CQBLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_CQBLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_crew_ard_F: O_R_crew_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_crew_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_arid_F",
			"H_Tank_black_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_arid_F",
			"H_Tank_black_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_engineer_ard_F: O_R_engineer_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_engineer_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_exp_ard_F: O_R_soldier_exp_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_exp_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_mine_ard_F: O_R_soldier_exp_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_mine_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_GLLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_GL_ard_F: O_R_Soldier_GL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_GL_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_GMG_ard_F: O_R_support_GMG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_GMG_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_MG_ard_F: O_R_support_MG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_MG_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_support_Mort_ard_F: O_R_support_Mort_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_support_Mort_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_helipilot_ard_F: O_R_helipilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_helipilot_ard_F.jpg";
    };
    class O_R_helicrew_ard_F: O_R_helicrew_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_helicrew_ard_F.jpg";
    };
    class O_R_soldier_M_ard_F: O_R_soldier_M_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_M_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
	class Aegis_O_R_Sharpshooter_ard_F: Aegis_O_R_Sharpshooter_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\Aegis_O_R_Sharpshooter_ard_F.jpg";
		uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
	};
    class O_R_soldier_AA_ard_F: O_R_soldier_AA_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_AA_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
		backpack="AX_B_EAssaultPack_green_AA_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_AT_ard_F: O_R_soldier_AT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_AT_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
		backpack="AX_B_EAssaultPack_green_AT_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_officer_ard_F: O_R_officer_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_officer_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_officer_arid_F";
    };
    class O_R_soldier_repair_ard_F: O_R_soldier_repair_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_repair_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
		backpack="AX_B_EAssaultPack_arid_Repair_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_ard_F: O_R_Soldier_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_HAT_ard_F: O_R_Soldier_HAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_HAT_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
		backpack="AX_B_EAssaultPack_arid_HAT_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
	class O_R_Soldier_lite_ard_F: O_R_Soldier_lite_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_lite_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"V_BandollierB_cbr",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_LAT_ard_F: O_R_Soldier_LAT_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_LAT_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
		backpack="AX_B_EAssaultPack_arid_RPG_AT_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_CQ_ard_F: O_R_Soldier_CQ_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_CQ_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_SL_ard_F: O_R_Soldier_SL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_SL_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_TL_ard_F: O_R_Soldier_TL_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_TL_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_GL_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_Soldier_CBRN_ard_F: O_R_Soldier_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_CBRN_ard_F.jpg";
        uniformClass="AX_U_O_CBRN_Suit_01_Arid_F";
		backpack="B_CombinationUnitRespirator_01_F";
		linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"G_AirPurifyingRespirator_02_olive_F",
			"ItemMap",
			"ItemCompass",
			"ChemicalDetector_01_watch_F",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_RadioOperator_ard_F: O_R_Soldier_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_RadioOperator_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_UAV_ard_F: O_R_soldier_UAV_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_RolledUp_arid_F";
        linkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"AX_V_OCarrierLuchnik_SuperLite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_soldier_UAV_06_ard_F: O_R_soldier_UAV_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_06_ard_F.jpg";
    };
    class O_R_soldier_UAV_06_medical_ard_F: O_R_soldier_UAV_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_06_medical_ard_F.jpg";
    };
    class O_R_soldier_UGV_02_Demining_ard_F: O_R_soldier_UAV_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UGV_02_Demining_ard_F.jpg";
    };
    class O_R_soldier_UAV_02_ard_lxWS_F: O_R_soldier_UAV_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_soldier_UAV_02_ard_lxWS_F.jpg";
    };
    class O_R_Soldier_PG_ard_F: O_R_Soldier_PG_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_PG_ard_F.jpg";
        uniformClass="Aegis_U_O_Luchnik_arid_F";
        linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"O_NVGoggles_grn_F"
		};
    };
    class O_R_diver_ard_F: O_R_diver_F
	{
    };
    class O_R_diver_exp_ard_F: O_R_diver_exp_F
	{
    };
    class O_R_diver_TL_ard_F: O_R_diver_TL_F
	{
    };
    class O_R_recon_TL_ard_F: O_R_recon_TL_F
	{
    };
    class O_R_recon_exp_ard_F: O_R_recon_exp_F
	{
    };
    class O_R_recon_AR_ard_F: O_R_recon_AR_F
	{
    };
    class O_R_recon_M_ard_F: O_R_recon_M_F
	{
		weapons[]=
		{
			"AX_srifle_DMR_04_tan_DMS_weathered_Kir_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
		respawnWeapons[]=
		{
			"AX_srifle_DMR_04_tan_DMS_weathered_Kir_F",
			"hgun_Rook40_snds_F",
			"Throw",
			"Put",
			"Rangefinder"
		};
    };
    class O_R_recon_medic_ard_F: O_R_recon_medic_F
	{
    };
    class O_R_recon_GL_ard_F: O_R_recon_GL_F
	{
    };
    class O_R_recon_LAT_ard_F: O_R_recon_LAT_F
	{
    };
    class O_R_recon_JTAC_ard_F: O_R_recon_JTAC_F
	{
    };
    class O_R_recon_ard_F: O_R_recon_F
	{
    };
    class O_R_recon_CQ_ard_F: O_R_recon_CQ_F
	{
    };
    class O_R_spotter_ard_F: O_R_spotter_F
	{
		uniformClass="AX_U_O_R_FullGhillie_dsrt_F";
    };
    class O_R_sniper_ard_F: O_R_sniper_F
	{
		uniformClass="AX_U_O_R_FullGhillie_dsrt_F";
    };
    class O_R_Soldier_universal_ard_F: O_R_Soldier_ard_F
	{
    };
    class O_R_Survivor_ard_F: O_R_Soldier_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Survivor_ard_F.jpg";
    };
    class O_R_Soldier_unarmed_ard_F: O_R_Soldier_ard_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Soldier_unarmed_ard_F.jpg";
		linkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_OCarrierLuchnik_Lite_arid_F",
			"H_HelmetLuchnik_cover_ruarid_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class O_R_ghillie_ard_F: O_R_ghillie_base_F
	{
    };
    class O_R_ghillie_lsh_F: O_R_ghillie_base_F
	{
    };
    class O_R_ghillie_sard_F: O_R_ghillie_base_F
	{
    };
    class O_R_ghillie_spotter_ard_F: O_R_ghillie_ard_F
	{
    };
    class O_R_ghillie_spotter_lsh_F: O_R_ghillie_lsh_F
	{
    };
    class O_R_ghillie_spotter_sard_F: O_R_ghillie_sard_F
	{
    };
    class O_R_Fighter_Pilot_ard_F: O_R_Fighter_Pilot_F
	{
		editorPreview="\ax_grounded_futura\editor_previews\enoch\O_R_Fighter_Pilot_ard_F.jpg";
    };
    