    class Aegis_O_R_Conscript_Base_F: O_R_Soldier_Base_F
	{
    };
    class Aegis_O_R_Conscript_SL_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_TL_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AT_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_M_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_GL_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AR_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_headset_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Medic_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Repair_F: Aegis_O_R_Conscript_Base_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUtaiga_F",
			"H_HelmetLuchnik_olive_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_SL_ard_F: Aegis_O_R_Conscript_SL_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemGPS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_TL_ard_F: Aegis_O_R_Conscript_TL_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_ard_F: Aegis_O_R_Conscript_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AT_ard_F: Aegis_O_R_Conscript_AT_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_M_ard_F: Aegis_O_R_Conscript_M_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_GL_ard_F: Aegis_O_R_Conscript_GL_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_AR_ard_F: Aegis_O_R_Conscript_AR_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_headset_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Medic_ard_F: Aegis_O_R_Conscript_Medic_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    class Aegis_O_R_Conscript_Repair_ard_F: Aegis_O_R_Conscript_Repair_F
	{
        linkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Aegis_V_ChestrigEast_RUarid_F",
			"H_HelmetLuchnik_khk_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
    };
    